import { siteConfig } from "@/config/site";

export const electricBillCalculatorConfig = {
  name: "Electric Bill Calculator",
  slug: "electric-bill-calculator",
  category: "electrical",
  description: "Estimate your electricity bill from kWh or appliance watts at your own price per kWh. Flat or tiered rates, fixed charges and tax, in any currency.",
  icon: "⚡",
  color: "#f59e0b",
  featured: false,
  keywords: [
    "electric bill calculator",
    "electricity bill calculator",
    "electricity cost calculator",
    "kwh cost calculator",
    "electricity cost per kwh calculator",
    "how to calculate electric bill",
    "watts to kwh calculator",
    "appliance electricity cost calculator",
    "energy bill estimator",
    "electricity bill estimator",
    "monthly electricity bill calculator",
    "utility bill calculator",
    "tiered electricity rate calculator",
    "electricity tariff calculator",
    "calculate electricity bill from units",
    "electricity bill calculator with tax",
    "standing charge calculator",
    "kwh to bill calculator",
    "commercial electricity bill calculator",
    "free electric bill calculator",
  ],
  seo: {
    title: "Electric Bill Calculator – kWh & Appliance Cost Estimator",
    description: "Estimate your electric bill from kWh or appliance watts at your own rate. Flat or tiered pricing, standing charges and tax, in $, €, £ and more.",
    keywords: "electric bill calculator, electricity cost calculator, kwh cost calculator, watts to kwh calculator, appliance electricity cost, how to calculate electric bill",
    openGraph: {
      title: "Electric Bill Calculator – kWh & Appliance Cost Estimator",
      description: "Estimate your electric bill from kWh or appliance watts at your own price per kWh, with flat or tiered rates, fixed charges and tax.",
      type: "website",
      url: `${siteConfig.url}/tools/electrical/electric-bill-calculator`,
    },
    og: {
      title: "Electric Bill Calculator – kWh & Appliance Cost Estimator",
      description: "Estimate your electric bill from kWh or appliance watts at your own price per kWh, with flat or tiered rates, fixed charges and tax.",
      type: "website",
      url: `${siteConfig.url}/tools/electrical/electric-bill-calculator`,
    },
    howToSteps: [
      { name: "Enter your usage", text: "Type the kWh from your bill or meter, or switch to \"Estimate from watts\" and list your appliances with their watts and hours of use per day." },
      { name: "Choose your currency", text: "The calculator starts in your local currency; change it if your bill is in another one." },
      { name: "Enter your price per kWh", text: "Copy the energy (unit) rate from your bill, or pick a preset such as the U.S. average, the UK price cap or the EU average." },
      { name: "Switch to tiered if your utility uses tiers", text: "If your tariff charges more per kWh above a threshold, choose Tiered and enter each band's range and rate." },
      { name: "Add fixed charges and tax", text: "Enter any monthly service, customer or standing charge and the tax percentage shown on your bill." },
      { name: "Read the total", text: "The total bill, energy cost, tax and a line-by-line breakdown update as you type; copy, save or export them." },
    ],
    faq: [
      { q: "How do I calculate my electric bill?", a: "Multiply the kWh you used by your price per kWh, then add fixed charges and tax: Bill = (kWh × price per kWh) + fixed charges + tax. For example, 900 kWh at $0.18/kWh is $162.00 of energy, before any customer charge or tax." },
      { q: "How do I convert watts to kWh?", a: "kWh = watts × hours ÷ 1,000. A 1,500 W space heater running 4 hours a day for 30 days uses 1,500 × 4 × 30 ÷ 1,000 = 180 kWh, which costs $32.40 at $0.18/kWh." },
      { q: "What is a kWh?", a: "A kilowatt-hour (kWh) is the unit of energy on your bill: 1,000 watts used for one hour. A 100 W TV running for 10 hours also uses 1 kWh." },
      { q: "What is the average electricity price per kWh?", a: "About 18¢ per kWh for U.S. homes in 2026 (EIA), from roughly 13¢ in the cheapest states to over 50¢ in Hawaii. The EU household average was about €0.29 per kWh including taxes in the second half of 2025 (Eurostat), and the UK price cap for October–December 2026 is 26.32p per kWh plus a 54.83p daily standing charge (Ofgem)." },
      { q: "What is a standing charge?", a: "A fixed daily fee for being connected to the grid, charged even if you use no electricity. It is common in the UK and Europe. Multiply it by the days in your bill and enter it as the service charge, for example 54.83p × 30 days = £16.45." },
      { q: "Should I add tax?", a: "Only if your rate excludes it. UK price-cap rates and the Eurostat averages already include VAT and taxes, so leave tax at 0 when you use them. Many U.S. bills list state or local taxes separately; enter that percentage in the tax field." },
      { q: "What is tiered (block) electricity pricing?", a: "Your usage is split into bands with their own price, and each band is charged only for the kWh inside it. With 0–500 kWh at $0.15 and 501+ at $0.20, a 700 kWh month costs 500 × 0.15 + 200 × 0.20 = $115." },
      { q: "Why is my calculated bill different from my actual bill?", a: "Utilities often add delivery or transmission charges, fuel or energy adjustments, regulatory fees and rounding. Enter the all-in average by dividing your total bill by the kWh used, or add the extra fees as service charges, to match your bill." },
      { q: "Which appliances use the most electricity?", a: "Anything that heats or cools: water heaters, space heaters, air conditioners, clothes dryers and EV chargers. A 4,500 W tank water heater running 3 hours a day uses about 405 kWh a month, while an LED bulb uses 1.5 kWh." },
      { q: "Is my data private?", a: "Yes. Everything is calculated in your browser, and saved history stays in your browser's local storage. Nothing is sent to a server." },
    ],
  },
  relatedTools: [
    "energy-consumption-calculator",
    "power-calculator-electrical",
    "solar-panel-calculator",
    "air-conditioner-power-calculator",
    "wire-size-calculator",
  ],
};
