export const bionicReadingConverterConfig = {
  name: "Bionic Reading Converter",
  slug: "bionic-reading-converter",
  description: "Convert text to Bionic Reading style for faster reading and better comprehension",
  category: "text",
  icon: "👁️",
  keywords: [
    "bionic reading",
    "speed reading",
    "reading enhancement",
    "text converter",
    "bold text",
    "reading tool",
    "fast reading",
    "text formatter",
    "reading speed",
    "comprehension tool",
    "text styling",
    "reading aid",
    "bionic text",
    "reading optimizer",
    "text processor",
    "reading converter",
    "frontend text tool",
    "reading improvement"
  ],
  seo: {
    title: "Bionic Reading Converter Online - Convert Text with Adjustable Emphasis",
    description: "Free Bionic Reading Converter with adjustable bold percentage, small-word filtering, preview controls, and HTML/TXT/Markdown export. Convert text and copy results instantly.",
    keywords: [
      "bionic reading",
      "speed reading",
      "reading enhancement",
      "text converter",
      "bold text",
      "reading tool",
      "fast reading",
      "text formatter",
      "reading speed",
      "comprehension tool",
      "text styling",
      "reading aid",
      "bionic text",
      "reading optimizer",
      "text processor",
      "reading converter",
      "frontend text tool",
      "reading improvement",
      "bionic text converter",
      "bionic reading generator",
      "bold word converter",
      "reading format converter",
      "bionic markdown converter",
      "bionic html export",
      "focus reading tool",
      "reading text formatter",
      "adaptive reading converter"
    ],
    openGraph: {
      title: "Bionic Reading Converter - Adjustable Text Emphasis and Export",
      description: "Convert text to bionic style with customizable settings and export-ready output formats.",
      type: "website",
      url: "/tools/writing/bionic-reading-converter"
    }
  }
};
