import { siteConfig } from "@/config/site";

export const electricMotorPowerCalculatorConfig = {
  name: "Electric Motor Power Calculator",
  slug: "electric-motor-power-calculator",
  description: "Calculate electric motor power, current, torque, and efficiency. Supports HP to kW conversion, three-phase and single-phase motors, and motor energy cost analysis.",
  category: "electrical",
  icon: "⚙️",
  free: true,
  backend: false,
  seo: {
    title: "Motor Power Calculator — HP, kW, 3 Phase",
    description: "Convert motor power between HP and kW and find current draw for single-phase and three-phase motors at any voltage, efficiency and power factor.",
    keywords: [
      "electric motor power calculator",
      "motor power calculator",
      "motor kw calculator",
      "motor power formula",
      "hp to kw motor calculator",
      "motor current calculator",
      "calculate motor power",
      "3 phase motor power calculator",
      "motor torque calculator",
      "electric motor calculator",
      "motor efficiency calculator",
      "motor power consumption calculator",
      "kw to hp motor converter",
      "motor full load current calculator",
      "calculating motor power",
      "motor power calculation formula",
      "single phase motor power calculator",
      "motor kva calculator",
      "motor input power calculator",
      "motor hp calculator",
      "induction motor power calculator",
      "motor energy cost calculator",
      "electric motor kw to amps",
      "motor torque from power and speed",
      "free motor power calculator",
    ],
    openGraph: {
      title: "Electric Motor Power Calculator — Motor kW, Current & Torque",
      description: "Calculate motor power, full-load current, torque, and efficiency for 3-phase and single-phase AC motors. HP to kW, kW to amps, torque from RPM.",
      type: "website",
      url: `${siteConfig.url}/tools/electrical/electric-motor-power-calculator`,
    },
    og: {
      title: "Electric Motor Power Calculator — Motor kW, Current & Torque",
      description: "Calculate motor power, full-load current, torque, and efficiency for 3-phase and single-phase AC motors. HP to kW, kW to amps, torque from RPM.",
      url: `${siteConfig.url}/tools/electrical/electric-motor-power-calculator`,
    },
    howToSteps: [
      { name: "Choose a calculation method", text: "Pick Mechanical (torque and speed), Electrical (voltage and current) or Horsepower Conversion, or load a preset such as a 480 V or 400 V three-phase motor, a conveyor drive or a 24 V DC motor." },
      { name: "Mechanical: enter torque and speed", text: "Type the shaft torque in newton-meters and the speed in RPM. Power = 2π × RPM × torque ÷ 60." },
      { name: "Electrical: enter the supply values", text: "Choose single-phase AC, three-phase AC or DC, then enter voltage, current, power factor and efficiency from the nameplate. Three-phase uses the line-to-line voltage and the √3 factor." },
      { name: "Read the power", text: "The result shows the power in watts, kilowatts and horsepower, with each step of the working." },
      { name: "Copy, export or save", text: "Copy the result, download it as text or CSV, or reopen earlier calculations from the history." },
    ],
    faq: [
      { q: "What is the formula for electric motor power?", a: "3-phase: Output (kW) = √3 × V × I × PF × η ÷ 1000. Single-phase: Output (kW) = V × I × PF × η ÷ 1000. Input power = Output ÷ Efficiency." },
      { q: "How do I convert motor horsepower to kW?", a: "1 HP = 0.7457 kW. Multiply HP by 0.7457 to get kW. Examples: 5 HP = 3.73 kW; 10 HP = 7.46 kW; 15 HP = 11.19 kW; 20 HP = 14.91 kW." },
      { q: "How do I calculate motor current from kW?", a: "3-phase: I = kW × 1000 ÷ (√3 × V × PF × η). Single-phase: I = kW × 1000 ÷ (V × PF × η). Example: 7.5 kW at 400 V, PF 0.85, η 90% → I = 7,500 ÷ (1.732 × 400 × 0.85 × 0.9) ≈ 14.2 A." },
      { q: "What is motor efficiency?", a: "Motor efficiency is shaft output power divided by electrical input power. A 90% efficient 10 kW motor consumes 11.1 kW. Efficiency drops at partial load — motors are most efficient at 75–100% of rated load." },
      { q: "How do I calculate motor torque from power and speed?", a: "Torque (N·m) = kW × 9,549 ÷ RPM. Example: 5 kW at 1,450 RPM → 5 × 9,549 ÷ 1,450 = 32.9 N·m. In imperial: Torque (lb·ft) = HP × 5,252 ÷ RPM." },
      { q: "What is power factor in an electric motor?", a: "Power factor is real power (kW) divided by apparent power (kVA). Motors typically have PF 0.75–0.95 at full load. It drops significantly at partial loads. Low PF increases current draw and conductor sizing requirements." },
      { q: "What is the difference between kW and kVA for motors?", a: "kW is real power (actual work done). kVA is apparent power (total drawn from supply). kW = kVA × Power Factor. Generator and transformer sizing must use kVA, not kW." },
      { q: "Why is √3 used in three-phase motor calculations?", a: "√3 (1.7321) is the three-phase constant that accounts for the phase relationship between the three supply conductors. Omitting it in three-phase calculations produces a result 42% too low." },
      { q: "How do I size a motor for an application?", a: "Calculate required shaft output from the mechanical load (P = F × v or P = T × ω). Apply a 1.15–1.25 service factor. Select the next standard motor rating above the result from the IEC standard series: 0.37, 0.55, 0.75, 1.1, 1.5, 2.2, 3, 4, 5.5, 7.5, 11, 15, 22, 30, 37, 45, 55, 75 kW." },
      { q: "Is my data private when using this calculator?", a: "Yes. We do not collect or store what you enter." },
    ],
  },
  features: [
    "Power from shaft torque and speed (RPM)",
    "Power from voltage, current, power factor and efficiency",
    "Single-phase AC, three-phase AC and DC supplies",
    "Horsepower to watts and kilowatts",
    "Results in W, kW and HP with step-by-step working",
    "Presets for common motors",
    "Copy, export as text or CSV, and history",
    "Your inputs are not collected or stored",
  ],
  relatedTools: [
    "air-conditioner-power-calculator",
    "wire-size-calculator",
    "ups-load-calculator",
    "generator-size-calculator",
    "electrical-efficiency-calculator",
    "reactive-power-calculator",
  ],
};
