import { siteConfig } from "@/config/site";

export const electricMotorPowerCalculatorConfig = {
  name: "Electric Motor Power Calculator",
  slug: "electric-motor-power-calculator",
  description: "Calculate electric motor power, current, torque, and efficiency. Supports HP to kW conversion, three-phase and single-phase motors, and motor energy cost analysis.",
  category: "electrical",
  icon: "⚙️",
  free: true,
  backend: false,
  seo: {
    title: "Electric Motor Power Calculator — Motor kW, Current & Torque | Productive Toolbox",
    description: "Calculate motor power in kW or HP, full-load current, torque, and efficiency. Free motor power calculator for 3-phase and single-phase AC motors. No signup.",
    keywords: [
      "electric motor power calculator",
      "motor power calculator",
      "motor kw calculator",
      "motor power formula",
      "hp to kw motor calculator",
      "motor current calculator",
      "calculate motor power",
      "3 phase motor power calculator",
      "motor torque calculator",
      "electric motor calculator",
      "motor efficiency calculator",
      "motor power consumption calculator",
      "kw to hp motor converter",
      "motor full load current calculator",
      "calculating motor power",
      "motor power calculation formula",
      "single phase motor power calculator",
      "motor kva calculator",
      "motor input power calculator",
      "motor hp calculator",
      "induction motor power calculator",
      "motor energy cost calculator",
      "electric motor kw to amps",
      "motor torque from power and speed",
      "free motor power calculator",
    ],
    openGraph: {
      title: "Electric Motor Power Calculator — Motor kW, Current & Torque",
      description: "Calculate motor power, full-load current, torque, and efficiency for 3-phase and single-phase AC motors. HP to kW, kW to amps, torque from RPM.",
      type: "website",
      url: `${siteConfig.url}/tools/electrical/electric-motor-power-calculator`,
    },
    og: {
      title: "Electric Motor Power Calculator — Motor kW, Current & Torque",
      description: "Calculate motor power, full-load current, torque, and efficiency for 3-phase and single-phase AC motors. HP to kW, kW to amps, torque from RPM.",
      url: `${siteConfig.url}/tools/electrical/electric-motor-power-calculator`,
    },
    howToSteps: [
      { name: "Select Motor Type", text: "Choose single-phase or three-phase AC motor, or DC motor. This determines which formula set is used." },
      { name: "Enter Known Motor Parameters", text: "Input any combination of rated power (HP or kW), supply voltage, rated current, efficiency (%), and power factor from the nameplate or datasheet." },
      { name: "Read All Calculated Outputs", text: "Results show output power (kW and HP), input power, full-load current, torque at rated speed, apparent power (kVA), and monthly energy consumption." },
      { name: "Use the Torque Calculator Tab", text: "Switch to the torque tab to calculate shaft torque from power and speed (RPM), or find required power from a torque and speed requirement." },
      { name: "Check the Efficiency Comparison", text: "Enter two motors with different efficiency ratings to see the annual energy cost difference — useful for justifying IE3 or IE4 premium efficiency motor selection." },
    ],
    faq: [
      { q: "What is the formula for electric motor power?", a: "3-phase: Output (kW) = √3 × V × I × PF × η ÷ 1000. Single-phase: Output (kW) = V × I × PF × η ÷ 1000. Input power = Output ÷ Efficiency." },
      { q: "How do I convert motor horsepower to kW?", a: "1 HP = 0.7457 kW. Multiply HP by 0.7457 to get kW. Examples: 5 HP = 3.73 kW; 10 HP = 7.46 kW; 15 HP = 11.19 kW; 20 HP = 14.91 kW." },
      { q: "How do I calculate motor current from kW?", a: "3-phase: I = kW × 1000 ÷ (√3 × V × PF × η). Single-phase: I = kW × 1000 ÷ (V × PF × η). Example: 7.5 kW, 415V, PF 0.85, η 90% → I = 13.7A." },
      { q: "What is motor efficiency?", a: "Motor efficiency is shaft output power divided by electrical input power. A 90% efficient 10 kW motor consumes 11.1 kW. Efficiency drops at partial load — motors are most efficient at 75–100% of rated load." },
      { q: "How do I calculate motor torque from power and speed?", a: "Torque (N·m) = kW × 9,549 ÷ RPM. Example: 5 kW at 1,450 RPM → 5 × 9,549 ÷ 1,450 = 32.9 N·m. In imperial: Torque (lb·ft) = HP × 5,252 ÷ RPM." },
      { q: "What is power factor in an electric motor?", a: "Power factor is real power (kW) divided by apparent power (kVA). Motors typically have PF 0.75–0.95 at full load. It drops significantly at partial loads. Low PF increases current draw and conductor sizing requirements." },
      { q: "What is the difference between kW and kVA for motors?", a: "kW is real power (actual work done). kVA is apparent power (total drawn from supply). kW = kVA × Power Factor. Generator and transformer sizing must use kVA, not kW." },
      { q: "Why is √3 used in three-phase motor calculations?", a: "√3 (1.7321) is the three-phase constant that accounts for the phase relationship between the three supply conductors. Omitting it in three-phase calculations produces a result 42% too low." },
      { q: "How do I size a motor for an application?", a: "Calculate required shaft output from the mechanical load (P = F × v or P = T × ω). Apply a 1.15–1.25 service factor. Select the next standard motor rating above the result from the IEC standard series: 0.37, 0.55, 0.75, 1.1, 1.5, 2.2, 3, 4, 5.5, 7.5, 11, 15, 22, 30, 37, 45, 55, 75 kW." },
      { q: "Is my data private when using this calculator?", a: "Yes. All calculations run in your browser. Your motor specs and electrical parameters are never transmitted to any server or stored outside your device." },
    ],
  },
  features: [
    "Output power in kW and HP",
    "Input electrical power (kW)",
    "Full-load current (amps)",
    "Shaft torque (N·m and lb·ft)",
    "Apparent power (kVA)",
    "Monthly energy consumption (kWh)",
    "HP ↔ kW ↔ BTU/h conversion",
    "Three-phase and single-phase support",
    "Efficiency comparison mode",
    "Motor sizing guidance",
    "No signup required",
  ],
  relatedTools: [
    "air-conditioner-power-calculator",
    "wire-size-calculator",
    "ups-load-calculator",
    "generator-size-calculator",
    "electrical-efficiency-calculator",
    "reactive-power-calculator",
  ],
};
