export const aspectRatioCalculatorConfig = {
  slug: "aspect-ratio-calculator",
  name: "Aspect Ratio Calculator",
  description: "Calculate image and video dimensions with visual preview and CSS generation",
  category: "design",
  icon: "📐",
  free: true,
  backend: false,
  seo: {
    title: "Aspect Ratio Calculator – Calculate Image & Video Dimensions",
    description: "Free online aspect ratio calculator to calculate width and height, convert resolutions, detect image ratio, simplify proportions, and generate responsive CSS.",
    keywords: [
      "aspect ratio calculator",
      "free aspect ratio calculator",
      "image dimensions calculator",
      "video aspect ratio",
      "16:9 calculator",
      "9:16 calculator",
      "1:1 aspect ratio calculator",
      "aspect ratio converter",
      "resolution calculator",
      "image resize calculator",
      "css aspect ratio",
      "css aspect-ratio generator",
      "responsive image calculator",
      "video dimensions",
      "aspect ratio tool",
      "image proportions",
      "screen ratio calculator",
      "photo aspect ratio",
      "width and height calculator",
      "image ratio detector",
      "social media image size calculator",
      "video size calculator",
      "aspect ratio simplifier",
      "pixel ratio calculator",
      "responsive video embed calculator"
    ],
    openGraph: {
      title: "Aspect Ratio Calculator – Calculate Image & Video Dimensions",
      description: "Calculate dimensions, visualize ratios, and generate responsive CSS instantly in your browser.",
      type: "website",
      url: "/aspect-ratio-calculator"
    },
    howToSteps: [
      { name: "Enter width", text: "Enter width, height, or ratio values." },
      { name: "Use any two inputs and the third value is calculated automatically", text: "Use any two inputs and the third value is calculated automatically." },
      { name: "Review the simplified ratio for clean reporting", text: "Review the simplified ratio for clean reporting." },
      { name: "Use the preview box to confirm visual proportions", text: "Use the preview box to confirm visual proportions." },
      { name: "Copy dimensions or export output as JSON or text", text: "Copy dimensions or export output as JSON or text." },
    ],
    faq: [
      { q: "What is the most common video aspect ratio?", a: "16:9 is the most common standard for modern video playback across web, streaming, and presentation contexts." },
      { q: "How do I calculate height from width and ratio?", a: "Use Height = (Width x Ratio Height) / Ratio Width. This calculator does it instantly and updates all related outputs." },
      { q: "Can this tool simplify ratios automatically?", a: "Yes. Enter dimensions like 3840 x 2160 and the tool simplifies to 16:9 automatically." },
      { q: "What aspect ratio is 1920 × 1080?", a: "16:9. Divide both numbers by their greatest common divisor, 120, to get 16 and 9. 1280 × 720, 2560 × 1440 and 3840 × 2160 (4K) are 16:9 as well." },
      { q: "Can I use this for responsive web design?", a: "Yes. Use generated CSS to maintain consistent media blocks and reduce layout shift on different screen sizes." },
      { q: "Does image upload help detect unknown ratios?", a: "Yes. Upload any image and the tool reads dimensions and calculated ratio so you can resize accurately." },
    ],
  },
  features: [
    "Auto-calculate width, height, or ratio",
    "Visual preview box with live updates",
    "Resize simulator (100px - 4000px)",
    "8 preset aspect ratios",
    "Image upload ratio detection",
    "CSS aspect-ratio generator",
    "Legacy padding-top CSS",
    "Responsive container code",
    "Resolution converter",
    "Automatic ratio simplifier",
    "Common resolutions (720p-8K)",
    "Copy dimensions to clipboard",
    "Export as JSON or TXT",
    "100% client-side processing",
    "Mobile responsive design",
    "Instant calculations"
  ]
};
