export const aspectRatioCalculatorConfig = {
  slug: "aspect-ratio-calculator",
  name: "Aspect Ratio Calculator",
  description: "Calculate image and video dimensions with visual preview and CSS generation",
  category: "design",
  icon: "📐",
  free: true,
  backend: false,
  seo: {
    title: "Aspect Ratio Calculator – Calculate Image & Video Dimensions",
    description: "Find a missing width or height, simplify ratios like 1920×1080 to 16:9, convert resolutions, read an image's ratio and get responsive CSS.",
    keywords: [
      "aspect ratio calculator",
      "free aspect ratio calculator",
      "image dimensions calculator",
      "video aspect ratio",
      "16:9 calculator",
      "9:16 calculator",
      "1:1 aspect ratio calculator",
      "aspect ratio converter",
      "resolution calculator",
      "image resize calculator",
      "css aspect ratio",
      "css aspect-ratio generator",
      "responsive image calculator",
      "video dimensions",
      "aspect ratio tool",
      "image proportions",
      "screen ratio calculator",
      "photo aspect ratio",
      "width and height calculator",
      "image ratio detector",
      "social media image size calculator",
      "video size calculator",
      "aspect ratio simplifier",
      "pixel ratio calculator",
      "responsive video embed calculator"
    ],
    openGraph: {
      title: "Aspect Ratio Calculator – Calculate Image & Video Dimensions",
      description: "Calculate dimensions, visualize ratios, and generate responsive CSS instantly in your browser.",
      type: "website",
      url: "/aspect-ratio-calculator"
    },
    howToSteps: [
      { name: "Enter two of width, height and ratio", text: "Type a width and height to get the simplified ratio, or type a ratio such as 16:9 to get the height for your width. Tick Keep the ratio to resize one side and have the other follow." },
      { name: "Pick a common size", text: "Click a resolution such as 1920 × 1080 or 1080 × 1920, or any size in the chart further down the page, to load it into the calculator." },
      { name: "Check the preview and slider", text: "The preview box shows the proportions, and the slider rescales the size while keeping the ratio." },
      { name: "Convert or detect a ratio", text: "Use the converter tab to fit a resolution into a different ratio, or upload an image to read its dimensions and ratio." },
      { name: "Copy the results", text: "Copy the dimensions or the generated CSS for a responsive container, or export the result." },
    ],
    faq: [
      { q: "What is the most common video aspect ratio?", a: "16:9 is the most common standard for modern video playback across web, streaming, and presentation contexts." },
      { q: "How do I calculate height from width and ratio?", a: "Use Height = (Width x Ratio Height) / Ratio Width. This calculator does it instantly and updates all related outputs." },
      { q: "Can this tool simplify ratios automatically?", a: "Yes. Enter dimensions like 3840 x 2160 and the tool simplifies to 16:9 automatically." },
      { q: "What aspect ratio is 1920 × 1080?", a: "16:9. Divide both numbers by their greatest common divisor, 120, to get 16 and 9. 1280 × 720, 2560 × 1440 and 3840 × 2160 (4K) are 16:9 as well." },
      { q: "Can I use this for responsive web design?", a: "Yes. Use generated CSS to maintain consistent media blocks and reduce layout shift on different screen sizes." },
      { q: "Does image upload help detect unknown ratios?", a: "Yes. Upload any image and the tool reads dimensions and calculated ratio so you can resize accurately." },
      { q: "What size is a 9:16 vertical video?", a: "1080 × 1920 pixels is the usual size for Stories, Reels, TikTok and YouTube Shorts; 720 × 1280 is the smaller HD version. Both are 9:16, the 16:9 landscape frame turned on its side." },
    ],
  },
  features: [
    "Auto-calculate width, height, or ratio",
    "Visual preview box with live updates",
    "Resize simulator (100px - 4000px)",
    "8 preset aspect ratios",
    "Image upload ratio detection",
    "CSS aspect-ratio generator",
    "Legacy padding-top CSS",
    "Responsive container code",
    "Resolution converter",
    "Automatic ratio simplifier",
    "Common resolutions (720p-8K)",
    "Copy dimensions to clipboard",
    "Export as JSON or TXT",
    "Private: your inputs are not collected or stored",
    "Mobile responsive design",
    "Instant calculations"
  ]
};
