export const aspectRatioCalculatorConfig = {
  slug: "aspect-ratio-calculator",
  name: "Aspect Ratio Calculator",
  description: "Calculate image and video dimensions with visual preview and CSS generation",
  category: "design",
  icon: "📐",
  free: true,
  backend: false,
  seo: {
    title: "Aspect Ratio Calculator – Calculate Image & Video Dimensions | Productive Toolbox",
    description: "Free online aspect ratio calculator to calculate width and height, convert resolutions, detect image ratio, simplify proportions, and generate responsive CSS.",
    keywords: [
      "aspect ratio calculator",
      "free aspect ratio calculator",
      "image dimensions calculator",
      "video aspect ratio",
      "16:9 calculator",
      "9:16 calculator",
      "1:1 aspect ratio calculator",
      "aspect ratio converter",
      "resolution calculator",
      "image resize calculator",
      "css aspect ratio",
      "css aspect-ratio generator",
      "responsive image calculator",
      "video dimensions",
      "aspect ratio tool",
      "image proportions",
      "screen ratio calculator",
      "photo aspect ratio",
      "width and height calculator",
      "image ratio detector",
      "social media image size calculator",
      "video size calculator",
      "aspect ratio simplifier",
      "pixel ratio calculator",
      "responsive video embed calculator"
    ],
    openGraph: {
      title: "Aspect Ratio Calculator – Calculate Image & Video Dimensions",
      description: "Calculate dimensions, visualize ratios, and generate responsive CSS instantly in your browser.",
      type: "website",
      url: "/aspect-ratio-calculator"
    }
  },
  features: [
    "Auto-calculate width, height, or ratio",
    "Visual preview box with live updates",
    "Resize simulator (100px - 4000px)",
    "8 preset aspect ratios",
    "Image upload ratio detection",
    "CSS aspect-ratio generator",
    "Legacy padding-top CSS",
    "Responsive container code",
    "Resolution converter",
    "Automatic ratio simplifier",
    "Common resolutions (720p-8K)",
    "Copy dimensions to clipboard",
    "Export as JSON or TXT",
    "100% client-side processing",
    "Mobile responsive design",
    "Instant calculations"
  ]
};
