"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import {
  calculateConversionRate,
  validateInputs,
  formatNumber,
  parseNumber,
  saveHistory,
  getHistory,
  clearHistory,
  debounce,
  buildShareUrl,
  parseShareParams,
  type ConversionResult,
  type HistoryEntry,
} from "./logic";
import ConversionRateCalculatorSEO from "./seo-content";
import RelatedTools from "@/components/RelatedTools";

const PRESETS = [
  { label: "Website", visitors: 5000, conversions: 175 },
  { label: "Landing Page", visitors: 2500, conversions: 325 },
  { label: "Google Ads", visitors: 12800, conversions: 512 },
  { label: "Facebook Ads", visitors: 8000, conversions: 120 },
  { label: "Email Campaign", visitors: 900, conversions: 81 },
  { label: "Ecommerce", visitors: 10000, conversions: 250 },
];

const PERFORMANCE_STYLES: Record<
  ConversionResult["performanceLevel"],
  { bg: string; text: string; border: string; dot: string }
> = {
  exceptional: {
    bg: "bg-purple-50",
    text: "text-purple-700",
    border: "border-purple-200",
    dot: "bg-purple-500",
  },
  excellent: {
    bg: "bg-green-50",
    text: "text-green-700",
    border: "border-green-200",
    dot: "bg-green-500",
  },
  good: {
    bg: "bg-blue-50",
    text: "text-blue-700",
    border: "border-blue-200",
    dot: "bg-blue-500",
  },
  average: {
    bg: "bg-yellow-50",
    text: "text-yellow-700",
    border: "border-yellow-200",
    dot: "bg-yellow-500",
  },
  low: {
    bg: "bg-red-50",
    text: "text-red-700",
    border: "border-red-200",
    dot: "bg-red-400",
  },
};

export default function ConversionRateCalculatorUI() {
  const [visitors, setVisitors] = useState("5000");
  const [conversions, setConversions] = useState("175");
  const [decimalPlaces, setDecimalPlaces] = useState(2);
  const [result, setResult] = useState<ConversionResult | null>(null);
  const [visitorsError, setVisitorsError] = useState<string | null>(null);
  const [conversionsError, setConversionsError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [shareCopied, setShareCopied] = useState(false);
  const [showHistory, setShowHistory] = useState(false);
  const [history, setHistory] = useState<HistoryEntry[]>([]);
  const visitorsRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    setHistory(getHistory());
    const shared = parseShareParams();
    if (shared) {
      setVisitors(shared.visitors);
      setConversions(shared.conversions);
    } else {
      visitorsRef.current?.focus();
    }
  }, []);

  const run = useCallback(
    debounce((v: string, c: string, dp: number) => {
      const { visitorsError: ve, conversionsError: ce } = validateInputs(v, c);
      setVisitorsError(ve);
      setConversionsError(ce);
      if (ve || ce) { setResult(null); return; }
      const vv = parseNumber(v);
      const cv = parseNumber(c);
      if (vv === null || cv === null) { setResult(null); return; }
      setResult(calculateConversionRate(vv, cv, dp));
    }, 120),
    []
  );

  useEffect(() => {
    run(visitors, conversions, decimalPlaces);
  }, [visitors, conversions, decimalPlaces, run]);

  const handlePreset = (p: (typeof PRESETS)[0]) => {
    setVisitors(String(p.visitors));
    setConversions(String(p.conversions));
    visitorsRef.current?.focus();
  };

  const handleReset = () => {
    setVisitors("5000");
    setConversions("175");
    setResult(null);
    setVisitorsError(null);
    setConversionsError(null);
    visitorsRef.current?.focus();
  };

  const handleCopyResult = () => {
    if (!result) return;
    navigator.clipboard.writeText(result.rateFormatted);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleCopyFull = () => {
    if (!result) return;
    const text = [
      `Conversion Rate Calculator Result`,
      `==================================`,
      `Visitors:        ${formatNumber(result.visitors)}`,
      `Conversions:     ${formatNumber(result.conversions)}`,
      `Formula:         ${result.formula}`,
      `Conversion Rate: ${result.rateFormatted}`,
      `Performance:     ${result.performanceLabel}`,
    ].join("\n");
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadTxt = () => {
    if (!result) return;
    const text = [
      `Conversion Rate Calculator Report`,
      `==================================`,
      ``,
      `Visitors:        ${formatNumber(result.visitors)}`,
      `Conversions:     ${formatNumber(result.conversions)}`,
      `Formula:         ${result.formula}`,
      `Conversion Rate: ${result.rateFormatted}`,
      `Performance:     ${result.performanceLabel}`,
      ``,
      `Generated by Productive Toolbox`,
    ].join("\n");
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `conversion_rate_${result.visitors}_${result.conversions}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadCsv = () => {
    if (!result) return;
    const csv = [
      "Visitors,Conversions,Conversion Rate,Performance",
      `${result.visitors},${result.conversions},${result.rateFormatted},${result.performanceLabel}`,
    ].join("\n");
    const blob = new Blob([csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `conversion_rate_${result.visitors}_${result.conversions}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleShare = () => {
    if (!result) return;
    const url = buildShareUrl(result.visitors, result.conversions);
    navigator.clipboard.writeText(url);
    setShareCopied(true);
    setTimeout(() => setShareCopied(false), 2000);
  };

  const handleSave = () => {
    if (!result) return;
    saveHistory({ visitors: result.visitors, conversions: result.conversions, result });
    setHistory(getHistory());
  };

  const handleClearHistory = () => {
    if (confirm("Clear all calculation history?")) {
      clearHistory();
      setHistory([]);
    }
  };

  const loadFromHistory = (entry: HistoryEntry) => {
    setVisitors(String(entry.visitors));
    setConversions(String(entry.conversions));
    setShowHistory(false);
  };

  const perfStyle = result ? PERFORMANCE_STYLES[result.performanceLevel] : null;

  // Progress bar width — cap at 100% visually, use min so very high rates don't overflow
  const progressWidth = result ? Math.min(result.rate, 100) : 0;

  return (
    <>
      <div className="max-w-5xl mx-auto space-y-6">

        {/* Info Banner */}
        <div className="bg-blue-50 border border-blue-100 rounded-xl p-4 flex items-start gap-3">
          <span className="text-xl mt-0.5">📈</span>
          <div>
            <h3 className="text-sm font-semibold text-blue-900" style={{ fontFamily: "var(--font-heading)" }}>
              Conversion Rate Calculator
            </h3>
            <p className="text-sm text-blue-700 mt-0.5" style={{ fontFamily: "var(--font-body)" }}>
              Enter your visitors and conversions to instantly calculate your conversion rate. All calculations run locally in your browser — no data is sent anywhere.
            </p>
          </div>
        </div>

        <div className="grid lg:grid-cols-12 gap-6">

          {/* Left: Controls */}
          <div className="lg:col-span-4 space-y-5">

            {/* Input Panel */}
            <div className="bg-white rounded-xl border border-gray-100 shadow-sm p-5 space-y-4">
              <h3 className="text-sm font-semibold text-gray-800" style={{ fontFamily: "var(--font-heading)" }}>
                Campaign Data
              </h3>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1.5" htmlFor="cr-visitors">
                  Visitors
                </label>
                <input
                  ref={visitorsRef}
                  id="cr-visitors"
                  type="number"
                  min="1"
                  value={visitors}
                  onChange={(e) => setVisitors(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && run(visitors, conversions, decimalPlaces)}
                  className={`w-full px-3 py-2.5 border-2 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent text-sm ${
                    visitorsError ? "border-red-300" : "border-gray-200"
                  }`}
                  placeholder="5000"
                  aria-label="Number of visitors"
                  aria-describedby={visitorsError ? "visitors-error" : undefined}
                  inputMode="numeric"
                />
                {visitorsError && (
                  <p id="visitors-error" className="text-xs text-red-600 mt-1" role="alert">
                    {visitorsError}
                  </p>
                )}
                <p className="text-xs text-gray-400 mt-1">Total sessions, users, or impressions</p>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1.5" htmlFor="cr-conversions">
                  Conversions
                </label>
                <input
                  id="cr-conversions"
                  type="number"
                  min="0"
                  value={conversions}
                  onChange={(e) => setConversions(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && run(visitors, conversions, decimalPlaces)}
                  className={`w-full px-3 py-2.5 border-2 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent text-sm ${
                    conversionsError ? "border-red-300" : "border-gray-200"
                  }`}
                  placeholder="175"
                  aria-label="Number of conversions"
                  aria-describedby={conversionsError ? "conversions-error" : undefined}
                  inputMode="numeric"
                />
                {conversionsError && (
                  <p id="conversions-error" className="text-xs text-red-600 mt-1" role="alert">
                    {conversionsError}
                  </p>
                )}
                <p className="text-xs text-gray-400 mt-1">Purchases, sign-ups, downloads, etc.</p>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1.5" htmlFor="cr-decimal">
                  Decimal Places
                </label>
                <select
                  id="cr-decimal"
                  value={decimalPlaces}
                  onChange={(e) => setDecimalPlaces(Number(e.target.value))}
                  className="w-full px-3 py-2.5 border-2 border-gray-200 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent text-sm bg-white"
                  aria-label="Decimal precision"
                >
                  {[0, 1, 2, 3, 4].map((d) => (
                    <option key={d} value={d}>{d} decimal{d !== 1 ? "s" : ""}</option>
                  ))}
                </select>
              </div>

              <p className="text-xs text-gray-400">
                Press <kbd className="px-1 py-0.5 bg-gray-100 rounded text-xs font-mono">Enter</kbd> to recalculate
              </p>

              <div className="space-y-2 pt-1">
                <button
                  onClick={handleReset}
                  className="w-full px-4 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg text-sm font-medium transition-colors"
                >
                  Reset
                </button>
                <div className="grid grid-cols-2 gap-2">
                  <button
                    onClick={handleDownloadTxt}
                    disabled={!result}
                    className="px-3 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg text-xs font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    Export TXT
                  </button>
                  <button
                    onClick={handleDownloadCsv}
                    disabled={!result}
                    className="px-3 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg text-xs font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    Export CSV
                  </button>
                </div>
                <button
                  onClick={() => setShowHistory(!showHistory)}
                  className="w-full px-4 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg text-sm font-medium transition-colors"
                >
                  {showHistory ? "Hide" : "Show"} History
                </button>
              </div>
            </div>

            {/* Result Summary Card */}
            <div className="bg-primary rounded-xl border border-primary shadow-lg shadow-primary/20 p-5 text-white">
              <p className="text-primary-100 text-xs font-semibold uppercase tracking-wider mb-2" style={{ fontFamily: "var(--font-heading)" }}>
                Result
              </p>
              {result ? (
                <>
                  <div className="text-4xl font-bold font-mono mb-1 tabular-nums">
                    {result.rateFormatted}
                  </div>
                  <div className="text-sm text-primary-100 mb-1 font-mono">
                    {result.formula}
                  </div>
                  {perfStyle && (
                    <div className="flex items-center gap-2 mb-4 mt-2">
                      <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold ${perfStyle.bg} ${perfStyle.text} ${perfStyle.border} border`}>
                        <span className={`w-1.5 h-1.5 rounded-full ${perfStyle.dot}`} />
                        {result.performanceLabel}
                      </span>
                    </div>
                  )}
                  {result.warning && (
                    <p className="text-xs text-yellow-200 bg-yellow-900/30 rounded-lg px-3 py-2 mb-3">
                      ⚠ {result.warning}
                    </p>
                  )}
                  <div className="border-t border-white/20 pt-3 space-y-1 text-sm mb-4">
                    <div className="flex justify-between">
                      <span className="text-primary-100">Visitors</span>
                      <span className="font-semibold font-mono">{formatNumber(result.visitors)}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-primary-100">Conversions</span>
                      <span className="font-semibold font-mono">{formatNumber(result.conversions)}</span>
                    </div>
                  </div>
                  <div className="space-y-2">
                    <button
                      onClick={handleCopyResult}
                      className="w-full bg-white text-primary font-semibold py-2 rounded-lg hover:bg-gray-50 transition-colors text-sm"
                    >
                      {copied ? "✓ Copied!" : "Copy Rate"}
                    </button>
                    <div className="grid grid-cols-2 gap-2">
                      <button
                        onClick={handleCopyFull}
                        className="border border-white/30 text-white font-medium py-2 rounded-lg hover:bg-white/10 transition-colors text-xs"
                      >
                        Copy All
                      </button>
                      <button
                        onClick={handleShare}
                        className="border border-white/30 text-white font-medium py-2 rounded-lg hover:bg-white/10 transition-colors text-xs"
                      >
                        {shareCopied ? "✓ Copied!" : "Share URL"}
                      </button>
                    </div>
                    <button
                      onClick={handleSave}
                      className="w-full border border-white/30 text-white font-medium py-2 rounded-lg hover:bg-white/10 transition-colors text-sm"
                    >
                      Save to History
                    </button>
                  </div>
                </>
              ) : (
                <div className="text-primary-100 text-sm">
                  {visitorsError || conversionsError
                    ? "Fix the errors above to calculate"
                    : "Enter visitors and conversions to calculate"}
                </div>
              )}
            </div>

          </div>

          {/* Right: Results */}
          <div className="lg:col-span-8 space-y-5">

            {/* Quick Presets */}
            <div className="bg-white rounded-xl border border-gray-100 shadow-sm p-5">
              <h3 className="text-sm font-semibold text-gray-800 mb-3" style={{ fontFamily: "var(--font-heading)" }}>
                Quick Examples
              </h3>
              <div className="flex flex-wrap gap-2">
                {PRESETS.map((p) => {
                  const active =
                    visitors === String(p.visitors) && conversions === String(p.conversions);
                  return (
                    <button
                      key={p.label}
                      onClick={() => handlePreset(p)}
                      className={`px-3 py-1.5 rounded-lg text-sm font-medium transition-colors border ${
                        active
                          ? "bg-primary text-white border-primary"
                          : "bg-gray-50 text-gray-700 border-gray-200 hover:bg-gray-100"
                      }`}
                    >
                      {p.label}
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Progress Bar Visualization */}
            {result && (
              <div className="bg-white rounded-xl border border-gray-100 shadow-sm p-5">
                <h3 className="text-sm font-semibold text-gray-800 mb-3" style={{ fontFamily: "var(--font-heading)" }}>
                  Conversion Rate Visualization
                </h3>
                <div className="space-y-2">
                  <div className="flex justify-between text-xs text-gray-500 mb-1">
                    <span>0%</span>
                    <span className="font-semibold text-primary">{result.rateFormatted}</span>
                    <span>10%+</span>
                  </div>
                  <div className="w-full bg-gray-100 rounded-full h-3 overflow-hidden">
                    <div
                      className="h-3 rounded-full bg-primary transition-all duration-500"
                      style={{ width: `${Math.min((progressWidth / 10) * 100, 100)}%` }}
                      role="progressbar"
                      aria-valuenow={result.rate}
                      aria-valuemin={0}
                      aria-valuemax={10}
                    />
                  </div>
                  <p className="text-xs text-gray-400">
                    Bar represents 0–10% range. Rates above 10% are capped at full bar.
                  </p>
                </div>
              </div>
            )}

            {/* Calculation Breakdown */}
            <div className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
              <div className="p-5 border-b border-gray-100 bg-gray-50/50">
                <h3 className="font-semibold text-gray-800 text-sm" style={{ fontFamily: "var(--font-heading)" }}>
                  Calculation Breakdown
                </h3>
              </div>
              {result ? (
                <div className="divide-y divide-gray-50">
                  {[
                    { label: "Visitors", value: formatNumber(result.visitors), mono: true },
                    { label: "Conversions", value: formatNumber(result.conversions), mono: true },
                    { label: "Formula", value: result.formula, mono: true },
                    { label: "Conversion Rate", value: result.rateFormatted, mono: true, highlight: true },
                    { label: "Performance", value: result.performanceLabel, mono: false },
                  ].map(({ label, value, mono, highlight }) => (
                    <div
                      key={label}
                      className="flex items-center justify-between px-5 py-3 hover:bg-gray-50 transition-colors"
                    >
                      <span className="text-sm text-gray-600">{label}</span>
                      <span className={`text-sm font-semibold ${mono ? "font-mono" : ""} ${highlight ? "text-primary text-base" : "text-gray-900"}`}>
                        {value}
                      </span>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="p-8 text-center text-gray-400 text-sm">
                  {visitorsError || conversionsError
                    ? visitorsError || conversionsError
                    : "Enter values above to see the breakdown"}
                </div>
              )}
            </div>

            {/* Performance Guide */}
            <div className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
              <div className="p-5 border-b border-gray-100 bg-gray-50/50">
                <h3 className="font-semibold text-gray-800 text-sm" style={{ fontFamily: "var(--font-heading)" }}>
                  Performance Reference
                </h3>
              </div>
              <div className="divide-y divide-gray-50">
                {[
                  { level: "exceptional" as const, label: "Exceptional", range: "≥ 10.00%", desc: "Top-tier performance" },
                  { level: "excellent" as const, label: "Excellent", range: "5.00% – 9.99%", desc: "Strong results" },
                  { level: "good" as const, label: "Good", range: "3.00% – 4.99%", desc: "Above average" },
                  { level: "average" as const, label: "Average", range: "1.00% – 2.99%", desc: "Typical industry range" },
                  { level: "low" as const, label: "Low", range: "< 1.00%", desc: "Optimization recommended" },
                ].map(({ level, label, range, desc }) => {
                  const s = PERFORMANCE_STYLES[level];
                  const isActive = result?.performanceLevel === level;
                  return (
                    <div
                      key={level}
                      className={`flex items-center justify-between px-5 py-3 transition-colors ${
                        isActive ? "bg-primary/5" : "hover:bg-gray-50"
                      }`}
                    >
                      <div className="flex items-center gap-3">
                        <span className={`inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full text-xs font-semibold ${s.bg} ${s.text} ${s.border} border`}>
                          <span className={`w-1.5 h-1.5 rounded-full ${s.dot}`} />
                          {label}
                        </span>
                        <span className="text-xs text-gray-500">{desc}</span>
                      </div>
                      <span className="text-xs font-mono font-semibold text-gray-700">{range}</span>
                    </div>
                  );
                })}
              </div>
              <p className="text-xs text-gray-400 px-5 py-3 border-t border-gray-50">
                * Benchmarks are general guidelines. Good conversion rate varies by industry, channel, and goal type.
              </p>
            </div>

            {/* History */}
            {showHistory && (
              <div className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
                <div className="p-4 border-b border-gray-100 bg-gray-50/50 flex items-center justify-between">
                  <h3 className="font-semibold text-gray-800 text-sm" style={{ fontFamily: "var(--font-heading)" }}>
                    Calculation History
                  </h3>
                  {history.length > 0 && (
                    <button
                      onClick={handleClearHistory}
                      className="text-xs text-red-600 hover:text-red-700 font-medium"
                    >
                      Clear All
                    </button>
                  )}
                </div>
                <div className="divide-y divide-gray-50 max-h-72 overflow-y-auto">
                  {history.length === 0 ? (
                    <div className="p-6 text-center text-gray-400 text-sm">No saved calculations yet</div>
                  ) : (
                    history.map((entry) => (
                      <div
                        key={entry.id}
                        onClick={() => loadFromHistory(entry)}
                        className="p-4 hover:bg-gray-50 cursor-pointer transition-colors"
                      >
                        <div className="flex items-center justify-between mb-1">
                          <span className="font-mono text-sm font-semibold text-gray-900">
                            {formatNumber(entry.visitors)} visitors / {formatNumber(entry.conversions)} conv.
                          </span>
                          <span className="text-xs text-gray-400">
                            {new Date(entry.timestamp).toLocaleString("en-US")}
                          </span>
                        </div>
                        <div className="text-xs text-primary font-mono font-semibold">
                          Rate: {entry.result.rateFormatted} · {entry.result.performanceLabel}
                        </div>
                      </div>
                    ))
                  )}
                </div>
              </div>
            )}

          </div>
        </div>
      </div>

      <ConversionRateCalculatorSEO />

      <RelatedTools
        currentTool="conversion-rate-calculator"
        tools={[
          "ctr-calculator",
          "percentage-calculator",
          "discount-calculator",
          "investment-return-calculator",
          "simple-interest-calculator",
          "gst-vat-calculator",
        ]}
      />
    </>
  );
}
