export const textDiffCheckerConfig = {
  name: "Text Diff Checker",
  slug: "text-diff-checker",
  description: "Compare two text blocks and highlight differences with advanced options",
  category: "text",
  icon: "🔀",
  keywords: [
    "text diff checker",
    "compare text",
    "text comparison",
    "diff tool",
    "text differences",
    "compare documents",
    "text analyzer",
    "diff viewer",
    "text compare online",
    "file comparison",
    "text diff",
    "compare files",
    "text difference",
    "side by side comparison",
    "text merger",
    "diff highlight",
    "text tool",
    "frontend diff tool"
  ],
  seo: {
    title: "Text Diff Checker – Compare Two Texts Online",
    description: "Compare two texts and highlight what changed by line, word or character, side by side or inline, with options to ignore case and whitespace.",
    keywords: [
      "text diff checker",
      "compare text",
      "text comparison",
      "diff tool",
      "text differences",
      "compare documents",
      "text analyzer",
      "diff viewer",
      "text compare online",
      "file comparison",
      "text diff",
      "compare files",
      "text difference",
      "side by side comparison",
      "text merger",
      "diff highlight",
      "text tool",
      "frontend diff tool",
      "text difference checker",
      "compare two texts online",
      "line by line diff tool",
      "word diff checker",
      "character diff checker",
      "side by side text compare",
      "inline diff viewer",
      "document difference checker",
      "text revision comparison tool"
    ],
    openGraph: {
      title: "Text Diff Checker - Compare and Export Text Differences",
      description: "Detect additions and removals with multi-level comparison, visual views, and export-ready output.",
      type: "website",
      url: "/tools/writing/text-diff-checker"
    }
  }
};
