import { siteConfig } from "@/config/site";

export const fileSizeConverterConfig = {
  slug: "file-size-converter",
  name: "File Size Converter",
  description: "Convert file sizes instantly between Bytes, KB, MB, GB, TB, and PB using binary (1024) or decimal (1000) standards.",
  category: "computer-science",
  icon: "💾",
  free: true,
  seo: {
    howToSteps: [
      { name: "Enter a size", text: "Type any number into File size; decimals and very large values work." },
      { name: "Pick the unit", text: "Choose bytes, KB, MB, GB, TB or PB, or click a preset such as 100 MB or 1 TB." },
      { name: "Choose binary or decimal", text: "Binary (1,024) matches Windows and RAM; decimal (1,000) matches drive labels, macOS and network speeds." },
      { name: "Read every unit at once", text: "The results table lists the size in all six units, with the exact byte count." },
      { name: "See how it shows up and how long it takes", text: "Compare how Windows and macOS display the size, and set your connection speed in Mbps to see the download or upload time." },
      { name: "Copy or export", text: "Copy a single value or the share-ready line, or download the full result as text or CSV." },
    ],
    faq: [
      { q: "Why does my 1 TB drive show 931 GB on Windows?", a: "Drive makers count in decimal: 1 TB = 1,000,000,000,000 bytes. Windows divides by 1,024 three times but still writes GB, so it shows 1,000,000,000,000 ÷ 1,073,741,824 ≈ 931 GB. Nothing is missing; it is the same number of bytes in a different unit." },
      { q: "Why does the same file look bigger on a Mac than on Windows?", a: "Since macOS 10.6, Finder counts 1 KB as 1,000 bytes, while Windows Explorer counts 1 KB as 1,024 bytes. A file of 1,500,000,000 bytes shows as 1.5 GB on a Mac and about 1.4 GB on Windows." },
      { q: "What is the difference between MB and MiB?", a: "An MB (megabyte) is 1,000,000 bytes. A MiB (mebibyte) is 1,048,576 bytes, or 1,024 × 1,024. The IEC binary prefixes KiB, MiB and GiB were introduced to tell the two apart, but in everyday use \"MB\" can mean either." },
      { q: "Which standard should I use?", a: "Use binary (1,024) to match what Windows shows, for RAM, and for most programming. Use decimal (1,000) for drive and SSD capacities, cloud storage plans, macOS and iOS, and anything tied to network speed." },
      { q: "How long does it take to download a file?", a: "Multiply the size in bytes by 8 to get bits, then divide by your speed in bits per second. A 5 GB (decimal) file on a 100 Mbps connection takes 5,000,000,000 × 8 ÷ 100,000,000 = 400 seconds, about 6 minutes 40 seconds, at full speed. Real downloads are slower because of protocol overhead and shared connections." },
      { q: "What is the difference between Mbps and MB/s?", a: "Mbps is megabits per second, the unit internet providers use. MB/s is megabytes per second, which download managers often show. One byte is 8 bits, so 100 Mbps is at most 12.5 MB/s." },
      { q: "Is my data sent anywhere?", a: "No. We do not collect or store what you enter. Any history the tool keeps is visible only to you." },
    ],
    title: "File Size Converter – Bytes, KB, MB, GB, TB",
    description: "Convert bytes, KB, MB, GB, TB and PB in binary (1024) or decimal (1000), see how Windows and macOS show a size, and how long it takes to download.",
    keywords: [
      "file size converter",
      "KB to MB converter",
      "MB to GB converter",
      "GB to TB converter",
      "storage unit converter",
      "byte converter",
      "convert file size online",
      "binary vs decimal file size",
      "KiB MiB GiB converter",
      "digital storage converter",
      "file size calculator",
      "data size converter",
    ],
    openGraph: {
      title: "Free File Size Converter – Convert KB, MB, GB, TB Online",
      description: "Convert bytes, KB, MB, GB, TB and PB in binary (1024) or decimal (1000), see how Windows and macOS show a size, and how long it takes to download.",
      type: "website",
      url: `${siteConfig.url}/tools/computer-science/file-size-converter`,
    },
  },
};
