import { siteConfig } from "@/config/site";

export const airConditionerPowerCalculatorConfig = {
  name: "Air Conditioner Power Calculator",
  slug: "air-conditioner-power-calculator",
  description: "Calculate AC power consumption in watts, monthly electricity cost, and required generator size from tonnage and EER/SEER rating.",
  category: "electrical",
  icon: "❄️",
  free: true,
  backend: false,
  seo: {
    title: "Air Conditioner Power Calculator — AC Wattage & Cost | Productive Toolbox",
    description: "Calculate AC power consumption in watts, monthly electricity cost, and generator size from tonnage and EER. Free AC power calculator, browser-based, no signup.",
    keywords: [
      "air conditioner power calculator",
      "ac power consumption calculator",
      "ac wattage calculator",
      "1 ton ac power consumption",
      "1.5 ton ac wattage",
      "air conditioner electricity cost calculator",
      "ac running cost calculator",
      "generator size for ac",
      "kva for air conditioner",
      "how many watts does ac use",
      "1.5 ton ac power consumption watts",
      "air conditioner energy consumption calculator",
      "ac monthly electricity cost",
      "eer calculator ac",
      "seer to watts calculator",
      "ac power calculator online",
      "air conditioner kw calculator",
      "btu to watts calculator",
      "tons to watts calculator",
      "ac circuit breaker size calculator",
      "inverter ac power consumption",
      "ac electricity bill calculator",
      "air conditioner running cost",
      "1 ton ac cost per month",
      "ac power calculator free",
    ],
    openGraph: {
      title: "Air Conditioner Power Calculator — AC Wattage & Cost Calculator",
      description: "Calculate AC power consumption in watts, monthly electricity cost, and generator size from tonnage and EER/SEER. Free, browser-based.",
      type: "website",
      url: `${siteConfig.url}/tools/electrical/air-conditioner-power-calculator`,
    },
    og: {
      title: "Air Conditioner Power Calculator — AC Wattage & Cost Calculator",
      description: "Calculate AC power consumption in watts, monthly electricity cost, and generator size from tonnage and EER/SEER. Free, browser-based.",
      url: `${siteConfig.url}/tools/electrical/air-conditioner-power-calculator`,
    },
    howToSteps: [
      { name: "Enter AC Capacity", text: "Input your AC capacity in tons (e.g. 1.5) or BTU/h (e.g. 18000). Select whichever matches your unit's nameplate or spec sheet." },
      { name: "Enter EER or SEER Rating", text: "Type the EER or SEER from the product label. Typical range: 8–10 for older units, 12–14 for modern units, 16–22 for premium inverter ACs. Use 10 if unknown." },
      { name: "Set Daily Hours and Days per Month", text: "Enter how many hours per day the AC runs and how many days per month (typically 30). This drives monthly energy and cost calculations." },
      { name: "Enter Your Electricity Rate", text: "Type your local electricity cost per kWh from your bill. Common ranges: $0.10–0.15/kWh in the US, ₹5–8 in India, ৳7–10 in Bangladesh." },
      { name: "Read All Results", text: "The calculator returns running wattage, monthly kWh, monthly cost, annual cost, required circuit breaker size, and recommended generator/inverter kVA — all updated instantly." },
    ],
    faq: [
      { q: "How many watts does a 1 ton AC use?", a: "A 1 ton AC (12,000 BTU/h) consumes 12,000 ÷ EER watts. At EER 10: 1,200W. At EER 12: 1,000W. At EER 8 (older unit): 1,500W." },
      { q: "How many watts does a 1.5 ton AC use?", a: "A 1.5 ton AC (18,000 BTU/h) consumes 18,000 ÷ EER watts. At EER 10: 1,800W. At EER 12: 1,500W. At EER 14: 1,286W." },
      { q: "What size generator is required for a 1.5 ton AC?", a: "A 1.5 ton AC at 1,800W running load requires a generator rated at least 3 kVA to handle startup surge (2.5× running = 4,500W peak). A 5 kVA unit is recommended if running other loads simultaneously." },
      { q: "How do I calculate monthly electricity cost for an AC?", a: "Monthly cost = (Watts ÷ 1000) × hours/day × days/month × rate/kWh. Example: 1,800W × 8h × 30 days × $0.12 = $51.84/month." },
      { q: "What is the difference between EER and SEER?", a: "EER is measured at one standard peak-condition test point. SEER is the seasonal average across varying temperatures — always higher than EER for the same unit. For generator and circuit sizing, use EER. For annual cost estimation, use SEER. Convert: EER ≈ SEER × 0.875." },
      { q: "How many tons of AC do I need?", a: "Approximately 20 BTU/h per square foot under standard conditions. A 400 sq ft room needs ~8,000 BTU/h (0.67 ton, round up to 1 ton). High ceilings or west-facing windows add 20–30% to the estimate." },
      { q: "What is the power consumption of a 2 ton AC?", a: "A 2 ton AC (24,000 BTU/h) at EER 10 consumes 2,400W. At EER 12: 2,000W. Monthly cost at 8h/day, $0.12/kWh: EER 10 = $69.12; EER 12 = $57.60." },
      { q: "What is BTU and how does it relate to tons?", a: "1 ton = 12,000 BTU/h. Common conversions: 0.75 ton = 9,000 BTU/h; 1.5 ton = 18,000 BTU/h; 2 ton = 24,000 BTU/h; 2.5 ton = 30,000 BTU/h; 3 ton = 36,000 BTU/h." },
      { q: "How do I size a circuit breaker for an AC?", a: "Divide running watts by supply voltage to get running amps, then multiply by 1.25 (NEC continuous load factor). A 1.5 ton AC at 1,800W on 240V: 1,800 ÷ 240 = 7.5A × 1.25 = 9.4A — a 15A breaker is correct." },
      { q: "Is my data private when using this calculator?", a: "Yes. All calculations run in your browser. Your AC specs, operating hours, and electricity rates are never sent to any server or stored outside your device." },
    ],
  },
  features: [
    "Running wattage from tons and EER/SEER",
    "Monthly kWh and electricity cost",
    "Annual energy cost",
    "Generator/inverter kVA recommendation",
    "Circuit breaker size",
    "Tons ↔ BTU/h ↔ kW conversion",
    "Room sizing mode",
    "Inverter vs non-inverter comparison",
    "Multi-currency support",
    "No signup required",
  ],
  relatedTools: [
    "ups-load-calculator",
    "generator-size-calculator",
    "electric-motor-power-calculator",
    "solar-panel-calculator",
    "electric-bill-calculator",
    "wire-size-calculator",
  ],
};
