export const tableToMarkdownConfig = {
  name: "Table to Markdown",
  slug: "table-to-markdown",
  description: "Convert spreadsheet tables from Excel, Google Sheets, CSV to Markdown format",
  category: "text",
  icon: "📊",
  keywords: [
    "table to markdown",
    "markdown table",
    "csv to markdown",
    "excel to markdown",
    "spreadsheet converter",
    "markdown converter",
    "table converter",
    "markdown generator",
    "csv converter",
    "tsv to markdown",
    "google sheets markdown",
    "markdown table generator",
    "table formatter",
    "markdown tool",
    "spreadsheet to markdown",
    "data converter",
    "frontend converter",
    "markdown syntax"
  ],
  seo: {
    title: "Table to Markdown Converter – CSV, TSV & Spreadsheets",
    description: "Paste a table from a spreadsheet, CSV or TSV and get a Markdown table, with delimiter detection, column alignment and escaping. Copy or download it.",
    keywords: [
      "table to markdown",
      "markdown table",
      "csv to markdown",
      "excel to markdown",
      "spreadsheet converter",
      "markdown converter",
      "table converter",
      "markdown generator",
      "csv converter",
      "tsv to markdown",
      "google sheets markdown",
      "markdown table generator",
      "table formatter",
      "markdown tool",
      "spreadsheet to markdown",
      "data converter",
      "frontend converter",
      "markdown syntax",
      "convert table to markdown online",
      "markdown table alignment",
      "csv table to markdown",
      "tab separated to markdown",
      "pipe table to markdown",
      "markdown table formatter",
      "markdown table with headers",
      "github markdown table generator",
      "documentation table converter"
    ],
    openGraph: {
      title: "Table to Markdown Converter – CSV, TSV & Spreadsheets",
      description: "Paste a table from a spreadsheet, CSV or TSV and get a Markdown table, with delimiter detection, column alignment and escaping. Copy or download it.",
      type: "website",
      url: "/tools/writing/table-to-markdown"
    }
  }
};
