export const tableToMarkdownConfig = {
  name: "Table to Markdown",
  slug: "table-to-markdown",
  description: "Convert spreadsheet tables from Excel, Google Sheets, CSV to Markdown format",
  category: "text",
  icon: "📊",
  keywords: [
    "table to markdown",
    "markdown table",
    "csv to markdown",
    "excel to markdown",
    "spreadsheet converter",
    "markdown converter",
    "table converter",
    "markdown generator",
    "csv converter",
    "tsv to markdown",
    "google sheets markdown",
    "markdown table generator",
    "table formatter",
    "markdown tool",
    "spreadsheet to markdown",
    "data converter",
    "frontend converter",
    "markdown syntax"
  ],
  seo: {
    title: "Table to Markdown Converter Online - Convert CSV, TSV, and Sheets Data Fast",
    description: "Free Table to Markdown converter with delimiter auto-detect, custom headers, column alignment, escape options, and live preview. Copy or download clean .md output.",
    keywords: [
      "table to markdown",
      "markdown table",
      "csv to markdown",
      "excel to markdown",
      "spreadsheet converter",
      "markdown converter",
      "table converter",
      "markdown generator",
      "csv converter",
      "tsv to markdown",
      "google sheets markdown",
      "markdown table generator",
      "table formatter",
      "markdown tool",
      "spreadsheet to markdown",
      "data converter",
      "frontend converter",
      "markdown syntax",
      "convert table to markdown online",
      "markdown table alignment",
      "csv table to markdown",
      "tab separated to markdown",
      "pipe table to markdown",
      "markdown table formatter",
      "markdown table with headers",
      "github markdown table generator",
      "documentation table converter"
    ],
    openGraph: {
      title: "Table to Markdown Converter - Structured Markdown Tables from Spreadsheet Data",
      description: "Convert spreadsheet and delimited data into markdown tables with alignment, formatting, and preview controls.",
      type: "website",
      url: "/tools/writing/table-to-markdown"
    }
  }
};
