export const momentOfInertiaCalculatorConfig = {
  name: "Moment of Inertia Calculator",
  slug: "moment-of-inertia-calculator",
  description: "Calculate area moment of inertia (Ix, Iy, polar moment) for rectangles, circles, hollow sections, I-beams, T-beams, and more. Instant engineering-grade results.",
  category: "mechanical",
  icon: "📐",
  free: true,
  seo: {
    title: "Moment of Inertia Calculator – Area Moment of Inertia for Engineering",
    description: "Calculate area moment of inertia instantly for rectangles, circles, hollow sections, beams, and structural shapes. Free engineering calculator with formulas and diagrams.",
    keywords: [
      "moment of inertia calculator",
      "area moment of inertia calculator",
      "second moment of area calculator",
      "beam inertia calculator",
      "shaft moment of inertia",
      "engineering calculator",
      "structural engineering tools",
      "Ix Iy calculator",
      "polar moment of inertia",
      "section modulus calculator",
      "I-beam moment of inertia",
      "hollow circle moment of inertia",
      "rectangle moment of inertia",
    ],
    og: {
      title: "Moment of Inertia Calculator – Area Moment of Inertia for Engineering",
      description: "Calculate area moment of inertia instantly for rectangles, circles, hollow sections, beams, and structural shapes. Free engineering calculator with formulas and diagrams.",
      url: "https://www.productivtb.com/tools/mechanical/moment-of-inertia-calculator",
    },
  },
  relatedTools: [
    "beam-deflection-calculator",
    "stress-calculator",
    "torque-calculator",
    "bending-stress-calculator",
    "section-modulus-calculator",
    "shear-stress-calculator",
  ],
};
