import { siteConfig } from "@/config/site";

export const costPerClickCpcCalculatorConfig = {
  slug: "cost-per-click-cpc-calculator",
  name: "Cost Per Click (CPC) Calculator",
  description: "Calculate Cost Per Click (CPC) instantly from advertising cost and total clicks. Free online CPC calculator for Google Ads, Facebook Ads, PPC campaigns, and digital marketing.",
  category: "marketing",
  icon: "💵",
  free: true,
  seo: {
    title: "Free Cost Per Click (CPC) Calculator Online | Calculate Average CPC Instantly",
    description: "Calculate Cost Per Click (CPC) instantly using our free online CPC Calculator. Enter your advertising cost and total clicks to get accurate PPC metrics in real time. Fast, mobile-friendly, and 100% browser-based.",
    keywords: [
      "cost per click calculator",
      "CPC calculator",
      "average CPC calculator",
      "Google Ads CPC calculator",
      "PPC calculator",
      "advertising cost calculator",
      "digital marketing calculator",
      "marketing calculator",
      "calculate cost per click",
      "free CPC tool",
      "online CPC calculator",
      "Facebook Ads CPC",
      "ad spend calculator",
    ],
    openGraph: {
      title: "Free CPC Calculator – Calculate Cost Per Click Instantly",
      description: "Quickly calculate your advertising Cost Per Click (CPC) using this free online calculator. Works instantly with no signup required.",
      type: "website",
      url: `${siteConfig.url}/tools/marketing/cost-per-click-cpc-calculator`,
    },
    howToSteps: [
      { name: "Enter Total Advertising Cost", text: "Type the total amount billed by your ad platform for the campaign period — the gross spend figure from your Google Ads, Facebook Ads, or other platform billing summary." },
      { name: "Enter Total Clicks", text: "Type the total number of clicks your ads received during the same period. Make sure the date range matches your cost figure exactly." },
      { name: "Select Your Currency", text: "Choose from 9 supported currencies. Currency is applied to display formatting only — no conversion is performed." },
      { name: "Use Industry Presets (Optional)", text: "Click any preset button to instantly load a real-world example for ecommerce, SaaS, legal, or other industries." },
      { name: "Read the Performance Badge", text: "Your CPC result appears instantly alongside a performance badge — Very Low, Low, Average, High, or Very High — with a plain-language interpretation." },
      { name: "Export or Share", text: "Copy the result to clipboard, export as CSV or TXT, or use the shareable URL to send the calculation with all inputs pre-filled." },
    ],
    faq: [
      { q: "What is Cost Per Click (CPC)?", a: "Cost Per Click (CPC) is the amount an advertiser pays each time a user clicks on their ad. It is the standard pricing model for paid search on Google Ads, Microsoft Ads, and is also used on Meta, LinkedIn, TikTok, and Pinterest. CPC tells you the cost of acquiring one website visitor through paid traffic." },
      { q: "How is CPC calculated?", a: "CPC is calculated by dividing total advertising cost by the total number of clicks received during the same period. For example, if you spent $800 and received 400 clicks, your average CPC is $800 ÷ 400 = $2.00." },
      { q: "What is a good CPC?", a: "A good CPC is relative to the value of a conversion. Calculate your Maximum Viable CPC: multiply your average order value by your conversion rate. For example, $90 AOV × 3% CVR = $2.70 max CPC. Any CPC below that is profitable on average." },
      { q: "What is the difference between CPC and CPM?", a: "CPC charges advertisers only when a user clicks the ad. CPM charges per 1,000 impressions regardless of clicks. CPC is better for direct-response campaigns; CPM is better for brand awareness where reach matters more than clicks." },
      { q: "What is maximum CPC vs average CPC?", a: "Maximum CPC is the ceiling you set — the most you are willing to pay per click. Average CPC is what you actually paid on average, which is almost always lower than your max bid due to auction dynamics and quality scores." },
      { q: "How can I lower my CPC on Google Ads?", a: "Improve Quality Score by increasing ad relevance, landing page experience, and expected CTR. Use exact and phrase match keywords, add negative keywords, and improve ad copy. Higher Quality Score lowers actual CPC at the same bid." },
      { q: "What is the relationship between CPC and Quality Score?", a: "Quality Score (1–10) directly affects your Ad Rank and actual CPC paid. Improving Quality Score from 5 to 8 on a competitive keyword can reduce actual CPC by 30–50% without changing your max bid." },
      { q: "Why does Google Analytics show fewer sessions than Google Ads clicks?", a: "A discrepancy of 10–30% between Google Ads clicks and Analytics sessions is normal. Causes include users hitting back before the tag fires, bot filtering, JavaScript disabled, redirect timing, and ad blockers. Use platform click count for CPC calculation." },
      { q: "How is CPC different on search vs display vs social?", a: "Search CPC is driven by keyword auction competition and high purchase intent. Display CPC is generally lower as ads appear on third-party sites with lower intent. Social CPC uses demographic targeting with CPCs varying widely by platform and audience quality." },
      { q: "Is my data private when using this calculator?", a: "Yes. All calculations run entirely in your browser. Your advertising cost figures and click counts are never transmitted to any server, stored in any database, or accessible to anyone other than you." },
    ],
  },
};
