"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import {
  calculateCPC, validateInputs, formatCurrency, formatNumber, parseNumber,
  saveHistory, getHistory, clearHistory, debounce, buildShareUrl, parseShareParams,
  CURRENCIES, type CPCResult, type HistoryEntry,
} from "./logic";
import CPCCalculatorSEO from "./seo-content";
import RelatedTools from "@/components/RelatedTools";

const PRESETS = [
  { label: "Google Ads",    cost: 500,   clicks: 250  },
  { label: "Facebook Ads",  cost: 1250,  clicks: 5000 },
  { label: "LinkedIn Ads",  cost: 850,   clicks: 170  },
  { label: "Display Ads",   cost: 200,   clicks: 1000 },
  { label: "High-Value",    cost: 3000,  clicks: 600  },
];

const PERF_STYLES: Record<CPCResult["performanceLevel"], { bg: string; text: string; border: string; dot: string }> = {
  "very-low":  { bg: "bg-green-50",  text: "text-green-700",  border: "border-green-200",  dot: "bg-green-500"  },
  "low":       { bg: "bg-blue-50",   text: "text-blue-700",   border: "border-blue-200",   dot: "bg-blue-500"   },
  "average":   { bg: "bg-yellow-50", text: "text-yellow-700", border: "border-yellow-200", dot: "bg-yellow-500" },
  "high":      { bg: "bg-orange-50", text: "text-orange-700", border: "border-orange-200", dot: "bg-orange-400" },
  "very-high": { bg: "bg-red-50",    text: "text-red-700",    border: "border-red-200",    dot: "bg-red-500"    },
};

export default function CPCCalculatorUI() {
  const [cost, setCost]             = useState("500");
  const [clicks, setClicks]         = useState("250");
  const [currency, setCurrency]     = useState("USD");
  const [decimalPlaces, setDecimal] = useState(2);
  const [result, setResult]         = useState<CPCResult | null>(null);
  const [costError, setCostError]   = useState<string | null>(null);
  const [clicksError, setClicksError] = useState<string | null>(null);
  const [copied, setCopied]         = useState(false);
  const [shareCopied, setShareCopied] = useState(false);
  const [showHistory, setShowHistory] = useState(false);
  const [history, setHistory]       = useState<HistoryEntry[]>([]);
  const costRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    setHistory(getHistory());
    const shared = parseShareParams();
    if (shared) { setCost(shared.cost); setClicks(shared.clicks); setCurrency(shared.currency); }
    else costRef.current?.focus();
  }, []);

  const run = useCallback(
    debounce((c: string, cl: string, cur: string, dp: number) => {
      const { costError: ce, clicksError: cle } = validateInputs(c, cl);
      setCostError(ce); setClicksError(cle);
      if (ce || cle) { setResult(null); return; }
      const cv = parseNumber(c); const clv = parseNumber(cl);
      if (cv === null || clv === null) { setResult(null); return; }
      setResult(calculateCPC(cv, clv, cur, dp));
    }, 120), []
  );

  useEffect(() => { run(cost, clicks, currency, decimalPlaces); }, [cost, clicks, currency, decimalPlaces, run]);

  const handlePreset = (p: typeof PRESETS[0]) => { setCost(String(p.cost)); setClicks(String(p.clicks)); costRef.current?.focus(); };
  const handleReset  = () => { setCost("500"); setClicks("250"); setResult(null); setCostError(null); setClicksError(null); costRef.current?.focus(); };

  const handleCopyResult = () => { if (!result) return; navigator.clipboard.writeText(result.cpcFormatted); setCopied(true); setTimeout(() => setCopied(false), 2000); };

  const handleCopyFull = () => {
    if (!result) return;
    const text = [`CPC Calculator Report`, `===================`, `Ad Spend: ${formatCurrency(result.cost, result.currency)}`, `Clicks:   ${formatNumber(result.clicks)}`, `CPC:      ${result.cpcFormatted}`, `Assessment: ${result.performanceLabel}`].join("\n");
    navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadTxt = () => {
    if (!result) return;
    const text = [`Cost Per Click (CPC) Report`, `===========================`, ``, `Ad Spend:   ${formatCurrency(result.cost, result.currency)}`, `Clicks:     ${formatNumber(result.clicks)}`, `Formula:    ${result.formula}`, `CPC:        ${result.cpcFormatted}`, `Assessment: ${result.performanceLabel}`, ``, result.interpretation, ``, `Generated by Productive Toolbox`].join("\n");
    const blob = new Blob([text], { type: "text/plain" });
    const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = `cpc_${result.cost}_${result.clicks}.txt`; a.click(); URL.revokeObjectURL(a.href);
  };

  const handleDownloadCsv = () => {
    if (!result) return;
    const csv = [`Ad Spend,Clicks,CPC,Assessment`, `${result.cost},${result.clicks},${result.cpcFormatted},${result.performanceLabel}`].join("\n");
    const blob = new Blob([csv], { type: "text/csv" });
    const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = `cpc_${result.cost}_${result.clicks}.csv`; a.click(); URL.revokeObjectURL(a.href);
  };

  const handleShare = () => {
    if (!result) return;
    navigator.clipboard.writeText(buildShareUrl(result.cost, result.clicks, result.currency));
    setShareCopied(true); setTimeout(() => setShareCopied(false), 2000);
  };

  const handleSave = () => {
    if (!result) return;
    saveHistory({ cost: result.cost, clicks: result.clicks, currency: result.currency, result });
    setHistory(getHistory());
  };

  const perfStyle = result ? PERF_STYLES[result.performanceLevel] : null;
  const sym = CURRENCIES[currency]?.symbol ?? "$";

  return (
    <>
      <div className="max-w-5xl mx-auto space-y-6">
        {/* Info Banner */}
        <div className="bg-blue-50 border border-blue-100 rounded-xl p-4 flex items-start gap-3">
          <span className="text-xl mt-0.5">💵</span>
          <div>
            <h3 className="text-sm font-semibold text-blue-900" style={{ fontFamily: "var(--font-heading)" }}>Cost Per Click (CPC) Calculator</h3>
            <p className="text-sm text-blue-700 mt-0.5" style={{ fontFamily: "var(--font-body)" }}>
              Enter your ad spend and total clicks to instantly calculate your CPC. All calculations run locally in your browser.
            </p>
          </div>
        </div>

        <div className="grid lg:grid-cols-12 gap-6">
          {/* Left */}
          <div className="lg:col-span-4 space-y-5">
            <div className="bg-white rounded-xl border border-gray-100 shadow-sm p-5 space-y-4">
              <h3 className="text-sm font-semibold text-gray-800" style={{ fontFamily: "var(--font-heading)" }}>Campaign Data</h3>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1.5" htmlFor="cpc-cost">Ad Spend ({sym})</label>
                <input ref={costRef} id="cpc-cost" type="number" min="0" value={cost}
                  onChange={(e) => setCost(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && run(cost, clicks, currency, decimalPlaces)}
                  className={`w-full px-3 py-2.5 border-2 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent text-sm ${costError ? "border-red-300" : "border-gray-200"}`}
                  placeholder="500" aria-label="Total advertising cost" inputMode="decimal" />
                {costError && <p className="text-xs text-red-600 mt-1" role="alert">{costError}</p>}
                <p className="text-xs text-gray-400 mt-1">Total amount spent on advertising</p>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1.5" htmlFor="cpc-clicks">Total Clicks</label>
                <input id="cpc-clicks" type="number" min="1" value={clicks}
                  onChange={(e) => setClicks(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && run(cost, clicks, currency, decimalPlaces)}
                  className={`w-full px-3 py-2.5 border-2 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent text-sm ${clicksError ? "border-red-300" : "border-gray-200"}`}
                  placeholder="250" aria-label="Total clicks" inputMode="numeric" />
                {clicksError && <p className="text-xs text-red-600 mt-1" role="alert">{clicksError}</p>}
                <p className="text-xs text-gray-400 mt-1">Total number of ad clicks received</p>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1.5" htmlFor="cpc-currency">Currency</label>
                <select id="cpc-currency" value={currency} onChange={(e) => setCurrency(e.target.value)}
                  className="w-full px-3 py-2.5 border-2 border-gray-200 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent text-sm bg-white">
                  {Object.entries(CURRENCIES).map(([code, { label }]) => <option key={code} value={code}>{label}</option>)}
                </select>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1.5" htmlFor="cpc-decimal">Decimal Places</label>
                <select id="cpc-decimal" value={decimalPlaces} onChange={(e) => setDecimal(Number(e.target.value))}
                  className="w-full px-3 py-2.5 border-2 border-gray-200 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent text-sm bg-white">
                  {[0,1,2,3,4].map((d) => <option key={d} value={d}>{d} decimal{d !== 1 ? "s" : ""}</option>)}
                </select>
              </div>

              <p className="text-xs text-gray-400">Press <kbd className="px-1 py-0.5 bg-gray-100 rounded text-xs font-mono">Enter</kbd> to recalculate</p>

              <div className="space-y-2 pt-1">
                <button onClick={handleReset} className="w-full px-4 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg text-sm font-medium transition-colors">Reset</button>
                <div className="grid grid-cols-2 gap-2">
                  <button onClick={handleDownloadTxt} disabled={!result} className="px-3 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg text-xs font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed">Export TXT</button>
                  <button onClick={handleDownloadCsv} disabled={!result} className="px-3 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg text-xs font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed">Export CSV</button>
                </div>
                <button onClick={() => setShowHistory(!showHistory)} className="w-full px-4 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg text-sm font-medium transition-colors">
                  {showHistory ? "Hide" : "Show"} History
                </button>
              </div>
            </div>

            {/* Result Card */}
            <div className="bg-primary rounded-xl border border-primary shadow-lg shadow-primary/20 p-5 text-white">
              <p className="text-primary-100 text-xs font-semibold uppercase tracking-wider mb-2" style={{ fontFamily: "var(--font-heading)" }}>Result</p>
              {result ? (
                <>
                  <div className="text-4xl font-bold font-mono mb-1 tabular-nums">{result.cpcFormatted}</div>
                  <div className="text-sm text-primary-100 mb-1">per click</div>
                  {perfStyle && (
                    <div className="flex items-center gap-2 mb-3 mt-2">
                      <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold ${perfStyle.bg} ${perfStyle.text} ${perfStyle.border} border`}>
                        <span className={`w-1.5 h-1.5 rounded-full ${perfStyle.dot}`} />{result.performanceLabel}
                      </span>
                    </div>
                  )}
                  <div className="border-t border-white/20 pt-3 space-y-1 text-sm mb-4">
                    <div className="flex justify-between">
                      <span className="text-primary-100">Ad Spend</span>
                      <span className="font-semibold font-mono">{formatCurrency(result.cost, result.currency)}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-primary-100">Clicks</span>
                      <span className="font-semibold font-mono">{formatNumber(result.clicks)}</span>
                    </div>
                  </div>
                  <div className="space-y-2">
                    <button onClick={handleCopyResult} className="w-full bg-white text-primary font-semibold py-2 rounded-lg hover:bg-gray-50 transition-colors text-sm">
                      {copied ? "✓ Copied!" : "Copy CPC"}
                    </button>
                    <div className="grid grid-cols-2 gap-2">
                      <button onClick={handleCopyFull} className="border border-white/30 text-white font-medium py-2 rounded-lg hover:bg-white/10 transition-colors text-xs">Copy All</button>
                      <button onClick={handleShare} className="border border-white/30 text-white font-medium py-2 rounded-lg hover:bg-white/10 transition-colors text-xs">{shareCopied ? "✓ Copied!" : "Share URL"}</button>
                    </div>
                    <button onClick={handleSave} className="w-full border border-white/30 text-white font-medium py-2 rounded-lg hover:bg-white/10 transition-colors text-sm">Save to History</button>
                  </div>
                </>
              ) : (
                <div className="text-primary-100 text-sm">
                  {costError || clicksError ? "Fix the errors above to calculate" : "Enter ad spend and clicks to calculate"}
                </div>
              )}
            </div>
          </div>

          {/* Right */}
          <div className="lg:col-span-8 space-y-5">
            {/* Presets */}
            <div className="bg-white rounded-xl border border-gray-100 shadow-sm p-5">
              <h3 className="text-sm font-semibold text-gray-800 mb-3" style={{ fontFamily: "var(--font-heading)" }}>Quick Examples</h3>
              <div className="flex flex-wrap gap-2">
                {PRESETS.map((p) => {
                  const active = cost === String(p.cost) && clicks === String(p.clicks);
                  return (
                    <button key={p.label} onClick={() => handlePreset(p)}
                      className={`px-3 py-1.5 rounded-lg text-sm font-medium transition-colors border ${active ? "bg-primary text-white border-primary" : "bg-gray-50 text-gray-700 border-gray-200 hover:bg-gray-100"}`}>
                      {p.label}
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Interpretation */}
            {result && perfStyle && (
              <div className={`rounded-xl border p-5 ${perfStyle.bg} ${perfStyle.border}`}>
                <p className={`text-xs font-semibold mb-1 ${perfStyle.text}`}>Interpretation</p>
                <p className={`text-sm ${perfStyle.text}`}>{result.interpretation}</p>
              </div>
            )}

            {/* Breakdown */}
            <div className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
              <div className="p-5 border-b border-gray-100 bg-gray-50/50">
                <h3 className="font-semibold text-gray-800 text-sm" style={{ fontFamily: "var(--font-heading)" }}>Calculation Breakdown</h3>
              </div>
              {result ? (
                <div className="divide-y divide-gray-50">
                  {[
                    { label: "Ad Spend",   value: formatCurrency(result.cost, result.currency) },
                    { label: "Clicks",     value: formatNumber(result.clicks) },
                    { label: "Formula",    value: result.formula },
                    { label: "CPC",        value: result.cpcFormatted, highlight: true },
                    { label: "Assessment", value: result.performanceLabel },
                  ].map(({ label, value, highlight }) => (
                    <div key={label} className="flex items-center justify-between px-5 py-3 hover:bg-gray-50 transition-colors">
                      <span className="text-sm text-gray-600">{label}</span>
                      <span className={`text-sm font-semibold font-mono ${highlight ? "text-primary text-base" : "text-gray-900"}`}>{value}</span>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="p-8 text-center text-gray-400 text-sm">
                  {costError || clicksError ? costError || clicksError : "Enter values above to see the breakdown"}
                </div>
              )}
            </div>

            {/* Performance Reference */}
            <div className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
              <div className="p-5 border-b border-gray-100 bg-gray-50/50">
                <h3 className="font-semibold text-gray-800 text-sm" style={{ fontFamily: "var(--font-heading)" }}>Performance Reference</h3>
              </div>
              <div className="divide-y divide-gray-50">
                {([
                  { level: "very-low",  label: "Very Low",  range: "< $0.20",        desc: "Exceptionally cheap traffic" },
                  { level: "low",       label: "Low",        range: "$0.20 – $0.74",  desc: "Below-average, cost-efficient" },
                  { level: "average",   label: "Average",    range: "$0.75 – $1.99",  desc: "Typical for most channels" },
                  { level: "high",      label: "High",       range: "$2.00 – $4.99",  desc: "Competitive industries" },
                  { level: "very-high", label: "Very High",  range: "≥ $5.00",        desc: "Premium, high-value markets" },
                ] as { level: CPCResult["performanceLevel"]; label: string; range: string; desc: string }[]).map(({ level, label, range, desc }) => {
                  const s = PERF_STYLES[level];
                  const isActive = result?.performanceLevel === level;
                  return (
                    <div key={level} className={`flex items-center justify-between px-5 py-3 transition-colors ${isActive ? "bg-primary/5" : "hover:bg-gray-50"}`}>
                      <div className="flex items-center gap-3">
                        <span className={`inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full text-xs font-semibold ${s.bg} ${s.text} ${s.border} border`}>
                          <span className={`w-1.5 h-1.5 rounded-full ${s.dot}`} />{label}
                        </span>
                        <span className="text-xs text-gray-500">{desc}</span>
                      </div>
                      <span className="text-xs font-mono font-semibold text-gray-700">{range}</span>
                    </div>
                  );
                })}
              </div>
              <p className="text-xs text-gray-400 px-5 py-3 border-t border-gray-50">* CPC benchmarks vary by industry. Always evaluate in context of your conversion rate and customer value.</p>
            </div>

            {/* History */}
            {showHistory && (
              <div className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
                <div className="p-4 border-b border-gray-100 bg-gray-50/50 flex items-center justify-between">
                  <h3 className="font-semibold text-gray-800 text-sm" style={{ fontFamily: "var(--font-heading)" }}>Calculation History</h3>
                  {history.length > 0 && <button onClick={() => { if (confirm("Clear all history?")) { clearHistory(); setHistory([]); } }} className="text-xs text-red-600 hover:text-red-700 font-medium">Clear All</button>}
                </div>
                <div className="divide-y divide-gray-50 max-h-72 overflow-y-auto">
                  {history.length === 0 ? (
                    <div className="p-6 text-center text-gray-400 text-sm">No saved calculations yet</div>
                  ) : history.map((entry) => (
                    <div key={entry.id} onClick={() => { setCost(String(entry.cost)); setClicks(String(entry.clicks)); setCurrency(entry.currency); setShowHistory(false); }}
                      className="p-4 hover:bg-gray-50 cursor-pointer transition-colors">
                      <div className="flex items-center justify-between mb-1">
                        <span className="font-mono text-sm font-semibold text-gray-900">{formatCurrency(entry.cost, entry.currency)} / {formatNumber(entry.clicks)} clicks</span>
                        <span className="text-xs text-gray-400">{new Date(entry.timestamp).toLocaleString("en-US")}</span>
                      </div>
                      <div className="text-xs text-primary font-mono font-semibold">CPC: {entry.result.cpcFormatted} · {entry.result.performanceLabel}</div>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      <CPCCalculatorSEO />

      <RelatedTools
        currentTool="cost-per-click-cpc-calculator"
        tools={[
          "ctr-calculator",
          "conversion-rate-calculator",
          "bounce-rate-calculator",
          "roi-calculator-marketing",
          "investment-return-calculator",
          "percentage-calculator",
        ]}
      />
    </>
  );
}
