export const anagramFinderConfig = {
  name: 'Anagram Finder',
  slug: 'anagram-finder',
  description: 'Check if two words or phrases are anagrams with instant results, letter frequency analysis, and advanced comparison options.',
  category: 'text',
  icon: '🔤',
  keywords: [
    'anagram finder',
    'anagram checker',
    'check anagrams online',
    'word anagram tool',
    'phrase anagram detector',
    'letter frequency analyzer',
    'anagram solver',
    'word scramble checker',
    'anagram comparison',
    'text anagram tool',
    'free anagram finder',
    'online anagram checker',
    'anagram generator',
    'word rearrangement tool',
    'letter sorting tool',
    'anagram validator',
    'bulk anagram checker',
    'multi-word anagram finder'
  ],
  seo: {
    title: 'Anagram Finder Online - Check Words and Phrases with Bulk Matching',
    description: 'Free Anagram Finder with single and bulk checking, letter frequency analysis, similarity scoring, and configurable ignore rules. Copy or download result reports instantly.',
    keywords: [
      'anagram finder',
      'anagram checker',
      'check anagrams online',
      'word anagram tool',
      'phrase anagram detector',
      'letter frequency analyzer',
      'anagram solver',
      'word scramble checker',
      'anagram comparison',
      'text anagram tool',
      'free anagram finder',
      'online anagram checker',
      'anagram generator',
      'word rearrangement tool',
      'letter sorting tool',
      'anagram validator',
      'bulk anagram checker',
      'multi-word anagram finder',
      'anagram checker for phrases',
      'anagram similarity calculator',
      'bulk word anagram check',
      'letter match analyzer',
      'anagram frequency checker',
      'find anagrams online free',
      'word puzzle anagram tool'
    ],
    openGraph: {
      title: 'Anagram Finder - Single and Bulk Anagram Checking with Letter Analysis',
      description: 'Compare words and phrases with advanced ignore rules, frequency insights, and result export options.',
      type: 'website',
      url: '/tools/writing/anagram-finder'
    }
  }
};
