import { siteConfig } from "@/config/site";

export const toolConfig = {
  slug: "word-counter",
  name: "Word Counter",
  description: "Count words, characters, sentences, paragraphs, and reading time instantly. Free online word counter — no sign-up required, runs entirely in your browser.",
  category: "writing",
  icon: "📝",
  free: true,
  backend: false,
  seo: {
    title: "Word Counter — Free Online Word Count Tool | Productive Toolbox",
    description: "Free online word counter that instantly counts words, characters, sentences, paragraphs, and reading time. Works with essays, blog posts, SEO content, and social media copy. No sign-up, 100% browser-based.",
    keywords: [
      "word counter online",
      "word counter",
      "character counter",
      "online word count",
      "word count checker",
      "reading time calculator",
      "word counter for essays",
      "word counter with character count",
      "free word counter no sign up",
      "word counter for twitter posts",
      "word counter copy paste",
      "word counter for blog posts",
      "word counter for seo",
      "sentence counter",
      "paragraph counter",
      "text analyzer",
      "writing word count tool",
      "academic word counter",
      "character count tool",
      "reading time estimator",
      "text length checker",
      "word count tool free",
      "online character counter",
      "copywriting word counter",
      "word frequency counter",
    ],
    openGraph: {
      title: "Word Counter — Free Online Word Count Tool",
      description: "Instantly count words, characters, sentences, paragraphs, and reading time. Free, no sign-up, runs entirely in your browser.",
      type: "website",
      url: `${siteConfig.url}/tools/writing/word-counter`,
    },
  },
  features: [
    "Real-time word counting as you type",
    "Character count with and without spaces",
    "Sentence and paragraph counting",
    "Reading time estimation (200 wpm baseline)",
    "Detailed text statistics",
    "No registration required",
    "100% browser-based — your text never leaves your device",
  ],
  relatedTools: [
    "reading-time-calculator",
    "keyword-density-checker",
    "character-counter",
    "text-case-converter",
    "word-frequency-counter",
    "plagiarism-checker",
  ],
};
