// ── Median Calculator Logic ──

export interface ParsedDataset {
  values: number[];
  invalidTokens: string[];
}

const SPLIT_RE = /[\s,;\t\n]+/;

export function parseDataset(input: string): ParsedDataset {
  const tokens = input.split(SPLIT_RE).map((t) => t.trim()).filter(Boolean);
  const values: number[] = [];
  const invalidTokens: string[] = [];
  for (const token of tokens) {
    const n = Number(token);
    if (token !== "" && !isNaN(n) && isFinite(n)) values.push(n);
    else invalidTokens.push(token);
  }
  return { values, invalidTokens };
}

export interface MedianResult {
  median: number;
  sorted: number[];
  count: number;
  isEven: boolean;
  min: number;
  max: number;
  sum: number;
  mean: number;
  middlePosition: string;
  formula: string;
  calculation: string;
}

export function calculateMedian(values: number[], decimals: number): MedianResult | null {
  if (values.length === 0) return null;

  const sorted = [...values].sort((a, b) => a - b);
  const n = sorted.length;
  const isEven = n % 2 === 0;
  const round = (v: number) => parseFloat(v.toFixed(decimals));

  let median: number;
  let middlePosition: string;
  let formula: string;
  let calculation: string;

  if (isEven) {
    const lo = sorted[n / 2 - 1];
    const hi = sorted[n / 2];
    median = round((lo + hi) / 2);
    middlePosition = `Positions ${n / 2} & ${n / 2 + 1}`;
    formula = "Median = (Middle 1 + Middle 2) / 2";
    calculation = `(${lo} + ${hi}) / 2 = ${median}`;
  } else {
    const mid = Math.floor(n / 2);
    median = round(sorted[mid]);
    middlePosition = `Position ${mid + 1}`;
    formula = "Median = Middle Value";
    calculation = `Middle value = ${median}`;
  }

  const sum = sorted.reduce((a, b) => a + b, 0);

  return {
    median, sorted, count: n, isEven,
    min: sorted[0], max: sorted[n - 1], sum,
    mean: round(sum / n),
    middlePosition, formula, calculation,
  };
}

// ── Sample data ───────────────────────────────────────────────────────────────

export const SAMPLE_TEXT = "10, 20, 30, 40, 50";

export function generateRandomSample(): string {
  const count = 8 + Math.floor(Math.random() * 8);
  const values = Array.from({ length: count }, () => Math.round((Math.random() * 100 - 20) * 10) / 10);
  return values.join(", ");
}

// ── Helpers ───────────────────────────────────────────────────────────────────

export function debounce<T extends (...args: never[]) => void>(fn: T, ms: number): (...args: Parameters<T>) => void {
  let timer: ReturnType<typeof setTimeout>;
  return (...args: Parameters<T>) => { clearTimeout(timer); timer = setTimeout(() => fn(...args), ms); };
}

export function formatNum(n: number): string {
  return n.toLocaleString("en-US", { maximumFractionDigits: 10 });
}

// ── LocalStorage: last-session input ──────────────────────────────────────────

const INPUT_KEY = "median-calculator-input";

export function saveInput(text: string): void {
  try { localStorage.setItem(INPUT_KEY, text); } catch {}
}

export function loadInput(): string | null {
  try { return localStorage.getItem(INPUT_KEY); } catch { return null; }
}

// ── History ────────────────────────────────────────────────────────────────────

export interface HistoryEntry {
  id: string;
  timestamp: number;
  input: string;
  result: MedianResult;
}

const HISTORY_KEY = "median-calculator-history";

export function saveHistory(entry: Omit<HistoryEntry, "id" | "timestamp">): void {
  const history = getHistory();
  const newEntry: HistoryEntry = { ...entry, id: Math.random().toString(36).slice(2), timestamp: Date.now() };
  try { localStorage.setItem(HISTORY_KEY, JSON.stringify([newEntry, ...history].slice(0, 20))); } catch {}
}

export function getHistory(): HistoryEntry[] {
  try { const raw = localStorage.getItem(HISTORY_KEY); return raw ? JSON.parse(raw) : []; } catch { return []; }
}

export function clearHistory(): void {
  try { localStorage.removeItem(HISTORY_KEY); } catch {}
}

// ── Export helpers ────────────────────────────────────────────────────────────

export function buildTextReport(result: MedianResult, originalInput: string): string {
  const ts = new Date().toLocaleString("en-US");
  return [
    "Median Calculator Report",
    "=========================",
    `Generated: ${ts}`,
    "",
    `Original Dataset: ${originalInput.trim()}`,
    `Sorted Dataset: ${result.sorted.join(", ")}`,
    "",
    `Total Count: ${result.count} (${result.isEven ? "Even" : "Odd"})`,
    `Minimum: ${result.min}`,
    `Maximum: ${result.max}`,
    `Sum: ${result.sum}`,
    `Mean: ${result.mean}`,
    "",
    `Median: ${result.median}`,
    `Formula: ${result.formula}`,
    `Calculation: ${result.calculation}`,
    `Middle Position: ${result.middlePosition}`,
    "",
    "Generated by Median Calculator — https://productivetoolbox.com",
  ].join("\n");
}

export function buildCSVReport(result: MedianResult): string {
  const rows = [
    ["Metric", "Value"],
    ["Count", String(result.count)],
    ["Minimum", String(result.min)],
    ["Maximum", String(result.max)],
    ["Sum", String(result.sum)],
    ["Mean", String(result.mean)],
    ["Median", String(result.median)],
    ["Sorted Dataset", result.sorted.join(" ")],
  ];
  return rows.map((r) => r.map((c) => `"${c}"`).join(",")).join("\n");
}
