export const toolConfig = {
  id: "morse-code-translator",
  slug: "morse-code-translator",
  name: "Morse Code Translator",
  description: "Convert text to Morse code and Morse code back to text instantly. Supports audio playback, custom symbols, and real-time translation.",
  category: "text",
  icon: "📡",
  keywords: [
    "morse code translator",
    "text to morse",
    "morse to text",
    "morse code converter",
    "morse decoder",
    "morse encoder",
    "morse code audio",
    "cw translator",
    "morse code practice",
    "dot dash converter",
    "learn morse code",
    "morse code generator",
    "morse code parser",
    "morse reference chart",
    "amateur radio morse",
    "morse signal translator",
    "real time morse translator",
    "free morse converter"
  ],
  seo: {
    title: "Morse Code Translator – Text to Morse, Decode & Audio",
    description: "Translate text to Morse code and Morse to text, with custom symbols and spacing, a reference chart and audio playback at adjustable speed.",
    keywords: "morse code translator, text to morse code, morse to text, morse code converter, morse decoder, morse encoder, morse code audio, cw translator, learn morse code, dot dash converter, real time morse translator, free morse converter",
    openGraph: {
      title: "Morse Code Translator – Text to Morse, Decode & Audio",
      description: "Translate text to Morse code and Morse to text, with custom symbols and spacing, a reference chart and audio playback at adjustable speed.",
      type: "website",
      url: "/tools/writing/morse-code-translator",
    },
  },
};
