export const toolConfig = {
  id: "morse-code-translator",
  slug: "morse-code-translator",
  name: "Morse Code Translator",
  description: "Convert text to Morse code and Morse code back to text instantly. Supports audio playback, custom symbols, and real-time translation.",
  category: "text",
  icon: "📡",
  keywords: [
    "morse code translator",
    "text to morse",
    "morse to text",
    "morse code converter",
    "morse decoder",
    "morse encoder",
    "morse code audio",
    "cw translator",
    "morse code practice",
    "dot dash converter",
    "learn morse code",
    "morse code generator",
    "morse code parser",
    "morse reference chart",
    "amateur radio morse",
    "morse signal translator",
    "real time morse translator",
    "free morse converter"
  ],
  seo: {
    title: "Morse Code Translator Online - Convert Text, Decode Signals, and Play Audio",
    description: "Free Morse Code Translator for text-to-morse and morse-to-text conversion with custom symbols, spacing controls, reference table, and adjustable audio playback.",
    keywords: "morse code translator, text to morse code, morse to text, morse code converter, morse decoder, morse encoder, morse code audio, cw translator, learn morse code, dot dash converter, real time morse translator, free morse converter",
    openGraph: {
      title: "Morse Code Translator - Two-Way Conversion with Audio and Custom Formatting",
      description: "Translate Morse code instantly with configurable symbols, spacing, playback speed, and downloadable output.",
      type: "website",
      url: "/tools/writing/morse-code-translator",
    },
  },
};
