export const toolConfig = {
  id: "upside-down-text-generator",
  slug: "upside-down-text-generator",
  name: "Upside-Down Text Generator",
  description: "Convert normal text into upside-down Unicode characters instantly. Perfect for social media, memes, and creative text effects.",
  category: "text",
  icon: "🙃",
  keywords: [
    "upside down text generator",
    "flip text",
    "unicode text flipper",
    "inverted text",
    "mirrored text",
    "flipped text generator",
    "text flipper",
    "upside down letters",
    "reverse unicode text",
    "fun text generator",
    "social media text effects",
    "creative text styling",
    "mirror text converter",
    "unicode character flip",
    "upside down converter online",
    "text reversal tool",
    "decode upside down text",
    "free upside down text tool"
  ],
  seo: {
    title: "Upside-Down Text Generator Online - Flip, Mirror, and Decode Unicode Text",
    description: "Free Upside-Down Text Generator with classic, mirrored, and fully flipped presets, reverse conversion, realtime output, and Unicode character mapping.",
    keywords: "upside down text generator, flip text, unicode text flipper, mirrored text converter, inverted text generator, upside down letters, reverse text unicode, decode upside down text, social media text effects, creative text tool",
    openGraph: {
      title: "Upside-Down Text Generator - Unicode Flip and Mirror Text Tool",
      description: "Create, customize, and decode upside-down Unicode text for social posts, memes, and creative messaging.",
      type: "website",
      url: "/tools/writing/upside-down-text-generator",
    },
  },
};
