export const whitespaceRemoverConfig = {
  name: "White Space Remover",
  slug: "whitespace-remover",
  description: "Remove extra spaces, leading/trailing whitespace, and clean up text formatting",
  category: "text",
  icon: "🧽",
  keywords: [
    "whitespace remover",
    "remove spaces",
    "text cleaner",
    "trim spaces",
    "clean text",
    "remove extra spaces",
    "text formatter",
    "space stripper",
    "text trimmer",
    "remove leading spaces",
    "remove trailing spaces",
    "text cleanup",
    "space remover",
    "text tool",
    "format text",
    "clean whitespace",
    "frontend text tool",
    "text processor"
  ],
  seo: {
    title: "White Space Remover Online - Clean Extra Spaces and Tabs Instantly",
    description: "Free White Space Remover to clean leading/trailing spaces, collapse multiple spaces, remove empty lines, and convert tabs. Export cleaned text in TXT, MD, or CSV.",
    keywords: [
      "whitespace remover",
      "remove spaces",
      "text cleaner",
      "trim spaces",
      "clean text",
      "remove extra spaces",
      "text formatter",
      "space stripper",
      "text trimmer",
      "remove leading spaces",
      "remove trailing spaces",
      "text cleanup",
      "space remover",
      "text tool",
      "format text",
      "clean whitespace",
      "frontend text tool",
      "text processor",
      "remove trailing spaces",
      "remove leading spaces",
      "strip whitespace online",
      "text whitespace cleaner",
      "tab to spaces converter",
      "spaces to tabs converter",
      "remove empty lines online",
      "text cleanup utility",
      "whitespace formatter tool"
    ],
    openGraph: {
      title: "White Space Remover - Clean and Normalize Text Formatting",
      description: "Remove unwanted spaces and tabs with configurable cleanup rules and export-ready output.",
      type: "website",
      url: "/tools/writing/whitespace-remover"
    }
  }
};
