import { siteConfig } from "@/config/site";

export const aiTokenCostCalculatorConfig = {
  slug: "ai-token-cost-calculator",
  name: "AI Token Cost Calculator",
  description: "Estimate AI API token costs for OpenAI, Claude, Gemini, and custom models. Calculate prompt and completion token expenses, compare models, and forecast monthly and yearly costs.",
  category: "computer-science",
  icon: "🤖",
  color: "#058554",
  featured: true,
  keywords: [
    "AI token calculator",
    "OpenAI token cost calculator",
    "GPT API pricing calculator",
    "Claude token pricing",
    "Gemini token cost",
    "LLM pricing calculator",
    "AI API cost estimator",
    "prompt token calculator",
  ],
  seo: {
    title: "AI Token Cost Calculator – Estimate LLM API Costs",
    description: "Estimate AI API costs from prompt and completion tokens for OpenAI, Claude, Gemini or a custom model price per million tokens.",
    keywords: "AI token calculator, OpenAI token cost calculator, GPT API pricing calculator, Claude token pricing, Gemini token cost, LLM pricing calculator, AI API cost estimator, prompt token calculator",
    og: {
      title: "AI Token Cost Calculator – Estimate LLM API Costs",
      description: "Estimate AI API costs from prompt and completion tokens for OpenAI, Claude, Gemini or a custom model price per million tokens.",
      type: "website",
      url: `${siteConfig.url}/tools/computer-science/ai-token-cost-calculator`,
    },
    faq: [
      { q: "How accurate are these cost estimates?", a: "The math is exact for the prices you enter. The model presets are example list prices collected in mid-2025 and providers change prices often, so check the provider's pricing page and edit the input and output price. Caching, batch and volume discounts lower real bills." },
      { q: "What is the difference between input and output tokens?", a: "Input tokens (also called prompt tokens) are the tokens you send to the model — your system prompt, conversation history, and user message. Output tokens (completion tokens) are generated by the model in its response. Output tokens typically cost more because generation is computationally intensive." },
      { q: "How do I estimate tokens for my use case?", a: "A quick rule of thumb: 1 token ≈ 4 characters. For English text, divide word count by 0.75. For code, tokens per character are often lower. OpenAI's Tokenizer tool and the Tiktoken library can give exact counts." },
      { q: "Which model is cheapest for a chatbot?", a: "For most chatbot use cases, GPT-4o Mini, Gemini 2.5 Flash, Claude Haiku, or Llama 3.1 8B (via Groq) offer the best price-to-performance ratio. Use the comparison tab to see side-by-side costs for your exact token usage." },
      { q: "Does caching reduce token costs?", a: "Yes. OpenAI's prompt caching and Anthropic's cache-control feature allow repeated prompt prefixes to be cached, reducing input token costs by up to 75–90% for matching cached segments." },
    ],
  },
  relatedTools: [
    "ai-prompt-length-calculator",
    "download-time-calculator",
    "data-transfer-calculator",
    "time-complexity-calculator",
  ],
};

export const toolConfig = aiTokenCostCalculatorConfig;
