export const removeDuplicateLinesConfig = {
  name: "Remove Duplicate Lines",
  slug: "remove-duplicate-lines",
  description: "Clean up text by removing duplicate lines instantly with advanced options",
  category: "text",
  icon: "🧹",
  keywords: [
    "remove duplicate lines",
    "text cleaner",
    "duplicate remover",
    "clean text online",
    "remove duplicates",
    "text deduplication",
    "list cleaner",
    "unique lines",
    "text processing",
    "line sorter",
    "text formatter",
    "duplicate finder",
    "text tool",
    "clean lists",
    "remove repeated lines",
    "text editor",
    "batch text processing",
    "frontend text tool"
  ],
  seo: {
    title: "Remove Duplicate Lines Online - Clean Repeated Text Entries Instantly",
    description: "Free Remove Duplicate Lines tool to deduplicate text lists with case handling, whitespace trim, empty-line removal, sorting, and duplicate-only mode. Copy or download cleaned output quickly.",
    keywords: [
      "remove duplicate lines",
      "text cleaner",
      "duplicate remover",
      "clean text online",
      "remove duplicates",
      "text deduplication",
      "list cleaner",
      "unique lines",
      "text processing",
      "line sorter",
      "text formatter",
      "duplicate finder",
      "text tool",
      "clean lists",
      "remove repeated lines",
      "text editor",
      "batch text processing",
      "frontend text tool",
      "line deduplication tool",
      "remove duplicate text entries",
      "unique line extractor",
      "list dedupe online",
      "csv line deduplicator",
      "remove repeated rows text",
      "duplicate line cleaner",
      "text list cleaner online",
      "keep only duplicate lines"
    ],
    openGraph: {
      title: "Remove Duplicate Lines Tool - Deduplicate Lists with Advanced Controls",
      description: "Clean repeated lines from text quickly with matching, sorting, and copy/download options.",
      type: "website",
      url: "/tools/writing/remove-duplicate-lines"
    }
  }
};
