export const naturalFrequencyCalculatorConfig = {
  name: "Natural Frequency Calculator",
  slug: "natural-frequency-calculator",
  description: "Calculate natural frequency of mechanical systems instantly. Supports spring-mass, pendulum, beam vibration, and torsional systems with unit conversion and step-by-step explanation.",
  category: "mechanical",
  icon: "〰️",
  free: true,
  seo: {
    title: "Free Natural Frequency Calculator – Mechanical Vibration Frequency Tool",
    description: "Calculate natural frequency instantly using spring-mass and pendulum formulas. Free mechanical engineering calculator with unit conversion and step-by-step explanation.",
    keywords: [
      "natural frequency calculator",
      "spring mass frequency calculator",
      "mechanical vibration calculator",
      "frequency of oscillation calculator",
      "engineering vibration calculator",
      "pendulum frequency calculator",
      "angular frequency calculator",
      "resonance frequency calculator",
      "beam natural frequency calculator",
      "torsional frequency calculator",
      "vibration analysis calculator",
      "mechanical engineering calculator",
    ],
    og: {
      title: "Free Natural Frequency Calculator – Mechanical Vibration Frequency Tool",
      description: "Calculate natural frequency instantly using spring-mass and pendulum formulas. Free mechanical engineering calculator with unit conversion and step-by-step explanation.",
      url: "https://www.engineeringcalcs.com/tools/mechanical/natural-frequency-calculator",
    },
  },
  relatedTools: [
    "spring-force-calculator",
    "damping-ratio-calculator",
    "torque-calculator",
    "kinetic-energy-calculator",
    "moment-of-inertia-calculator",
    "beam-deflection-calculator",
  ],
};
