"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import {
  calculateBounceRate,
  validateInputs,
  formatNumber,
  parseNumber,
  saveHistory,
  getHistory,
  clearHistory,
  debounce,
  buildShareUrl,
  parseShareParams,
  type BounceRateResult,
  type HistoryEntry,
} from "./logic";
import BounceRateCalculatorSEO from "./seo-content";
import RelatedTools from "@/components/RelatedTools";

const PRESETS = [
  { label: "Small Website", bounces: 500, totalVisits: 2000 },
  { label: "Blog", bounces: 3200, totalVisits: 4000 },
  { label: "E-commerce", bounces: 800, totalVisits: 2000 },
  { label: "Enterprise Site", bounces: 1250, totalVisits: 5000 },
  { label: "Landing Page", bounces: 1800, totalVisits: 2500 },
];

const PERFORMANCE_STYLES: Record<
  BounceRateResult["performanceLevel"],
  { bg: string; text: string; border: string; dot: string; bar: string }
> = {
  excellent: {
    bg: "bg-green-50",
    text: "text-green-700",
    border: "border-green-200",
    dot: "bg-green-500",
    bar: "bg-green-500",
  },
  good: {
    bg: "bg-blue-50",
    text: "text-blue-700",
    border: "border-blue-200",
    dot: "bg-blue-500",
    bar: "bg-blue-500",
  },
  average: {
    bg: "bg-yellow-50",
    text: "text-yellow-700",
    border: "border-yellow-200",
    dot: "bg-yellow-500",
    bar: "bg-yellow-500",
  },
  high: {
    bg: "bg-red-50",
    text: "text-red-700",
    border: "border-red-200",
    dot: "bg-red-500",
    bar: "bg-red-500",
  },
};

export default function BounceRateCalculatorUI() {
  const [bounces, setBounces] = useState("500");
  const [totalVisits, setTotalVisits] = useState("2000");
  const [decimalPlaces, setDecimalPlaces] = useState(2);
  const [result, setResult] = useState<BounceRateResult | null>(null);
  const [bouncesError, setBouncesError] = useState<string | null>(null);
  const [totalVisitsError, setTotalVisitsError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [shareCopied, setShareCopied] = useState(false);
  const [showHistory, setShowHistory] = useState(false);
  const [history, setHistory] = useState<HistoryEntry[]>([]);
  const bouncesRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    setHistory(getHistory());
    const shared = parseShareParams();
    if (shared) {
      setBounces(shared.bounces);
      setTotalVisits(shared.totalVisits);
    } else {
      bouncesRef.current?.focus();
    }
  }, []);

  const run = useCallback(
    debounce((b: string, t: string, dp: number) => {
      const { bouncesError: be, totalVisitsError: te } = validateInputs(b, t);
      setBouncesError(be);
      setTotalVisitsError(te);
      if (be || te) { setResult(null); return; }
      const bv = parseNumber(b);
      const tv = parseNumber(t);
      if (bv === null || tv === null) { setResult(null); return; }
      setResult(calculateBounceRate(bv, tv, dp));
    }, 120),
    []
  );

  useEffect(() => {
    run(bounces, totalVisits, decimalPlaces);
  }, [bounces, totalVisits, decimalPlaces, run]);

  const handlePreset = (p: (typeof PRESETS)[0]) => {
    setBounces(String(p.bounces));
    setTotalVisits(String(p.totalVisits));
    bouncesRef.current?.focus();
  };

  const handleReset = () => {
    setBounces("500");
    setTotalVisits("2000");
    setResult(null);
    setBouncesError(null);
    setTotalVisitsError(null);
    bouncesRef.current?.focus();
  };

  const handleCopyResult = () => {
    if (!result) return;
    navigator.clipboard.writeText(result.rateFormatted);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleCopyFull = () => {
    if (!result) return;
    const text = [
      `Bounce Rate Report`,
      `==================`,
      `Single Page Visits: ${formatNumber(result.bounces)}`,
      `Total Visits:       ${formatNumber(result.totalVisits)}`,
      `Formula:            ${result.formula}`,
      `Bounce Rate:        ${result.rateFormatted}`,
      `Assessment:         ${result.performanceLabel}`,
      ``,
      result.interpretation,
    ].join("\n");
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadTxt = () => {
    if (!result) return;
    const text = [
      `Bounce Rate Calculator Report`,
      `=============================`,
      ``,
      `Single Page Visits: ${formatNumber(result.bounces)}`,
      `Total Visits:       ${formatNumber(result.totalVisits)}`,
      `Formula:            ${result.formula}`,
      `Bounce Rate:        ${result.rateFormatted}`,
      `Assessment:         ${result.performanceLabel}`,
      ``,
      `Interpretation:`,
      result.interpretation,
      ``,
      `Generated by Productive Toolbox`,
    ].join("\n");
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `bounce_rate_${result.bounces}_${result.totalVisits}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadCsv = () => {
    if (!result) return;
    const csv = [
      "Single Page Visits,Total Visits,Bounce Rate,Assessment",
      `${result.bounces},${result.totalVisits},${result.rateFormatted},${result.performanceLabel}`,
    ].join("\n");
    const blob = new Blob([csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `bounce_rate_${result.bounces}_${result.totalVisits}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleShare = () => {
    if (!result) return;
    const url = buildShareUrl(result.bounces, result.totalVisits);
    navigator.clipboard.writeText(url);
    setShareCopied(true);
    setTimeout(() => setShareCopied(false), 2000);
  };

  const handleSave = () => {
    if (!result) return;
    saveHistory({ bounces: result.bounces, totalVisits: result.totalVisits, result });
    setHistory(getHistory());
  };

  const handleClearHistory = () => {
    if (confirm("Clear all calculation history?")) {
      clearHistory();
      setHistory([]);
    }
  };

  const loadFromHistory = (entry: HistoryEntry) => {
    setBounces(String(entry.bounces));
    setTotalVisits(String(entry.totalVisits));
    setShowHistory(false);
  };

  const perfStyle = result ? PERFORMANCE_STYLES[result.performanceLevel] : null;

  return (
    <>
      <div className="max-w-5xl mx-auto space-y-6">

        {/* Info Banner */}
        <div className="bg-blue-50 border border-blue-100 rounded-xl p-4 flex items-start gap-3">
          <span className="text-xl mt-0.5">📉</span>
          <div>
            <h3 className="text-sm font-semibold text-blue-900" style={{ fontFamily: "var(--font-heading)" }}>
              Bounce Rate Calculator
            </h3>
            <p className="text-sm text-blue-700 mt-0.5" style={{ fontFamily: "var(--font-body)" }}>
              Enter single page visits and total visits to instantly calculate your website bounce rate. All calculations run locally in your browser.
            </p>
          </div>
        </div>

        <div className="grid lg:grid-cols-12 gap-6">

          {/* Left: Controls */}
          <div className="lg:col-span-4 space-y-5">

            {/* Input Panel */}
            <div className="bg-white rounded-xl border border-gray-100 shadow-sm p-5 space-y-4">
              <h3 className="text-sm font-semibold text-gray-800" style={{ fontFamily: "var(--font-heading)" }}>
                Website Data
              </h3>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1.5" htmlFor="br-bounces">
                  Single Page Visits (Bounces)
                </label>
                <input
                  ref={bouncesRef}
                  id="br-bounces"
                  type="number"
                  min="0"
                  value={bounces}
                  onChange={(e) => setBounces(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && run(bounces, totalVisits, decimalPlaces)}
                  className={`w-full px-3 py-2.5 border-2 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent text-sm ${
                    bouncesError ? "border-red-300" : "border-gray-200"
                  }`}
                  placeholder="500"
                  aria-label="Single page visits"
                  aria-describedby={bouncesError ? "bounces-error" : undefined}
                  inputMode="numeric"
                />
                {bouncesError && (
                  <p id="bounces-error" className="text-xs text-red-600 mt-1" role="alert">
                    {bouncesError}
                  </p>
                )}
                <p className="text-xs text-gray-400 mt-1">Sessions where user viewed only one page</p>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1.5" htmlFor="br-total">
                  Total Visits
                </label>
                <input
                  id="br-total"
                  type="number"
                  min="1"
                  value={totalVisits}
                  onChange={(e) => setTotalVisits(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && run(bounces, totalVisits, decimalPlaces)}
                  className={`w-full px-3 py-2.5 border-2 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent text-sm ${
                    totalVisitsError ? "border-red-300" : "border-gray-200"
                  }`}
                  placeholder="2000"
                  aria-label="Total visits"
                  aria-describedby={totalVisitsError ? "total-error" : undefined}
                  inputMode="numeric"
                />
                {totalVisitsError && (
                  <p id="total-error" className="text-xs text-red-600 mt-1" role="alert">
                    {totalVisitsError}
                  </p>
                )}
                <p className="text-xs text-gray-400 mt-1">Total sessions or visits in the same period</p>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1.5" htmlFor="br-decimal">
                  Decimal Places
                </label>
                <select
                  id="br-decimal"
                  value={decimalPlaces}
                  onChange={(e) => setDecimalPlaces(Number(e.target.value))}
                  className="w-full px-3 py-2.5 border-2 border-gray-200 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent text-sm bg-white"
                  aria-label="Decimal precision"
                >
                  {[0, 1, 2, 3, 4].map((d) => (
                    <option key={d} value={d}>{d} decimal{d !== 1 ? "s" : ""}</option>
                  ))}
                </select>
              </div>

              <p className="text-xs text-gray-400">
                Press <kbd className="px-1 py-0.5 bg-gray-100 rounded text-xs font-mono">Enter</kbd> to recalculate
              </p>

              <div className="space-y-2 pt-1">
                <button
                  onClick={handleReset}
                  className="w-full px-4 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg text-sm font-medium transition-colors"
                >
                  Reset
                </button>
                <div className="grid grid-cols-2 gap-2">
                  <button
                    onClick={handleDownloadTxt}
                    disabled={!result}
                    className="px-3 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg text-xs font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    Export TXT
                  </button>
                  <button
                    onClick={handleDownloadCsv}
                    disabled={!result}
                    className="px-3 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg text-xs font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    Export CSV
                  </button>
                </div>
                <button
                  onClick={() => setShowHistory(!showHistory)}
                  className="w-full px-4 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg text-sm font-medium transition-colors"
                >
                  {showHistory ? "Hide" : "Show"} History
                </button>
              </div>
            </div>

            {/* Result Summary Card */}
            <div className="bg-primary rounded-xl border border-primary shadow-lg shadow-primary/20 p-5 text-white">
              <p className="text-primary-100 text-xs font-semibold uppercase tracking-wider mb-2" style={{ fontFamily: "var(--font-heading)" }}>
                Result
              </p>
              {result ? (
                <>
                  <div className="text-4xl font-bold font-mono mb-1 tabular-nums">
                    {result.rateFormatted}
                  </div>
                  <div className="text-sm text-primary-100 mb-1 font-mono">
                    {result.formula}
                  </div>
                  {perfStyle && (
                    <div className="flex items-center gap-2 mb-3 mt-2">
                      <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold ${perfStyle.bg} ${perfStyle.text} ${perfStyle.border} border`}>
                        <span className={`w-1.5 h-1.5 rounded-full ${perfStyle.dot}`} />
                        {result.performanceLabel}
                      </span>
                    </div>
                  )}
                  {result.warning && (
                    <p className="text-xs text-yellow-200 bg-yellow-900/30 rounded-lg px-3 py-2 mb-3">
                      ⚠ {result.warning}
                    </p>
                  )}
                  <div className="border-t border-white/20 pt-3 space-y-1 text-sm mb-4">
                    <div className="flex justify-between">
                      <span className="text-primary-100">Bounces</span>
                      <span className="font-semibold font-mono">{formatNumber(result.bounces)}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-primary-100">Total Visits</span>
                      <span className="font-semibold font-mono">{formatNumber(result.totalVisits)}</span>
                    </div>
                  </div>
                  <div className="space-y-2">
                    <button
                      onClick={handleCopyResult}
                      className="w-full bg-white text-primary font-semibold py-2 rounded-lg hover:bg-gray-50 transition-colors text-sm"
                    >
                      {copied ? "✓ Copied!" : "Copy Rate"}
                    </button>
                    <div className="grid grid-cols-2 gap-2">
                      <button
                        onClick={handleCopyFull}
                        className="border border-white/30 text-white font-medium py-2 rounded-lg hover:bg-white/10 transition-colors text-xs"
                      >
                        Copy All
                      </button>
                      <button
                        onClick={handleShare}
                        className="border border-white/30 text-white font-medium py-2 rounded-lg hover:bg-white/10 transition-colors text-xs"
                      >
                        {shareCopied ? "✓ Copied!" : "Share URL"}
                      </button>
                    </div>
                    <button
                      onClick={handleSave}
                      className="w-full border border-white/30 text-white font-medium py-2 rounded-lg hover:bg-white/10 transition-colors text-sm"
                    >
                      Save to History
                    </button>
                  </div>
                </>
              ) : (
                <div className="text-primary-100 text-sm">
                  {bouncesError || totalVisitsError
                    ? "Fix the errors above to calculate"
                    : "Enter bounces and total visits to calculate"}
                </div>
              )}
            </div>

          </div>

          {/* Right: Results */}
          <div className="lg:col-span-8 space-y-5">

            {/* Quick Presets */}
            <div className="bg-white rounded-xl border border-gray-100 shadow-sm p-5">
              <h3 className="text-sm font-semibold text-gray-800 mb-3" style={{ fontFamily: "var(--font-heading)" }}>
                Quick Examples
              </h3>
              <div className="flex flex-wrap gap-2">
                {PRESETS.map((p) => {
                  const active =
                    bounces === String(p.bounces) && totalVisits === String(p.totalVisits);
                  return (
                    <button
                      key={p.label}
                      onClick={() => handlePreset(p)}
                      className={`px-3 py-1.5 rounded-lg text-sm font-medium transition-colors border ${
                        active
                          ? "bg-primary text-white border-primary"
                          : "bg-gray-50 text-gray-700 border-gray-200 hover:bg-gray-100"
                      }`}
                    >
                      {p.label}
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Progress Bar Visualization */}
            {result && perfStyle && (
              <div className="bg-white rounded-xl border border-gray-100 shadow-sm p-5">
                <h3 className="text-sm font-semibold text-gray-800 mb-3" style={{ fontFamily: "var(--font-heading)" }}>
                  Bounce Rate Visualization
                </h3>
                <div className="space-y-2">
                  <div className="flex justify-between text-xs text-gray-500 mb-1">
                    <span>0% (Best)</span>
                    <span className={`font-semibold ${perfStyle.text}`}>{result.rateFormatted}</span>
                    <span>100% (Worst)</span>
                  </div>
                  <div className="w-full bg-gray-100 rounded-full h-3 overflow-hidden">
                    <div
                      className={`h-3 rounded-full transition-all duration-500 ${perfStyle.bar}`}
                      style={{ width: `${Math.min(result.rate, 100)}%` }}
                      role="progressbar"
                      aria-valuenow={result.rate}
                      aria-valuemin={0}
                      aria-valuemax={100}
                    />
                  </div>
                </div>
                {/* Interpretation */}
                <div className={`mt-4 rounded-lg p-3 border ${perfStyle.bg} ${perfStyle.border}`}>
                  <p className={`text-xs font-semibold mb-1 ${perfStyle.text}`}>Interpretation</p>
                  <p className={`text-sm ${perfStyle.text}`}>{result.interpretation}</p>
                </div>
              </div>
            )}

            {/* Calculation Breakdown */}
            <div className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
              <div className="p-5 border-b border-gray-100 bg-gray-50/50">
                <h3 className="font-semibold text-gray-800 text-sm" style={{ fontFamily: "var(--font-heading)" }}>
                  Calculation Breakdown
                </h3>
              </div>
              {result ? (
                <div className="divide-y divide-gray-50">
                  {[
                    { label: "Single Page Visits", value: formatNumber(result.bounces), mono: true },
                    { label: "Total Visits", value: formatNumber(result.totalVisits), mono: true },
                    { label: "Formula", value: result.formula, mono: true },
                    { label: "Bounce Rate", value: result.rateFormatted, mono: true, highlight: true },
                    { label: "Assessment", value: result.performanceLabel, mono: false },
                  ].map(({ label, value, mono, highlight }) => (
                    <div
                      key={label}
                      className="flex items-center justify-between px-5 py-3 hover:bg-gray-50 transition-colors"
                    >
                      <span className="text-sm text-gray-600">{label}</span>
                      <span className={`text-sm font-semibold ${mono ? "font-mono" : ""} ${highlight ? "text-primary text-base" : "text-gray-900"}`}>
                        {value}
                      </span>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="p-8 text-center text-gray-400 text-sm">
                  {bouncesError || totalVisitsError
                    ? bouncesError || totalVisitsError
                    : "Enter values above to see the breakdown"}
                </div>
              )}
            </div>

            {/* Performance Reference */}
            <div className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
              <div className="p-5 border-b border-gray-100 bg-gray-50/50">
                <h3 className="font-semibold text-gray-800 text-sm" style={{ fontFamily: "var(--font-heading)" }}>
                  Performance Reference
                </h3>
              </div>
              <div className="divide-y divide-gray-50">
                {[
                  { level: "excellent" as const, label: "Excellent", range: "0% – 30%", desc: "Highly engaged visitors" },
                  { level: "good" as const, label: "Good", range: "31% – 50%", desc: "Healthy engagement" },
                  { level: "average" as const, label: "Average", range: "51% – 70%", desc: "Typical for most websites" },
                  { level: "high" as const, label: "High", range: "71% – 100%", desc: "Many visitors leave after one page" },
                ].map(({ level, label, range, desc }) => {
                  const s = PERFORMANCE_STYLES[level];
                  const isActive = result?.performanceLevel === level;
                  return (
                    <div
                      key={level}
                      className={`flex items-center justify-between px-5 py-3 transition-colors ${
                        isActive ? "bg-primary/5" : "hover:bg-gray-50"
                      }`}
                    >
                      <div className="flex items-center gap-3">
                        <span className={`inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full text-xs font-semibold ${s.bg} ${s.text} ${s.border} border`}>
                          <span className={`w-1.5 h-1.5 rounded-full ${s.dot}`} />
                          {label}
                        </span>
                        <span className="text-xs text-gray-500">{desc}</span>
                      </div>
                      <span className="text-xs font-mono font-semibold text-gray-700">{range}</span>
                    </div>
                  );
                })}
              </div>
              <p className="text-xs text-gray-400 px-5 py-3 border-t border-gray-50">
                * Context matters: a high bounce rate on a blog or news site may be acceptable. Always compare against your own baseline.
              </p>
            </div>

            {/* History */}
            {showHistory && (
              <div className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
                <div className="p-4 border-b border-gray-100 bg-gray-50/50 flex items-center justify-between">
                  <h3 className="font-semibold text-gray-800 text-sm" style={{ fontFamily: "var(--font-heading)" }}>
                    Calculation History
                  </h3>
                  {history.length > 0 && (
                    <button
                      onClick={handleClearHistory}
                      className="text-xs text-red-600 hover:text-red-700 font-medium"
                    >
                      Clear All
                    </button>
                  )}
                </div>
                <div className="divide-y divide-gray-50 max-h-72 overflow-y-auto">
                  {history.length === 0 ? (
                    <div className="p-6 text-center text-gray-400 text-sm">No saved calculations yet</div>
                  ) : (
                    history.map((entry) => (
                      <div
                        key={entry.id}
                        onClick={() => loadFromHistory(entry)}
                        className="p-4 hover:bg-gray-50 cursor-pointer transition-colors"
                      >
                        <div className="flex items-center justify-between mb-1">
                          <span className="font-mono text-sm font-semibold text-gray-900">
                            {formatNumber(entry.bounces)} / {formatNumber(entry.totalVisits)} visits
                          </span>
                          <span className="text-xs text-gray-400">
                            {new Date(entry.timestamp).toLocaleString("en-US")}
                          </span>
                        </div>
                        <div className="text-xs text-primary font-mono font-semibold">
                          Bounce Rate: {entry.result.rateFormatted} · {entry.result.performanceLabel}
                        </div>
                      </div>
                    ))
                  )}
                </div>
              </div>
            )}

          </div>
        </div>
      </div>

      <BounceRateCalculatorSEO />

      <RelatedTools
        currentTool="bounce-rate-calculator"
        tools={[
          "ctr-calculator",
          "conversion-rate-calculator",
          "percentage-calculator",
          "discount-calculator",
          "investment-return-calculator",
          "simple-interest-calculator",
        ]}
      />
    </>
  );
}
