import { siteConfig } from "@/config/site";

export const acreToHectareConverterConfig = {
  name: "Acre to Hectare Converter",
  slug: "acre-to-hectare-converter",
  description: "Convert acres to hectares and hectares to acres instantly. Free online land area converter with comprehensive reference table, precision control, and conversion history.",
  category: "land",
  icon: "🔄",
  free: true,
  backend: false,
  seo: {
    title: "Acre to Hectare Converter — Free Acres to ha Calculator | Productive Toolbox",
    description: "Convert acres to hectares instantly. Free acres to ha calculator with full reference table, reverse conversion, and common values. Browser-based, no signup.",
    keywords: [
      "acre to hectare converter",
      "acres to hectares",
      "convert acres to hectares",
      "acre to hectare",
      "1 acre to hectare",
      "0.5 acres to hectares",
      "2.5 acres to hectares",
      "10 acres to hectares",
      "100 acres to hectares",
      "acres in hectares",
      "ac to ha",
      "hectares to acres",
      "hectare to acre",
      "convert hectares to acres",
      "1 acre in hectares",
      "acre to hectare calculator",
      "land area converter",
      "how many hectares in an acre",
      "how many acres in a hectare",
      "acre hectare conversion",
      "acres to ha calculator",
      "free acre to hectare converter",
      "imperial to metric land conversion",
      "acre to hectare formula",
      "acres hectares conversion table",
    ],
    openGraph: {
      title: "Acre to Hectare Converter — Free Acres to ha Calculator",
      description: "Convert acres to hectares and hectares to acres instantly. Full reference table, precision control, reverse conversion. Browser-based, free.",
      type: "website",
      url: `${siteConfig.url}/tools/land/acre-to-hectare-converter`,
    },
    og: {
      title: "Acre to Hectare Converter — Free Acres to ha Calculator",
      description: "Convert acres to hectares and hectares to acres instantly. Full reference table, precision control, reverse conversion. Browser-based, free.",
      url: `${siteConfig.url}/tools/land/acre-to-hectare-converter`,
    },
    howToSteps: [
      { name: "Enter Your Acre Value", text: "Type any number of acres into the input field. Decimals are fully supported — for example, 0.25, 1.5, or 640. The conversion result appears instantly as you type." },
      { name: "Read the Hectare Result", text: "The hectare equivalent appears immediately. For a 1 acre input, the result is 0.404686 hectares. The result updates with every keystroke." },
      { name: "Adjust Decimal Precision", text: "Use the precision selector to choose 2, 4, 6, or 8 decimal places. 4 decimal places is suitable for most practical applications; 6+ for scientific or legal precision." },
      { name: "Use Presets for Common Values", text: "Click any preset button (0.25, 0.5, 1, 5, 10, 100 acres) to instantly load standard values. Ideal for quickly checking residential lot or farm field sizes." },
      { name: "Swap to Hectares to Acres", text: "Click the swap button to reverse the conversion direction — so you can enter hectares and receive acres. The same tool covers both acres to ha and ha to acres." },
      { name: "Copy or Export", text: "Click the copy button to copy the result to clipboard, or download a text report of your conversion history for documentation or client handoff." },
    ],
    faq: [
      { q: "How many hectares is 1 acre?", a: "1 acre equals 0.404686 hectares. This is derived from the exact definitions: 1 acre = 4,046.856 square meters and 1 hectare = 10,000 square meters. Dividing: 4,046.856 ÷ 10,000 = 0.404686." },
      { q: "How many acres is 1 hectare?", a: "1 hectare equals 2.47105 acres. This is the reciprocal of the acre-to-hectare factor: 1 ÷ 0.404686 = 2.47105. So 5 hectares equals 12.3553 acres." },
      { q: "How many hectares is 0.5 acres?", a: "0.5 acres equals 0.202343 hectares. Calculation: 0.5 × 0.404686 = 0.202343. A half-acre lot is approximately 0.20 hectares." },
      { q: "How many hectares is 2.5 acres?", a: "2.5 acres equals 1.01172 hectares. Calculation: 2.5 × 0.404686 = 1.01172." },
      { q: "How many hectares is 10 acres?", a: "10 acres equals 4.04686 hectares. Calculation: 10 × 0.404686 = 4.04686." },
      { q: "How many hectares is 100 acres?", a: "100 acres equals 40.4686 hectares. Calculation: 100 × 0.404686 = 40.4686." },
      { q: "How many hectares is 640 acres (1 square mile)?", a: "640 acres equals 258.999 hectares — approximately 259 hectares. One US section (1 square mile) of land is 640 acres or about 259 hectares." },
      { q: "What is the acre to hectare formula?", a: "Hectares = Acres × 0.404686. For reverse conversion: Acres = Hectares × 2.47105. Both conversion factors are internationally standardized and used in all official land measurement systems." },
      { q: "Where are acres used vs hectares?", a: "Acres are primarily used in the United States, United Kingdom, Canada, and a few other countries for real estate and agriculture. Hectares are the standard metric unit used across most of Europe, Asia, Africa, and South America, and in all international agricultural and environmental data." },
      { q: "Is my data private when using this converter?", a: "Yes. All conversions run entirely in your browser using JavaScript. Your inputs are never sent to any server, stored in any database, or accessible to anyone other than you." },
    ],
  },
  features: [
    "Instant acres to hectares conversion",
    "Reverse conversion: hectares to acres",
    "2, 4, 6, and 8 decimal precision options",
    "Quick presets for common land sizes",
    "Comprehensive reference table",
    "Land size context descriptions",
    "Conversion history (last 10 entries)",
    "Copy result to clipboard",
    "Export conversion report",
    "100% browser-based — no data sent to server",
    "No registration required",
  ],
  relatedTools: [
    "hectare-to-acre-converter",
    "acre-to-square-feet-converter",
    "square-feet-to-acre-converter",
    "decimal-land-calculator",
    "land-area-calculator-square-meter",
    "land-price-calculator",
  ],
};
