import { siteConfig } from "@/config/site";

export const toolConfig = {
  slug: "fuel-cost-calculator",
  name: "Fuel Cost Calculator",
  description: "Calculate fuel needed and total trip cost from distance, MPG or km/L, and fuel price. Supports miles and kilometers with cost-per-mile or cost-per-km output.",
  category: "calculator",
  icon: "⛽",
  free: true,
  backend: false,
  seo: {
    title: "Fuel Cost Calculator — Free Gas & Trip Cost Estimator Online | Productive Toolbox",
    description: "Calculate fuel needed and total trip cost from distance, MPG or km/L, and fuel price. Free fuel cost calculator for road trips and commutes. No signup.",
    keywords: [
      "fuel cost calculator",
      "gas cost calculator",
      "trip fuel cost calculator",
      "fuel consumption calculator",
      "mpg calculator",
      "km/l calculator",
      "road trip cost calculator",
      "fuel cost per mile calculator",
      "calculate fuel cost",
      "travel fuel calculator",
      "fuel efficiency calculator",
      "fuel needed calculator",
      "petrol cost calculator",
      "gas mileage calculator",
      "fuel price calculator",
      "commute fuel cost calculator",
      "cost per mile calculator",
      "trip gas cost estimator",
      "fuel cost calculator free",
      "how much will fuel cost calculator",
      "miles per gallon fuel cost",
      "fuel cost per km calculator",
      "fuel cost for a trip",
      "road trip gas estimator",
      "diesel cost calculator",
    ],
    openGraph: {
      title: "Fuel Cost Calculator — Free Gas & Trip Cost Estimator Online",
      description: "Calculate fuel needed and total trip cost from distance, MPG or km/L, and fuel price. Supports miles and kilometers. CSV export, no signup.",
      type: "website",
      url: `${siteConfig.url}/tools/calculator/fuel-cost-calculator`,
    },
    howToSteps: [
      { name: "Choose Unit System", text: "Select Imperial (miles and MPG) or Metric (kilometers and km/L). This determines the units for distance, fuel efficiency, and cost-per-distance output." },
      { name: "Enter Trip Distance", text: "Type your total route distance in miles or kilometers. For round trips, enter the full distance both ways. For multi-leg trips, add all legs together." },
      { name: "Enter Fuel Efficiency", text: "Type your vehicle's average real-world fuel efficiency in MPG or km/L. Use your actual average rather than manufacturer ratings for a more accurate estimate." },
      { name: "Enter Fuel Price", text: "Type the current fuel price per gallon or per liter. Select your currency — USD, EUR, GBP, CAD, AUD, or INR. Fuel prices vary by location and day, so check before a long trip." },
      { name: "Read Your Results", text: "The calculator returns total fuel needed, estimated trip cost, and cost per mile or kilometer — updated instantly as you type any input." },
      { name: "Export or Save", text: "Click Export CSV to download a history of your calculations for travel reimbursement records, expense logs, or monthly commute budget tracking." },
    ],
    faq: [
      { q: "What is a fuel cost calculator?", a: "A fuel cost calculator is a free online tool that estimates how much fuel you will need for a trip and the total cost at current fuel prices. You enter the trip distance, your vehicle's fuel efficiency (MPG or km/L), and the current fuel price per gallon or liter. The calculator returns total fuel quantity, total trip cost, and cost per mile or kilometer." },
      { q: "How is trip fuel cost calculated?", a: "Fuel cost is calculated in two steps. First: Fuel Needed = Distance ÷ Fuel Efficiency. Then: Trip Cost = Fuel Needed × Price per Unit. For example, 300 miles at 30 MPG needs 10 gallons. At $3.80/gallon, the trip costs $38.00. Cost per mile = $38.00 ÷ 300 = $0.127/mile." },
      { q: "How do I calculate fuel cost in km/L?", a: "The formula is identical: Fuel Needed (liters) = Distance (km) ÷ Efficiency (km/L). Trip Cost = Fuel Needed × Price per liter. Example: 400 km at 15 km/L = 26.67 liters. At €1.80/liter, the trip costs €48.00. Cost per km = €48.00 ÷ 400 = €0.12/km." },
      { q: "How do I estimate monthly fuel cost for commuting?", a: "Multiply your daily round-trip distance by the number of commuting days per month, then run the calculation. Example: 35-mile daily round trip × 22 days = 770 miles/month. At 28 MPG and $3.60/gallon: 770 ÷ 28 = 27.5 gallons × $3.60 = $99.00/month." },
      { q: "What is a good MPG for fuel cost planning?", a: "For personal cars, 25–35 MPG is typical for most modern sedans. SUVs and trucks average 18–25 MPG. Hybrids achieve 45–60 MPG. For fuel cost calculations, always use your vehicle's real-world average, not the EPA-rated value — actual consumption is typically 10–20% lower than the manufacturer's test rating." },
      { q: "Can I calculate fuel cost in liters per 100km (L/100km)?", a: "Convert L/100km to km/L first: km/L = 100 ÷ L/100km. For example, a vehicle rated at 8 L/100km achieves 100 ÷ 8 = 12.5 km/L. Enter 12.5 in the km/L field. European fuel efficiency is typically quoted as L/100km; Asian and UK specifications often use both." },
      { q: "How do I calculate fuel cost for a road trip with multiple stops?", a: "Add all driving legs together into a total distance, then run a single calculation. Alternatively, run a separate calculation for each leg if fuel prices differ significantly between regions, then sum the results. Use the CSV export to accumulate multiple calculation results." },
      { q: "Does driving speed affect fuel consumption?", a: "Yes significantly. Most vehicles are most efficient at 45–65 mph (70–105 km/h). Above 70 mph, aerodynamic drag increases fuel consumption sharply — driving at 80 mph instead of 65 mph typically increases fuel use by 15–25%. For long highway trips at high speed, reduce your entered MPG by 10–15% from your city/mixed average for a more accurate estimate." },
      { q: "Can I use this for diesel vehicles?", a: "Yes. The formula is identical for diesel, gasoline, and any liquid fuel. Enter your diesel vehicle's MPG or km/L and the current diesel price per gallon or liter. The calculation logic is the same regardless of fuel type." },
      { q: "Is my data private when using this calculator?", a: "Yes. All calculations run entirely in your browser using JavaScript. Your distance, efficiency, and price inputs are never sent to any server or stored outside your device. Calculation history is saved only in your browser's localStorage." },
    ],
  },
  features: [
    "Total fuel needed for any trip",
    "Total trip cost in your currency",
    "Cost per mile or km",
    "Imperial (miles/MPG) and Metric (km/km·L) modes",
    "Multi-currency: USD, EUR, GBP, CAD, AUD, INR",
    "Real-time results as you type",
    "Monthly commute cost mode",
    "Calculation history saved to browser",
    "Export history to CSV",
    "Copy result to clipboard",
    "100% browser-based — no data sent to server",
    "No registration required",
  ],
  relatedTools: [
    "electric-motor-power-calculator",
    "air-conditioner-power-calculator",
    "discount-calculator",
    "average-calculator",
    "date-difference-calculator",
    "unit-ratio-calculator",
  ],
};
