import { siteConfig } from "@/config/site";

export const toolConfig = {
  slug: "fuel-cost-calculator",
  name: "Fuel Cost Calculator",
  description: "Calculate fuel needed and total trip cost from distance, MPG or km/L, and fuel price. Supports miles and kilometers with cost-per-mile or cost-per-km output.",
  category: "calculator",
  icon: "⛽",
  free: true,
  backend: false,
  seo: {
    title: "Fuel Cost Calculator — Trip Gas Cost in MPG or L/100 km",
    description: "Work out fuel and trip cost from distance, MPG or L/100 km and fuel price. Round trips, cost split per person and an EV comparison. Free, no sign-up.",
    keywords: [
      "fuel cost calculator",
      "gas cost calculator",
      "trip fuel cost calculator",
      "fuel consumption calculator",
      "mpg calculator",
      "km/l calculator",
      "road trip cost calculator",
      "fuel cost per mile calculator",
      "calculate fuel cost",
      "travel fuel calculator",
      "fuel efficiency calculator",
      "fuel needed calculator",
      "petrol cost calculator",
      "gas mileage calculator",
      "fuel price calculator",
      "commute fuel cost calculator",
      "cost per mile calculator",
      "trip gas cost estimator",
      "fuel cost calculator free",
      "how much will fuel cost calculator",
      "miles per gallon fuel cost",
      "fuel cost per km calculator",
      "fuel cost for a trip",
      "road trip gas estimator",
      "diesel cost calculator",
    ],
    openGraph: {
      title: "Fuel Cost Calculator — Trip Gas Cost in MPG or L/100 km",
      description: "Work out fuel and trip cost from distance, MPG or L/100 km and fuel price. Round trips, cost split per person and an EV comparison. Free, no sign-up.",
      type: "website",
      url: `${siteConfig.url}/tools/calculator/fuel-cost-calculator`,
    },
    howToSteps: [
      { name: "Choose your units", text: "Pick miles, MPG and gallons, or kilometers and liters. In kilometer mode you can enter economy as L/100 km, the European convention, or as km/L." },
      { name: "Enter the trip", text: "Type the one-way distance and tick Round trip to double it. For a trip with several legs, add them together." },
      { name: "Enter fuel economy and price", text: "Use your car's real-world average and today's price per gallon or liter. The currency is guessed from your location and can be changed." },
      { name: "Split or compare (optional)", text: "Enter how many people share the cost, and compare the trip with another car or with an electric car using its kWh per 100 miles or km and your electricity price." },
      { name: "Calculate", text: "Press Calculate Cost to see the fuel needed, total cost, cost per mile or km, the share per person and the comparison." },
      { name: "Copy or export", text: "Copy the summary, or open the history to download your recent calculations as a CSV file for expense claims." },
    ],
    faq: [
      { q: "How is trip fuel cost calculated?", a: "Fuel needed = distance ÷ fuel economy, and trip cost = fuel needed × price per gallon or liter. For example, 300 miles at 30 MPG needs 10 gallons; at $3.80 a gallon the trip costs $38.00, or about 12.7 cents a mile." },
      { q: "How do I use L/100 km?", a: "Switch to kilometers and choose L/100 km, the unit used on European spec sheets. The calculator turns it into liters for the trip: 400 km at 6.5 L/100 km uses 26 liters; at €1.75 a liter that is €45.50." },
      { q: "How do I convert UK MPG to US MPG?", a: "UK MPG uses the imperial gallon (4.546 liters), which is about 20% larger than the US gallon (3.785 liters). Multiply UK MPG by 0.833 to get US MPG, or by 0.354 to get km/L." },
      { q: "How do I calculate a round trip?", a: "Enter the one-way distance and tick Round trip; the calculator doubles the distance before working out fuel and cost." },
      { q: "How do I split fuel costs between passengers?", a: "Enter the number of people sharing the ride in Split the cost between. The result shows each person's share of the fuel cost. Tolls and parking are not included." },
      { q: "Is an electric car cheaper for this trip?", a: "Choose Compare with an electric car and enter its consumption and your electricity price per kWh. Typical consumption is 25–35 kWh per 100 miles, or 16–22 kWh per 100 km. Home charging is usually much cheaper than public fast charging, so use the rate you will actually pay." },
      { q: "How do I estimate my monthly commuting cost?", a: "Multiply your one-way commute by two and by your working days, then enter that distance. For example, 17.5 miles each way × 2 × 22 days = 770 miles; at 28 MPG and $3.60 a gallon that is 27.5 gallons, or $99.00 a month." },
      { q: "What fuel economy should I enter?", a: "Your car's real-world average, from its trip computer or fill-up records. Real-world figures are often 10–20% worse than the official rating, especially in city driving or cold weather." },
      { q: "Does driving speed affect fuel consumption?", a: "Yes. According to the US Department of Energy, fuel economy usually drops quickly at speeds above about 50 mph (80 km/h), because air resistance rises with speed. For a fast highway trip, enter a lower economy figure than your mixed average." },
      { q: "Can I use this for diesel?", a: "Yes. The formula is the same for gasoline and diesel. Enter the diesel price and your car's diesel economy." },
      { q: "Is my data private?", a: "Yes. Everything is calculated in your browser. Recent calculations and your currency choice are kept only in this browser's local storage." },
    ],
  },
  features: [
    "Fuel needed, total trip cost and cost per mile or km",
    "Miles/MPG/gallons or km with L/100 km or km/L",
    "Round-trip option",
    "Cost split between passengers",
    "Compare with another car or an electric car",
    "Currency selector (USD, EUR, GBP, CAD, AUD), guessed from your location",
    "Calculation history with CSV export",
    "Copy a text summary",
    "Runs in your browser — nothing is uploaded",
  ],
  relatedTools: [
    "electric-motor-power-calculator",
    "air-conditioner-power-calculator",
    "discount-calculator",
    "average-calculator",
    "date-difference-calculator",
    "unit-ratio-calculator",
  ],
};
