export const drainageSystemCalculatorConfig = {
  name: "Drainage System Calculator",
  slug: "drainage-system-calculator",
  category: "land",
  description: "Calculate peak runoff flow, pipe drainage capacity, channel flow, and land drainage requirements instantly. Free online drainage system calculator for engineering, agriculture, and water management.",
  icon: "🌊",
  color: "#0ea5e9",
  featured: false,
  keywords: [
    "drainage system calculator",
    "land drainage calculator",
    "stormwater drainage calculator",
    "runoff flow calculator",
    "pipe drainage calculator",
    "water management tool",
    "drainage design calculator",
    "rational method calculator",
    "manning equation drainage",
    "peak runoff calculator",
  ],
  seo: {
    title: "Drainage System Calculator – Land Drainage Flow Design Tool",
    description: "Calculate drainage flow, runoff rate, pipe capacity, and land drainage requirements instantly. Free online drainage system calculator for engineering, agriculture, and water management.",
    keywords: "drainage system calculator, land drainage calculator, stormwater drainage calculator, runoff flow calculator, pipe drainage calculator, water management tool, drainage design calculator",
    og: {
      title: "Drainage System Calculator – Free Land Drainage Flow Design Tool",
      description: "Calculate peak runoff, pipe capacity, and drainage requirements instantly. Free engineering tool for civil engineers, agricultural planners, and land developers.",
      type: "website",
      url: "https://www.engineeringcalcs.com/tools/land/drainage-system-calculator",
    },
  },
  relatedTools: [
    "rainwater-runoff-calculator",
    "irrigation-water-calculator",
    "soil-volume-calculator",
    "land-slope-calculator",
    "well-depth-calculator",
    "water-table-depth-calculator",
  ],
};
