import { siteConfig } from "@/config/site";

export const drainageSystemCalculatorConfig = {
  name: "Drainage System Calculator",
  slug: "drainage-system-calculator",
  category: "land",
  description: "Calculate peak runoff flow, pipe drainage capacity, channel flow, and land drainage requirements instantly. Free online drainage system calculator for engineering, agriculture, and water management.",
  icon: "🌊",
  color: "#0ea5e9",
  featured: false,
  keywords: [
    "drainage system calculator",
    "land drainage calculator",
    "stormwater drainage calculator",
    "runoff flow calculator",
    "pipe drainage calculator",
    "water management tool",
    "drainage design calculator",
    "rational method calculator",
    "manning equation drainage",
    "peak runoff calculator",
  ],
  seo: {
    title: "Drainage Calculator – Runoff, Pipe & Channel Flow",
    description: "Estimate peak stormwater runoff with the Rational Method and check pipe and channel capacity with Manning's equation, with a pipe size suggestion.",
    keywords: "drainage system calculator, land drainage calculator, stormwater drainage calculator, runoff flow calculator, pipe drainage calculator, water management tool, drainage design calculator",
    og: {
      title: "Drainage Calculator – Runoff, Pipe & Channel Flow",
      description: "Estimate peak stormwater runoff with the Rational Method and check pipe and channel capacity with Manning's equation, with a pipe size suggestion.",
      type: "website",
      url: `${siteConfig.url}/tools/land/drainage-system-calculator`,
    },
    howToSteps: [
      { name: "Choose the calculation", text: "Select peak runoff, pipe capacity, channel flow, drainage area design or stormwater estimate." },
      { name: "Enter the area and rainfall", text: "Type the drainage area in m², hectares or acres, and the design rainfall intensity in mm/hr." },
      { name: "Set the runoff coefficient", text: "Use the slider or a surface button: about 0.9 for concrete, 0.2 for lawns." },
      { name: "Describe the pipe or channel", text: "Type the pipe diameter, material and slope, or the channel width and water depth." },
      { name: "Read the results", text: "See the peak flow in m³/s, L/s and cfs, the pipe or channel capacity, how full it runs, the overflow risk and a recommended pipe size." },
    ],
    faq: [
      { q: "What is the Rational Method?", a: "Q = C × I × A ÷ 360, with Q in m³/s, I in mm/hr and A in hectares. One hectare of pavement (C = 0.9) in 50 mm/hr rain gives 0.125 m³/s, or 125 L/s (4.4 cfs). It suits small catchments, up to about 80 ha (200 acres)." },
      { q: "How do I find the rainfall intensity?", a: "Use design storm data for your location and return period, such as NOAA Atlas 14 in the US or the Flood Estimation Handbook in the UK. If you have inches per hour, multiply by 25.4 to get mm/hr." },
      { q: "How is pipe capacity calculated?", a: "With Manning's equation for a pipe flowing full: Q = (1/n) × A × R^(2/3) × S^(1/2), where A is the pipe area, R the hydraulic radius (D/4) and S the slope." },
      { q: "What is Manning's n?", a: "A roughness coefficient: about 0.009 for PVC, 0.011 for HDPE, 0.013 for concrete and 0.015 for clay pipe. Smoother pipes carry more water at the same size and slope." },
      { q: "What pipe size should I use?", a: "The calculator suggests the smallest standard diameter that carries the peak flow at your slope. Check velocities and your local drainage standards before you build." },
      { q: "Can I use this for large watersheds?", a: "Not reliably. For large or mixed catchments use the NRCS curve number method or hydrologic modeling software." },
    ],
  },
  relatedTools: [
    "rainwater-runoff-calculator",
    "irrigation-water-calculator",
    "soil-volume-calculator",
    "land-slope-calculator",
    "well-depth-calculator",
    "water-table-depth-calculator",
  ],
};
