export const toolConfig = {
  slug: "color-palette-generator",
  name: "Color Palette Generator",
  description: "Generate harmony-based color palettes with locking, contrast checks, and export-ready formats",
  category: "design",
  icon: "🎨",
  free: true,
  backend: false,
  seo: {
    title: "Color Palette Generator – Harmony-Based Palettes",
    description: "Generate analogous, complementary, triadic, tetradic and monochrome palettes. Lock colors, check contrast and export CSS, SCSS, JSON or Tailwind.",
    keywords: [
      "color palette generator",
      "color scheme generator",
      "palette generator",
      "color harmony",
      "analogous colors",
      "complementary colors",
      "triadic colors",
      "monochromatic palette",
      "tetradic color palette",
      "random color palette generator",
      "brand color palette generator",
      "ui color palette generator",
      "web design color palette",
      "wcag contrast checker",
      "palette exporter",
      "css palette generator",
      "tailwind color palette generator",
      "free palette generator",
      "online color palette",
      "css color palette",
      "design color palette",
      "color theory tool",
      "palette export",
      "color accessibility"
    ],
    openGraph: {
      title: "Color Palette Generator – Harmony-Based Palettes",
      description: "Generate analogous, complementary, triadic, tetradic and monochrome palettes. Lock colors, check contrast and export CSS, SCSS, JSON or Tailwind.",
      type: "website",
      url: "/tools/design/color-palette-generator"
    },
    howToSteps: [
      { name: "Set a base color with HEX input or the color picker", text: "Set a base color with HEX input or the color picker." },
      { name: "Choose a palette type based on your design goal", text: "Choose a palette type based on your design goal." },
      { name: "Generate a 5-color palette instantly", text: "Generate a 5-color palette instantly." },
      { name: "Lock colors you want to keep and regenerate others", text: "Lock colors you want to keep and regenerate others." },
      { name: "Check contrast ratio for accessibility confidence", text: "Check contrast ratio for accessibility confidence." },
      { name: "Copy or export palette values for your design or code workflow", text: "Copy or export palette values for your design or code workflow." },
    ],
    faq: [
      { q: "What is a color palette generator?", a: "A color palette generator creates sets of colors that work well together using color harmony principles such as analogous, complementary, triadic, monochromatic, and tetradic schemes." },
      { q: "Why use a color palette generator instead of picking colors manually?", a: "It helps you avoid inconsistent combinations by generating balanced color relationships quickly, which is useful for UI design, branding, and frontend development." },
      { q: "Which palette modes are supported in this tool?", a: "This generator supports analogous, complementary, triadic, monochromatic, tetradic, and random palette modes." },
      { q: "Can I lock specific colors while regenerating a palette?", a: "Yes. You can lock individual swatches so fixed brand colors stay in place while other colors are regenerated." },
      { q: "Does this tool include accessibility checks?", a: "Yes. It includes contrast ratio checks and shows WCAG pass/fail guidance to support readable and accessible interfaces." },
      { q: "Can I export palettes for development workflows?", a: "Yes. You can export palette values as CSS variables, SCSS, JSON, and Tailwind-style formats for direct project usage." },
      { q: "Is gradient generation included?", a: "Yes. The tool provides gradient previews and copy-ready CSS gradient output from your generated palette." },
      { q: "Is this color palette generator free to use?", a: "Yes. The tool is free to use with no sign-up required." },
      { q: "Does this tool store my design data on a server?", a: "No. We do not collect or store what you enter." },
      { q: "Who benefits most from this palette generator?", a: "UI/UX designers, frontend developers, brand designers, students, and content creators can use it for quick and consistent color systems." },
    ],
  },
  features: [
    "Multiple color harmony algorithms",
    "Analogous, complementary, triadic palettes",
    "Monochromatic and tetradic schemes",
    "Random palette generation",
    "Lock individual colors",
    "Contrast ratio and WCAG accessibility checker",
    "Export to CSS/SCSS/JSON/Tailwind",
    "Gradient generator",
    "Copy entire palette and individual color values",
    "Private: your inputs are not collected or stored"
  ]
};
