export const torqueCalculatorConfig = {
  name: "Torque Calculator",
  slug: "torque-calculator",
  description: "Calculate torque instantly using force and distance. Supports Newtons, pounds-force, meters, feet, angle correction, and real-time results.",
  category: "mechanical",
  icon: "🔧",
  free: true,
  seo: {
    title: "Free Torque Calculator – Calculate Torque Online (Nm, lb-ft)",
    description: "Calculate torque instantly using force and distance. Supports Newtons, pounds-force, meters, feet, angle correction, and real-time results. Free online torque calculator.",
    keywords: [
      "torque calculator",
      "calculate torque online",
      "Nm calculator",
      "force and distance calculator",
      "lb-ft torque calculator",
      "mechanical torque formula",
      "engineering calculator",
      "torque formula",
      "moment of force calculator",
      "rotational force calculator",
      "torque unit converter",
      "bolt torque calculator",
    ],
    og: {
      title: "Free Torque Calculator – Calculate Torque Online (Nm, lb-ft)",
      description: "Calculate torque instantly using force and distance. Supports Newtons, pounds-force, meters, feet, angle correction, and real-time results.",
      url: "https://www.engineeringcalcs.com/tools/mechanical/torque-calculator",
    },
  },
  relatedTools: [
    "gear-ratio-calculator",
    "force-calculator",
    "angular-velocity-calculator",
    "spring-force-calculator",
    "shaft-torque-calculator",
    "centripetal-force-calculator",
  ],
};
