export const toolConfig = {
  slug: "loan-emi-calculator",
  name: "Loan & EMI Calculator",
  description: "Calculate EMI, total interest, full amortization schedule, compare loan options, and test extra monthly payments instantly.",
  category: "calculator",
  icon: "💰",
  free: true,
  backend: false,
  seo: {
    title: "Loan EMI Calculator - Monthly Payment, Interest & Amortization Schedule | Productive Toolbox",
    description: "Free Loan EMI Calculator with amortization schedule, loan comparison, and extra payment simulator. Estimate monthly EMI, total interest, and total repayment instantly.",
    keywords: [
      "emi calculator",
      "loan calculator",
      "loan emi calculator",
      "monthly emi calculator",
      "monthly loan payment calculator",
      "monthly payment calculator",
      "equated monthly installment calculator",
      "loan interest calculator",
      "loan repayment calculator",
      "loan repayment planner",
      "amortization calculator",
      "mortgage payment calculator",
      "mortgage emi calculator",
      "car loan calculator",
      "car loan emi calculator",
      "personal loan calculator",
      "personal loan emi calculator",
      "home loan emi calculator",
      "education loan emi calculator",
      "business loan calculator",
      "loan cost calculator",
      "loan tenure calculator",
      "loan affordability calculator",
      "emi schedule calculator",
      "amortization schedule",
      "amortization schedule generator",
      "principal and interest calculator",
      "loan prepayment calculator",
      "extra payment calculator",
      "interest saving calculator",
      "compare loans",
      "loan comparison calculator",
      "financial planning calculator",
      "free emi calculator online"
    ],
    openGraph: {
      title: "Loan EMI Calculator - Monthly EMI, Interest, and Schedule in One Tool",
      description: "Estimate EMI, compare loan offers, view complete amortization, and simulate extra monthly payment savings in seconds.",
      type: "website",
      url: "/tools/calculator/loan-emi-calculator"
    }
  },
  features: [
    "Instantly calculate Equated Monthly Installment (EMI)",
    "Generate full monthly amortization schedules safely client-side",
    "Toggle between local and generic currency formats",
    "Compare dual loan scenarios (Loan A vs Loan B)",
    "Simulate the massive impact of making extra monthly payments",
    "Visualize Total Principal vs Total Interest scales"
  ]
};
