export const stressCalculatorConfig = {
  name: "Stress Calculator",
  slug: "stress-calculator",
  description: "Calculate mechanical stress instantly using force and cross-sectional area (σ = F / A). Supports N, kN, lbf, kgf and m², cm², mm², in², ft² with real-time results.",
  category: "mechanical",
  icon: "🔩",
  free: true,
  seo: {
    title: "Free Stress Calculator Online – Calculate Mechanical Stress Instantly",
    description: "Calculate mechanical stress instantly using force and area. Free online stress calculator with engineering unit conversion for MPa, psi, Pa, ksi, and more.",
    keywords: [
      "stress calculator",
      "mechanical stress calculator",
      "stress formula calculator",
      "force and area calculator",
      "engineering stress calculator",
      "MPa calculator",
      "psi stress calculator",
      "normal stress calculator",
      "sigma calculator",
      "stress in materials",
      "structural stress calculator",
      "online stress calculator",
    ],
    og: {
      title: "Free Stress Calculator Online – Calculate Mechanical Stress Instantly",
      description: "Calculate mechanical stress instantly using force and area. Free online stress calculator with engineering unit conversion for MPa, psi, Pa, ksi, and more.",
      url: "https://www.engineeringcalcs.com/tools/mechanical/stress-calculator",
    },
  },
  relatedTools: [
    "torque-calculator",
    "force-calculator",
    "beam-deflection-calculator",
    "spring-force-calculator",
    "young-modulus-calculator",
    "factor-of-safety-calculator",
  ],
};
