export const findAndReplaceConfig = {
  name: "Find and Replace",
  slug: "find-and-replace",
  description: "Search and replace text with advanced options like regex and match case",
  category: "text",
  icon: "🔍",
  keywords: [
    "find and replace",
    "text search",
    "replace text",
    "text editor",
    "regex replace",
    "batch replace",
    "text manipulation",
    "find text",
    "search replace",
    "text tool",
    "word replacer",
    "pattern matching",
    "text processing",
    "bulk replace",
    "text finder",
    "string replace",
    "text modifier",
    "frontend text tool"
  ],
  seo: {
    title: "Find and Replace Online - Advanced Text Search and Replace Tool",
    description: "Free Find and Replace tool with regex support, batch replacements, preview mode, match-case controls, and file upload. Edit text faster and export results instantly.",
    keywords: [
      "find and replace",
      "text search",
      "replace text",
      "text editor",
      "regex replace",
      "batch replace",
      "text manipulation",
      "find text",
      "search replace",
      "text tool",
      "word replacer",
      "pattern matching",
      "text processing",
      "bulk replace",
      "text finder",
      "string replace",
      "text modifier",
      "frontend text tool",
      "find replace online",
      "regex find and replace",
      "batch text replacer",
      "search and replace tool",
      "replace all text",
      "whole word replace",
      "match case replace",
      "text replacement utility",
      "online text editor replace"
    ],
    openGraph: {
      title: "Find and Replace Tool - Regex, Batch, and Preview Replacement",
      description: "Search and replace text with advanced controls, preview mode, and file-based workflows.",
      type: "website",
      url: "/tools/writing/find-and-replace"
    }
  }
};
