export const columnBucklingCalculatorConfig = {
  name: "Column Buckling Calculator",
  slug: "column-buckling-calculator",
  description: "Calculate critical buckling load (Pcr) of structural columns using Euler's formula. Supports multiple end conditions, materials, unit systems, and safety factor analysis.",
  category: "mechanical",
  icon: "🏗️",
  free: true,
  seo: {
    title: "Column Buckling Calculator – Calculate Critical Buckling Load Online",
    description: "Free online column buckling calculator using Euler's formula. Compute critical buckling load (Pcr), choose end conditions (pinned, fixed, cantilever), compare materials, and get instant engineering results.",
    keywords: [
      "column buckling calculator",
      "euler buckling calculator",
      "critical buckling load calculator",
      "column load calculator",
      "mechanical engineering calculator",
      "structural buckling calculator",
      "steel column buckling",
      "euler formula calculator",
      "effective length factor",
      "slenderness ratio calculator",
      "pinned pinned column",
      "fixed fixed column buckling",
    ],
    og: {
      title: "Column Buckling Calculator – Calculate Critical Buckling Load Online",
      description: "Free online column buckling calculator using Euler's formula. Compute Pcr, choose end conditions, compare materials, and get instant engineering results.",
      url: "https://www.productivebox.com/tools/mechanical/column-buckling-calculator",
    },
  },
  relatedTools: [
    "beam-deflection-calculator",
    "stress-calculator",
    "moment-of-inertia-calculator",
    "bending-moment-calculator",
    "bolt-load-calculator",
    "torque-calculator",
  ],
};
