export const toolConfig = {
  slug: "currency-format-previewer",
  name: "Currency Format Previewer",
  description: "Preview how numbers appear in different global currencies and locales instantly.",
  category: "developer",
  icon: "💱",
  free: true,
  backend: false,
  seo: {
    title: "Currency Format Previewer – Intl Money Format by Locale",
    description: "Preview how amounts are formatted as money in any locale with Intl.NumberFormat: currency symbols, accounting style, decimals and grouping.",
    keywords: [
      "currency formatter",
      "currency format previewer",
      "currency formatting tool",
      "money format by locale",
      "price formatting tool",
      "intl numberformat currency",
      "intl numberformat tester",
      "javascript currency formatter",
      "javascript intl number format",
      "locale currency formatter",
      "locale number formatter",
      "global currency format",
      "multicurrency display format",
      "ecommerce price formatting",
      "accounting number format",
      "negative currency parentheses",
      "decimal separator locale",
      "thousand separator locale",
      "currency display symbol code name",
      "batch currency formatter",
      "currency formatting qa tool",
      "financial ui formatting",
      "localized pricing format",
      "iso currency display preview",
      "number formatting preview",
      "global currency styles"
    ],
    openGraph: {
      title: "Currency Format Previewer – Intl Money Format by Locale",
      description: "Preview how amounts are formatted as money in any locale with Intl.NumberFormat: currency symbols, accounting style, decimals and grouping.",
      type: "website",
      url: "/tools/currency-format-previewer"
    },
    faq: [
      { q: "Is this tool useful if I already have currency conversion elsewhere?", a: "Yes. Conversion and formatting solve different problems. Conversion changes numeric value between currencies, while formatting controls how that value is displayed to users. This tool is focused on display quality and localization accuracy." },
      { q: "Can I test multiple values quickly?", a: "Yes. Use the batch processor to paste one value per line and instantly get formatted results. This is ideal for QA checks, data cleanup, and validating large price lists." },
      { q: "Does it support accounting format for negative values?", a: "Yes. Enable accounting style to preview negative amounts with parentheses, which is common in billing systems, accounting interfaces, and financial statements." },
      { q: "Can I use this for localization testing in web apps?", a: "Absolutely. You can test locale codes, grouping, decimal precision, and currency presentation options before implementing them in production." },
      { q: "Why use Intl.NumberFormat instead of formatting by hand?", a: "Hand-written formatting with string replacements breaks on regional rules such as which separator groups thousands, where the symbol goes and how many decimals a currency uses. Intl.NumberFormat applies each locale's rules for you, and this tool shows the output so you can check it." },
      { q: "Why does the same amount look different in each locale?", a: "Each locale has its own conventions. 1234.5 euros is shown as €1,234.50 in en-US, 1.234,50 € in de-DE and 1 234,50 € in fr-FR, which uses a narrow space to group thousands." },
    ],
  },
  features: [
    "Preview major global currencies using Intl.NumberFormat",
    "Toggle between standard, accounting, and generic number styles",
    "Customize decimal precision and symbol/code display",
    "Test specific locale strings (e.g., de-DE, hi-IN, bn-BD)",
    "Generate ready-to-use JavaScript code snippets for developers",
    "Batch format multiple numeric values simultaneously"
  ]
};
