export const toolConfig = {
  slug: "gst-vat-calculator",
  name: "GST / VAT Calculator",
  description: "Add or remove tax from price instantly.",
  category: "calculator",
  icon: "🧾",
  free: true,
  backend: false,
  seo: {
    title: "GST / VAT Calculator - Add or Remove Tax from Price Instantly",
    description: "Free GST/VAT Calculator to add tax to base price or remove tax from tax-inclusive totals. Includes formulas, examples, FAQ, predefined rates, history, and CSV export.",
    keywords: [
      "gst calculator",
      "vat calculator",
      "tax calculator",
      "gst vat calculator",
      "add tax calculator",
      "remove tax calculator",
      "inclusive tax calculator",
      "exclusive tax calculator",
      "tax inclusive calculator",
      "tax exclusive calculator",
      "gst inclusive calculator",
      "vat inclusive calculator",
      "gst exclusive calculator",
      "vat exclusive calculator",
      "reverse tax calculator",
      "price including tax calculator",
      "price excluding tax calculator",
      "sales tax calculator",
      "gst percentage calculator",
      "vat percentage calculator",
      "gst vat calculator online",
      "tax inclusive price calculator",
      "tax exclusive price calculator",
      "goods and services tax calculator"
    ],
    openGraph: {
      title: "GST / VAT Calculator - Inclusive and Exclusive Tax Conversion",
      description: "Calculate GST/VAT quickly with add/remove tax modes, predefined rates, and export-ready outputs.",
      type: "website",
      url: "/tools/gst-vat-calculator"
    }
  },
  features: [
    "Calculate tax-inclusive prices (add tax)",
    "Calculate tax-exclusive prices (remove tax)",
    "Support for custom tax rates",
    "Predefined GST/VAT rates (5%, 12%, 18%, 28%)",
    "Real-time calculation as you type",
    "Decimal precision control",
    "Quick amount presets",
    "Copy results to clipboard",
    "Save calculation history in browser",
    "Export calculation to CSV",
    "Reload previous calculations from history",
    "Mobile-responsive design",
    "Save last calculation in browser",
    "SEO-rich content with formulas, examples, and FAQ"
  ]
};
