export const boltLoadCalculatorConfig = {
  name: "Bolt Load Calculator",
  slug: "bolt-load-calculator",
  description: "Calculate bolt preload force, clamp load, tensile stress, and safety factor instantly. Supports metric and imperial bolt grades with real-time results.",
  category: "mechanical",
  icon: "🔩",
  free: true,
  seo: {
    title: "Bolt Load Calculator – Free Online Bolt Preload & Stress Calculator",
    description: "Calculate bolt load, preload force, clamp load, tensile stress, and safety factor instantly. Supports metric grades (8.8, 10.9, 12.9) and imperial grades. Free online bolt load calculator.",
    keywords: [
      "bolt load calculator",
      "bolt preload calculator",
      "bolt force calculator",
      "tensile load calculator",
      "engineering bolt calculator",
      "mechanical engineering calculator",
      "fastener load calculator",
      "bolt stress calculator",
      "clamp load calculator",
      "bolt safety factor calculator",
      "bolt grade 8.8 calculator",
      "bolt tightening calculator",
      "preload force calculator",
      "bolt tensile stress",
      "ISO bolt calculator",
    ],
    og: {
      title: "Bolt Load Calculator – Free Online Bolt Preload & Stress Calculator",
      description: "Calculate bolt load, preload force, clamp load, tensile stress, and safety factor instantly. Supports metric and imperial bolt grades.",
      url: "https://www.engineeringcalcs.com/tools/mechanical/bolt-load-calculator",
    },
  },
  relatedTools: [
    "torque-calculator",
    "stress-calculator",
    "force-calculator",
    "thread-pitch-calculator",
    "factor-of-safety-calculator",
    "spring-force-calculator",
  ],
};
