import { siteConfig } from "@/config/site";

export const toolConfig = {
  slug: "age-calculator",
  name: "Age Calculator",
  description: "Calculate exact age from date of birth in years, months, and days. Get lifetime stats, next birthday countdown, milestones, zodiac info, and batch CSV export — free, no sign-up.",
  category: "calculator",
  icon: "🎂",
  free: true,
  backend: false,
  seo: {
    title: "Age Calculator — Free Online Age Calculator from Date of Birth | Productive Toolbox",
    description: "Free age calculator from date of birth. Get exact age in years, months, and days, total days lived, next birthday countdown, milestones, and zodiac sign. No sign-up, 100% browser-based.",
    keywords: [
      "age calculator",
      "age calculator online",
      "age calculator from date of birth",
      "calculate age online",
      "how old am i",
      "date of birth calculator",
      "exact age calculator",
      "age in years months days",
      "calculate age from birth date",
      "how many days have i lived",
      "days lived calculator",
      "next birthday countdown",
      "birthday calculator",
      "age calculator dob",
      "chronological age calculator",
      "age eligibility calculator",
      "batch age calculator",
      "age calculator with zodiac",
      "calculate age on specific date",
      "age calculator for kids",
      "how old will i be calculator",
      "age milestone calculator",
      "weeks lived calculator",
      "age difference calculator",
      "free age calculator no sign up",
    ],
    openGraph: {
      title: "Age Calculator — Free Online Age Calculator from Date of Birth",
      description: "Calculate exact age in years, months, and days. Get lifetime stats, birthday countdown, milestones, and zodiac sign. Free and browser-based.",
      type: "website",
      url: `${siteConfig.url}/tools/calculator/age-calculator`,
    },
    howToSteps: [
      { name: "Enter your date of birth", text: "Click the date of birth field and select your birth date from the date picker, or type it in MM/DD/YYYY format. The calculator accepts any date from 1900 to the present." },
      { name: "Set the comparison date", text: "By default the comparison date is today. Leave it as-is to calculate your current age, or change it to any past or future date to see your age at that specific point in time." },
      { name: "Read your exact age", text: "Your age appears instantly in years, months, and days. The result updates automatically whenever you change either date — no submit button needed." },
      { name: "Review lifetime statistics", text: "The Lifetime Stats panel shows your total months, weeks, days, hours, minutes, and seconds lived from birth to the comparison date. These numbers update in real time." },
      { name: "Check your next birthday", text: "The birthday countdown shows how many months and days remain until your next birthday, the total days left, and what day of the week your next birthday falls on." },
      { name: "Explore milestones and zodiac", text: "The milestones panel lists notable day and year milestones with their exact calendar dates, marking which ones you have already passed. Your Western and Chinese zodiac signs are shown based on your birth date." },
      { name: "Use batch mode for multiple people", text: "Switch to Batch mode, paste one birth date per line, and the calculator processes all entries simultaneously. Use the Export CSV button to download the results for school, HR, or admin use." },
    ],
    faq: [
      { q: "How do I calculate my exact age from date of birth?", a: "To calculate exact age, subtract the birth date from today's date accounting for actual calendar months and leap years — not just dividing total days by 365. This calculator handles all calendar edge cases automatically: leap year birthdays, months with different lengths, and historical dates." },
      { q: "How many days have I lived?", a: "Your total days lived equals the number of calendar days from your date of birth to today, including leap years. Someone exactly 30 years old has lived approximately 10,957 days. This calculator shows your exact days, weeks, months, hours, minutes, and seconds lived in the Lifetime Statistics panel." },
      { q: "What happens if I was born on February 29 (leap day)?", a: "People born on February 29 officially turn a year older on March 1 in non-leap years — the most common legal convention. In leap years, the birthday falls on February 29 as expected. The next birthday countdown and milestone dates all account for this correctly." },
      { q: "Can I calculate how old I will be on a future date?", a: "Yes. Change the comparison date field to any future date and the calculator immediately shows your exact age on that date, including years, months, and days. Useful for checking eligibility ages, planning milestone celebrations, or verifying age at a future event." },
      { q: "Can I calculate someone's age on a past date?", a: "Yes. Set the comparison date to any historical date to see exactly how old someone was at that point. Commonly used for legal document verification, historical event research, and genealogy work." },
      { q: "What is the 10,000 days milestone?", a: "The 10,000 days milestone falls at approximately 27 years and 4–5 months of age. Other notable milestones: 1,000 days (about 2 years 9 months), 5,000 days (about 13 years 8 months), 15,000 days (about 41 years), and 20,000 days (about 54 years 9 months). This calculator shows the exact date each milestone falls on." },
      { q: "What is chronological age?", a: "Chronological age is your actual age in calendar time — years, months, and days since birth. It is used for legal eligibility, medical dosing, educational enrollment, insurance tables, and statistical classification. This calculator computes chronological age precisely using calendar-aware date arithmetic." },
      { q: "What is batch age calculation?", a: "Batch mode lets you enter multiple dates of birth at once — one per line — and get all ages calculated simultaneously with an option to export as CSV. Useful for teachers, HR administrators, healthcare workers, and anyone regularly processing more than one date of birth." },
      { q: "How is the Western zodiac sign determined?", a: "Western astrology divides the year into 12 signs based on fixed date ranges. Aries begins around March 21, Taurus April 20, Gemini May 21, Cancer June 21, Leo July 23, Virgo August 23, Libra September 23, Scorpio October 23, Sagittarius November 22, Capricorn December 22, Aquarius January 20, and Pisces February 19." },
      { q: "Is my date of birth stored or shared?", a: "No. All calculations happen entirely in your browser using JavaScript. The dates you enter are never sent to any server, stored in a database, or shared with third parties. The optional history feature uses browser localStorage — data stays only on your device." },
    ],
  },
  features: [
    "Exact age in years, months, and days",
    "Full lifetime statistics: total days, weeks, hours, minutes, seconds",
    "Countdown to next birthday with weekday prediction",
    "Life milestones: 1,000 days, 10,000 days, major birthdays",
    "Western and Chinese zodiac sign",
    "Age at any past or future comparison date",
    "Batch mode for multiple DOBs with CSV export",
    "100% browser-based — no data sent to any server",
  ],
  relatedTools: [
    "date-difference-calculator",
    "bmi-calculator",
    "retirement-age-calculator",
    "days-until-calculator",
    "timestamp-unix-converter",
    "reading-time-calculator",
  ],
};
