import {
  ApparentPowerInputs,
  ApparentPowerResult,
  Preset,
  HistoryEntry
} from "./types";

const HISTORY_KEY = "apparent-power-calculator-history";
const MAX_HISTORY = 10;

/**
 * Calculate apparent power
 */
export function calculateApparentPower(inputs: ApparentPowerInputs): ApparentPowerResult {
  const { voltage, current } = inputs;
  
  // Calculate apparent power: S = V × I
  const apparentPower = voltage * current;
  
  // Generate step-by-step calculation
  const steps = [
    `Step 1: Identify the values`,
    `Voltage (V) = ${voltage} V`,
    `Current (I) = ${current} A`,
    ``,
    `Step 2: Apply the formula`,
    `Apparent Power (S) = Voltage × Current`,
    `S = V × I`,
    ``,
    `Step 3: Calculate`,
    `S = ${voltage} × ${current}`,
    `S = ${apparentPower} VA`,
    ``,
    `Result: ${apparentPower} VA`
  ];
  
  return {
    apparentPower,
    voltage,
    current,
    formula: "S = V × I",
    steps,
    timestamp: Date.now()
  };
}

/**
 * Validate inputs
 */
export function validateInputs(inputs: ApparentPowerInputs): string | null {
  const { voltage, current } = inputs;
  
  if (isNaN(voltage) || voltage <= 0) {
    return 'Voltage must be greater than 0';
  }
  
  if (isNaN(current) || current <= 0) {
    return 'Current must be greater than 0';
  }
  
  return null;
}

/**
 * Get preset configurations
 */
export function getPresets(): Preset[] {
  return [
    {
      name: 'Residential Circuit',
      description: 'Standard 230V household circuit',
      voltage: 230,
      current: 10
    },
    {
      name: 'US Residential',
      description: 'Standard 120V US circuit',
      voltage: 120,
      current: 15
    },
    {
      name: 'Industrial 3-Phase',
      description: 'Industrial 400V circuit',
      voltage: 400,
      current: 25
    },
    {
      name: 'Small Appliance',
      description: 'Low power device',
      voltage: 230,
      current: 2
    },
    {
      name: 'Heavy Load',
      description: 'High power industrial load',
      voltage: 480,
      current: 50
    },
    {
      name: 'Low Voltage DC',
      description: 'Battery powered device',
      voltage: 12,
      current: 5
    }
  ];
}

/**
 * Format number with decimals
 */
export function formatNumber(value: number, decimals: number = 2): string {
  return value.toFixed(decimals);
}

/**
 * Format power with appropriate unit
 */
export function formatPower(va: number): string {
  if (va >= 1000000) {
    return `${(va / 1000000).toFixed(2)} MVA`;
  } else if (va >= 1000) {
    return `${(va / 1000).toFixed(2)} kVA`;
  } else {
    return `${va.toFixed(2)} VA`;
  }
}

// History management
export function saveToHistory(inputs: ApparentPowerInputs, result: ApparentPowerResult): void {
  if (typeof window === 'undefined') return;
  
  const history = getHistory();
  const entry: HistoryEntry = {
    id: `${Date.now()}-${Math.random()}`,
    timestamp: Date.now(),
    input: inputs,
    result
  };
  
  history.unshift(entry);
  const trimmed = history.slice(0, MAX_HISTORY);
  
  try {
    localStorage.setItem(HISTORY_KEY, JSON.stringify(trimmed));
  } catch (e) {
    console.error('Failed to save history:', e);
  }
}

export function getHistory(): HistoryEntry[] {
  if (typeof window === 'undefined') return [];
  
  try {
    const stored = localStorage.getItem(HISTORY_KEY);
    return stored ? JSON.parse(stored) : [];
  } catch (e) {
    console.error('Failed to load history:', e);
    return [];
  }
}

export function clearHistory(): void {
  if (typeof window === 'undefined') return;
  
  try {
    localStorage.removeItem(HISTORY_KEY);
  } catch (e) {
    console.error('Failed to clear history:', e);
  }
}

// Export functions
export function exportToText(inputs: ApparentPowerInputs, result: ApparentPowerResult): string {
  const lines = [
    "APPARENT POWER CALCULATION",
    "=".repeat(50),
    "",
    `Date: ${new Date(result.timestamp).toLocaleString()}`,
    "",
    "INPUT VALUES:",
    "-".repeat(50),
    `Voltage (V): ${inputs.voltage} V`,
    `Current (I): ${inputs.current} A`,
    "",
    "CALCULATED RESULT:",
    "-".repeat(50),
    `Apparent Power (S): ${formatNumber(result.apparentPower, 2)} VA`,
    `Formatted: ${formatPower(result.apparentPower)}`,
    "",
    "FORMULA:",
    "-".repeat(50),
    result.formula,
    "",
    "CALCULATION STEPS:",
    "-".repeat(50)
  ];
  
  result.steps.forEach(step => lines.push(step));
  
  lines.push("");
  lines.push("=".repeat(50));
  lines.push("Generated by Apparent Power Calculator");
  
  return lines.join("\n");
}

export function downloadFile(content: string, filename: string, mimeType: string = 'text/plain'): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function debounce<T extends (...args: any[]) => any>(
  func: T,
  wait: number
): (...args: Parameters<T>) => void {
  let timeout: NodeJS.Timeout | null = null;
  
  return function executedFunction(...args: Parameters<T>) {
    const later = () => {
      timeout = null;
      func(...args);
    };
    
    if (timeout) {
      clearTimeout(timeout);
    }
    timeout = setTimeout(later, wait);
  };
}
