export const textToSlugConverterConfig = {
  id: 'text-to-slug-converter',
  slug: 'text-to-slug-converter',
  name: 'Text to Slug Converter',
  description: 'Convert text into SEO-friendly URL slugs instantly',
  category: 'writing',
  icon: '🔗',
  keywords: [
    'text to slug converter',
    'slug generator',
    'url slug',
    'seo url',
    'permalink generator',
    'url converter',
    'slugify text',
    'title to slug',
    'bulk slug converter',
    'url cleaner',
    'slug formatter',
    'remove stop words slug',
    'accent remover slug',
    'slug separator tool',
    'seo slug builder',
    'cms slug generator',
    'blog url slug tool',
    'free slug converter'
  ],
  seo: {
    title: 'Text to Slug Converter Online - Generate SEO-Friendly URLs in Bulk',
    description: 'Free Text to Slug Converter with real-time and bulk conversion, stop-word filtering, accent normalization, max-length control, and TXT/CSV export.',
    keywords: [
      'text to slug converter',
      'slug generator',
      'url slug',
      'seo url',
      'permalink generator',
      'url converter',
      'slugify text',
      'title to slug',
      'bulk slug converter',
      'url cleaner',
      'slug formatter',
      'remove stop words slug',
      'accent remover slug',
      'slug separator tool',
      'seo slug builder',
      'cms slug generator',
      'blog url slug tool',
      'free slug converter',
      'seo friendly slug generator',
      'bulk title to slug tool',
      'slug length checker',
      'hyphen underscore slug converter',
      'url slug optimizer',
      'online permalink creator'
    ],
    openGraph: {
      title: 'Text to Slug Converter - SEO-Ready URL Slug Generation Tool',
      description: 'Create clean URL slugs from titles with bulk conversion, formatting controls, and export options.',
      type: 'website',
      url: '/tools/writing/text-to-slug-converter',
    },
  },
};
