import { siteConfig } from "@/config/site";

export const pricePerSquareFeetCalculatorConfig = {
  name: "Price per Square Feet Calculator",
  slug: "price-per-square-feet-calculator",
  description: "Calculate land price per square foot or per square meter from total price and area. Supports Decimal, Acre, Katha, Bigha, Sq Meter, and Hectare with multi-currency output.",
  category: "land",
  icon: "📊",
  free: true,
  backend: false,
  seo: {
    title: "Price per Square Foot Calculator — Land Rate per Sq Ft | Productive Toolbox",
    description: "Calculate land price per square foot and per square meter from total price and area. Supports Decimal, Acre, Katha, Bigha, and Hectare. Free, no signup.",
    keywords: [
      "price per square foot calculator",
      "price per square feet calculator",
      "land price per square foot",
      "land price per square meter",
      "land rate per square feet",
      "land price calculator per square feet",
      "price per sq ft calculator",
      "calculate price per square foot",
      "land price per square meter calculator uk",
      "property price per square foot",
      "land rate calculator",
      "land value per square foot",
      "land price per sqft",
      "real estate price per sq ft",
      "price per square meter land",
      "land price per sq m",
      "calculate land rate per sqft",
      "decimal land price per sqft",
      "acre price per square foot",
      "katha price per sqft",
      "price per square foot land calculator free",
      "land cost per square foot calculator",
      "property value per square foot",
      "how to calculate price per square foot",
      "land price per square foot online",
    ],
    openGraph: {
      title: "Price per Square Foot Calculator — Land Rate per Sq Ft",
      description: "Calculate land price per square foot and per square meter from total price and area. Supports Decimal, Acre, Katha, Bigha, Hectare. Multi-currency.",
      type: "website",
      url: `${siteConfig.url}/tools/land/price-per-square-feet-calculator`,
    },
    og: {
      title: "Price per Square Foot Calculator — Land Rate per Sq Ft",
      description: "Calculate land price per square foot and per square meter from total price and area. Supports Decimal, Acre, Katha, Bigha, Hectare. Multi-currency.",
      url: `${siteConfig.url}/tools/land/price-per-square-feet-calculator`,
    },
    howToSteps: [
      { name: "Enter Total Land Price", text: "Type the full purchase or listing price of the land. Select your currency — USD, BDT, INR, EUR, or GBP. The result updates instantly." },
      { name: "Enter Land Area", text: "Type the land size as a number — for example, 2500, 3, or 0.5. You can enter whole numbers or decimals." },
      { name: "Select Area Unit", text: "Choose the unit matching your land measurement: Square Feet, Square Meter, Decimal, Acre, Katha, Bigha, or Hectare. The calculator converts to square feet automatically before dividing." },
      { name: "Read Price per Sq Ft and Sq Meter", text: "Both price-per-square-foot and price-per-square-meter are shown simultaneously. This covers US, UK, and international market conventions in one step." },
      { name: "Review the Breakdown Table", text: "The breakdown table shows the total price at 0.25×, 0.5×, 1×, 2×, 5×, and 10× your entered area — useful for comparing adjacent plot sizes at the same rate." },
      { name: "Save or Export", text: "Save the result to your local calculation history or download a TXT summary for documentation, client handoff, or property comparison files." },
    ],
    faq: [
      { q: "What is price per square foot?", a: "Price per square foot is the cost of one square foot of land area, calculated by dividing the total land price by the total area in square feet. It is the standard comparison metric in US and UK real estate because it normalizes price across plots of different sizes — a 500 sq ft plot at $200/sq ft and a 1,000 sq ft plot at $200/sq ft are at the same rate even though the total prices differ." },
      { q: "How do I calculate price per square foot?", a: "Price per square foot = Total Price ÷ Area in square feet. If the area is not in square feet, convert it first: 1 Decimal = 435.6 sq ft; 1 Acre = 43,560 sq ft; 1 Katha (Bangladesh) = 720 sq ft; 1 Square Meter = 10.764 sq ft. Enter the total price and area into this calculator and it applies the conversion automatically." },
      { q: "How do I calculate price per square meter?", a: "Price per square meter = Total Price ÷ Area in square meters. Or: Price per sq ft × 10.764 = Price per sq meter. This calculator outputs both per-square-foot and per-square-meter simultaneously, covering US/UK and international market conventions." },
      { q: "What is land price per square foot in Bangladesh?", a: "In Bangladesh, land is typically priced per Decimal or per Katha rather than per square foot, but conversion to sq ft is often needed for comparison or bank valuation. 1 Decimal = 435.6 sq ft; 1 Katha = 720 sq ft. If a plot is 5 Decimal at BDT 2,500,000, select Decimal, enter 5 and BDT 2,500,000 — the calculator returns BDT 1,147 per sq ft." },
      { q: "What is land price per square meter in the UK?", a: "UK land values vary enormously by region — from £100–£500/sq m in rural areas to £5,000–£50,000/sq m in central London. This calculator outputs price per square meter directly from any input unit, so you can compare UK listings (often in acres) with European listings (often in sq meters) on the same basis." },
      { q: "How many square feet in 1 Decimal?", a: "1 Decimal = 435.6 square feet. This is the fixed standard used in Bangladesh and eastern India. Multiply any Decimal area by 435.6 to get square feet, or enter Decimal directly into this calculator and it converts automatically." },
      { q: "How many square feet in 1 Katha?", a: "In Bangladesh, 1 Katha = 720 square feet. In Bihar, 1 Katha = 1,361.25 square feet. This calculator uses the Bangladesh/West Bengal standard. If you are working with Bihar land, note the different regional definition." },
      { q: "How many square feet in 1 Acre?", a: "1 Acre = 43,560 square feet. This is a fixed international standard. Enter Acre as the unit and the calculator converts to square feet before computing the per-sq-ft rate." },
      { q: "Can I compare two plots with different units?", a: "Yes. Run the calculation for each plot separately and compare the resulting price per square foot — that rate is unit-independent. A plot priced at $200/sq ft and another at $200/sq ft are the same rate regardless of whether one was measured in Decimal and the other in Acres." },
      { q: "Is my data private when using this calculator?", a: "Yes. All calculations run in your browser. Your price, area values, and currency are never sent to any server or stored outside your device." },
    ],
  },
  features: [
    "Price per square foot and per square meter output simultaneously",
    "Supports Sq Feet, Sq Meter, Decimal, Acre, Katha, Bigha, Hectare",
    "Multi-currency: USD, BDT, INR, EUR, GBP",
    "Price breakdown at 0.25×, 0.5×, 1×, 2×, 5×, 10× area",
    "Real-time calculation as you type",
    "Conversion reference table built in",
    "Calculation history saved to browser",
    "Export TXT summary",
    "100% browser-based — no data sent to server",
    "No registration required",
  ],
  relatedTools: [
    "land-price-calculator",
    "decimal-land-calculator",
    "land-area-calculator-square-meter",
    "acre-to-square-feet-converter",
    "land-valuation-calculator",
    "katha-land-calculator",
  ],
};
