import { siteConfig } from "@/config/site";

export const pricePerSquareFeetCalculatorConfig = {
  name: "Price per Square Feet Calculator",
  slug: "price-per-square-feet-calculator",
  description: "Calculate price per square foot or per square meter from the total price and area of a home, apartment or plot of land.",
  category: "land",
  icon: "📊",
  free: true,
  backend: false,
  seo: {
    title: "Price per Square Foot Calculator – Homes & Land",
    description: "Work out price per square foot and per square meter from the total price and area of a home, apartment or lot, in sq ft, m², acres or hectares.",
    keywords: [
      "price per square foot calculator",
      "price per square feet calculator",
      "price per sq ft calculator",
      "price per square meter calculator",
      "house price per square foot",
      "land price per square foot",
      "cost per square foot calculator",
      "property price per square foot",
      "real estate price per sq ft",
      "how to calculate price per square foot",
    ],
    openGraph: {
      title: "Price per Square Foot Calculator – Homes & Land",
      description: "Work out price per square foot and per square meter from the total price and area of a home, apartment or lot, in sq ft, m², acres or hectares.",
      type: "website",
      url: `${siteConfig.url}/tools/land/price-per-square-feet-calculator`,
    },
    howToSteps: [
      { name: "Enter the total price", text: "Type the sale or asking price of the home, apartment or land, and pick USD, EUR, GBP, CAD or AUD." },
      { name: "Enter the area", text: "Type the size and choose its unit: square feet, square meters, acres or hectares (Decimal, Katha and Bigha are also available)." },
      { name: "Read the price per unit", text: "See the price per square foot and per square meter together, so US and metric listings can be compared." },
      { name: "Check the breakdown", text: "The table shows the price at 0.25×, 0.5×, 1×, 2×, 5× and 10× the area at the same rate." },
      { name: "Save or export", text: "Keep the result in your history or download a text summary." },
    ],
    faq: [
      { q: "How do you calculate price per square foot?", a: "Divide the price by the area in square feet. A $450,000 house with 2,000 sq ft of living space costs $225 per square foot. For land, use the lot area: a 0.25 acre (10,890 sq ft) lot at $120,000 is $11.02 per sq ft." },
      { q: "How do I convert price per square foot to price per square meter?", a: "Multiply by 10.764. $225 per sq ft is $2,422 per m²; €4,000 per m² is €372 per sq ft." },
      { q: "What square footage should I use for a house?", a: "In the US, the finished, heated living area measured to ANSI Z765, which excludes garages and unfinished basements. In the UK and Europe, prices per m² usually use the gross internal area. Use the same basis for every property you compare." },
      { q: "Is a lower price per square foot always a better deal?", a: "No. Larger homes and lots usually have a lower price per square foot than small ones, and location, condition, age and lot size all change the value. Compare properties of similar size in the same area." },
      { q: "What is a typical price per square foot?", a: "It varies widely by market: US home prices range from under $150 per sq ft in many Midwestern cities to over $1,000 in Manhattan and San Francisco. In Europe, prices per m² range from about €2,000 in smaller cities to over €10,000 in central Paris and London (about £11,000)." },
      { q: "Which units and currencies are supported?", a: "Square feet, square meters, acres, hectares, Decimal, Katha and Bigha, with prices in US dollars, euros, pounds, Canadian or Australian dollars. The total is always in the currency you enter." },
      { q: "Is my data private?", a: "Yes. We do not collect or store what you enter." },
    ],
  },
  features: [
    "Price per square foot and per square meter output simultaneously",
    "Supports sq ft, m², acres, hectares, Decimal, Katha and Bigha",
    "Currencies: USD, EUR, GBP, CAD, AUD",
    "Price breakdown at 0.25×, 0.5×, 1×, 2×, 5×, 10× area",
    "Real-time calculation as you type",
    "Conversion reference table built in",
    "Calculation history saved to browser",
    "Export TXT summary",
    "Private: your inputs are not collected or stored",
    "No registration required",
  ],
  relatedTools: [
    "land-price-calculator",
    "square-feet-to-acre-converter",
    "land-area-calculator-square-meter",
    "acre-to-square-feet-converter",
    "land-valuation-calculator",
    "subdivision-cost-calculator",
  ],
};
