export const goldenRatioCalculatorConfig = {
  slug: "golden-ratio-calculator",
  name: "Golden Ratio Calculator",
  description: "Calculate perfect proportions using φ (1.618) for design and layout",
  category: "design",
  icon: "✨",
  free: true,
  backend: false,
  seo: {
    title: "Golden Ratio Calculator – Split Values Using 1.618",
    description: "Calculate golden ratio proportions instantly. Split numbers into 61.8% and 38.2%, generate golden layouts, typography scales, and responsive CSS.",
    keywords: [
      "golden ratio calculator",
      "phi calculator",
      "1.618 calculator",
      "golden ratio design",
      "golden section calculator",
      "fibonacci calculator",
      "golden ratio layout",
      "typography scale generator",
      "golden spiral",
      "design proportions",
      "golden ratio css",
      "phi design tool",
      "golden mean calculator",
      "divine proportion",
      "free golden ratio tool"
    ],
    openGraph: {
      title: "Golden Ratio Calculator – Split Values Using 1.618",
      description: "Calculate perfect proportions using the golden ratio for design, typography, and layouts.",
      type: "website",
      url: "/golden-ratio-calculator"
    },
    faq: [
      { q: "Is the golden ratio really more pleasing to the eye?", a: "It is widely used in design because 1:1.618 gives a balanced but non-symmetric split, and it is easy to repeat at every scale. Claims that people are naturally drawn to it are weaker than often stated: studies of preferences for golden rectangles have produced mixed results." },
      { q: "Should I use golden ratio for all my designs?", a: "No. The golden ratio is a helpful guideline, not a strict rule. Use it where it makes sense, but prioritize usability, accessibility, and your specific design requirements." },
      { q: "How do I apply golden ratio to responsive design?", a: "Use CSS Grid with fr units (1.618fr and 1fr) or Flexbox with flex values. These scale proportionally across different screen sizes while maintaining the golden ratio." },
      { q: "Can I use golden ratio for mobile layouts?", a: "Yes, but consider stacking elements vertically on mobile instead of side-by-side. Apply golden ratio to vertical spacing, typography scales, and component sizing." },
      { q: "What's the difference between the golden ratio and the rule of thirds?", a: "The rule of thirds places guide lines at 33.3% and 66.7% of the frame; the golden ratio places them at 38.2% and 61.8%. The golden ratio lines sit closer to the center, which gives a slightly tighter composition." },
    ],
  },
  features: [
    "Forward and reverse calculations",
    "Support for px, %, and numbers",
    "Golden spiral visualization",
    "Golden rectangle preview",
    "Typography scale generator",
    "Spacing system generator",
    "Layout split calculator",
    "CSS Grid code generation",
    "Flexbox code generation",
    "Percentage-based layouts",
    "Pixel-based layouts",
    "Visual layout preview",
    "Copy to clipboard",
    "Export as JSON or TXT",
    "Common value presets",
    "100% client-side processing"
  ]
};
