/* Tools kept live but excluded from Google's index — the #22 catalogue triage
   (GSC export 2026-09-24, web, last 6 months): each had zero impressions.
   64 were created on 1–2 August and never earned one; 54 older tools earned
   none in 3–6 months.

   Listed tools get <meta name="robots" content="noindex, follow">, are left
   out of the sitemap and are not offered as related tools. They still load,
   and stay in site search and category grids for visitors.

   Reversible: delete a slug to put it back in the index. Kept as a plain slug
   list because RelatedTools ships it to the browser. */
export const NOINDEX_TOOLS: ReadonlySet<string> = new Set([
  "a-b-test-calculator",
  "ad-frequency-calculator",
  "ad-spend-calculator",
  "ascii-art-generator",
  "backlink-ratio-calculator",
  "bar-graph-generator",
  "beam-deflection-calculator",
  "bearing-life-calculator",
  "bending-moment-calculator",
  "big-data-throughput-calculator",
  "binary-hex-decimal-converter",
  "binary-to-decimal-calculator",
  "bolt-load-calculator",
  "bounce-rate-calculator",
  "cache-efficiency-calculator",
  "centimeter-to-meter-converter",
  "chi-square-calculator",
  "churn-rate-calculator",
  "click-heatmap-density-calculator",
  "cluster-utilization-calculator",
  "clustering-distance-calculator",
  "column-buckling-calculator",
  "confidence-interval-calculator",
  "correlation-coefficient-calculator",
  "cpm-calculator",
  "css-flexbox-playground",
  "css-triangle-generator",
  "cutting-speed-calculator",
  "data-compression-ratio-calculator",
  "data-growth-calculator",
  "data-normalization-calculator",
  "data-partition-calculator",
  "data-pipeline-latency-calculator",
  "data-sampling-calculator",
  "data-transfer-cost-calculator",
  "decimal-to-binary-calculator",
  "dithering-filter",
  "domain-authority-estimator",
  "email-click-rate-calculator",
  "email-open-rate-calculator",
  "encoding-efficiency-calculator",
  "engagement-rate-calculator",
  "etl-throughput-calculator",
  "exponential-smoothing-calculator",
  "fatigue-life-calculator",
  "feed-rate-calculator",
  "font-pairer",
  "green-building-score-calculator",
  "habit-tracker",
  "hadoop-storage-calculator",
  "histogram-bin-calculator",
  "ideal-gas-law-calculator",
  "impressions-calculator",
  "index-size-calculator",
  "irrigation-water-calculator",
  "keyword-difficulty-estimator",
  "kinetic-energy-calculator",
  "land-leveling-calculator",
  "lathe-speed-calculator",
  "lead-conversion-funnel-calculator",
  "live-load-calculator",
  "log-transformation-calculator",
  "mach-number-calculator",
  "marketing-roi-calculator",
  "mean-calculator",
  "median-calculator",
  "min-max-scaling-calculator",
  "mode-calculator",
  "moving-average-calculator",
  "nato-phonetic-converter",
  "organic-vs-paid-ratio-calculator",
  "outlier-detection-calculator",
  "p-value-calculator",
  "page-rank-estimator",
  "page-speed-score-calculator",
  "percentile-calculator",
  "pixel-art-grid",
  "placeholder-image-generator",
  "pressure-drop-calculator",
  "property-appreciation-calculator",
  "query-optimization-calculator",
  "rafter-length-calculator",
  "refrigeration-cop-calculator",
  "regex-tester",
  "regression-calculator",
  "retention-rate-calculator",
  "roc-auc-calculator",
  "roman-numeral-converter",
  "sample-size-calculator",
  "screen-resolution-checker",
  "scroll-depth-calculator",
  "seasonality-index-calculator",
  "serp-ctr-estimator",
  "session-duration-calculator",
  "social-media-post-preview",
  "social-media-reach-calculator",
  "spark-job-time-calculator",
  "specific-heat-calculator",
  "sql-formatter",
  "step-rise-run-calculator",
  "storage-requirement-calculator",
  "svg-pattern-generator",
  "text-to-speech-preview",
  "thread-pitch-calculator",
  "time-series-forecast-calculator",
  "tip-calculator",
  "torque-calculator",
  "traffic-growth-calculator",
  "user-growth-rate-calculator",
  "variance-calculator",
  "velocity-calculator",
  "video-frame-extractor",
  "viral-coefficient-calculator",
  "z-score-calculator",
  "zalgo-text-generator",
]);
