/* Hand-picked related tools, keyed by tool slug. Tools in the same family
   (config/tool-nav.ts) always come first; these follow, then the rest is
   filled from the tool's category. Moved here from each tool's ui.tsx so the
   side rail, the chips under the tool and the grid at the bottom all read
   one list. */
export const RELATED_PICKS: Readonly<Record<string, readonly string[]>> = {
  "3d-volume-calculator-architecture": ["room-volume-calculator", "concrete-volume-calculator", "room-area-calculator"],
  "a-b-test-calculator": ["sample-size-calculator", "p-value-calculator", "chi-square-calculator", "confidence-interval-calculator", "standard-deviation-calculator", "z-score-calculator"],
  "acceleration-calculator": ["velocity-calculator", "force-calculator", "kinetic-energy-calculator", "torque-calculator", "centripetal-force-calculator", "projectile-motion-calculator"],
  "acoustic-soundproofing-calculator": ["heat-loss-calculator-building", "insulation-thickness-calculator", "ventilation-calculator"],
  "acre-to-hectare-converter": ["hectare-to-acre-converter", "acre-to-square-feet-converter", "square-feet-to-acre-converter", "land-area-calculator-square-meter"],
  "acre-to-square-feet-converter": ["square-feet-to-acre-converter", "land-area-calculator-square-feet", "land-area-calculator-square-meter", "square-meter-to-square-foot-converter"],
  "ad-frequency-calculator": ["impressions-calculator", "social-media-reach-calculator", "ctr-calculator", "cpm-calculator", "cost-per-click-cpc-calculator", "engagement-rate-calculator"],
  "ad-spend-calculator": ["cpm-calculator", "cost-per-click-cpc-calculator", "cost-per-acquisition-cpa-calculator", "marketing-roi-calculator", "break-even-calculator"],
  "adc-resolution-calculator": ["dac-output-calculator", "logic-gate-calculator"],
  "age-calculator": ["date-difference-calculator", "time-duration-calculator", "bmi-calculator"],
  "ai-prompt-length-calculator": ["ai-token-cost-calculator", "download-time-calculator", "time-complexity-calculator", "latency-calculator", "data-transfer-calculator", "bandwidth-calculator"],
  "ai-token-cost-calculator": ["ai-prompt-length-calculator", "download-time-calculator", "data-transfer-calculator", "time-complexity-calculator", "latency-calculator", "bandwidth-calculator"],
  "air-change-rate-calculator": ["ventilation-calculator", "hvac-load-calculator", "room-volume-calculator"],
  "air-conditioner-power-calculator": ["fan-power-consumption-calculator", "energy-consumption-calculator", "electric-bill-calculator"],
  "amplifier-gain-calculator": ["impedance-calculator", "power-factor-calculator", "voltage-divider-calculator"],
  "anagram-finder": ["word-frequency-counter", "text-reverser", "find-and-replace"],
  "angular-velocity-calculator": ["torque-calculator", "centripetal-force-calculator", "gear-ratio-calculator", "velocity-calculator"],
  "antenna-length-calculator": ["clock-frequency-calculator", "data-rate-calculator", "impedance-calculator", "capacitive-reactance-calculator"],
  "apparent-power-calculator": ["real-power-calculator", "power-factor-calculator", "voltage-divider-calculator"],
  "arc-flash-calculator": ["power-loss-calculator", "short-circuit-current-calculator", "ground-fault-current-calculator", "electrical-efficiency-calculator"],
  "ascii-art-generator": ["qr-code-generator", "placeholder-image-generator", "color-palette-generator"],
  "aspect-ratio-calculator": ["image-resizer", "image-compressor", "css-gradient-generator"],
  "audio-visualizer": ["video-frame-extractor", "text-to-speech-preview"],
  "average-calculator": ["standard-deviation-calculator", "percentage-calculator"],
  "backlink-ratio-calculator": ["keyword-density-checker", "seo-score-calculator", "ctr-calculator", "conversion-rate-calculator", "bounce-rate-calculator", "cost-per-click-cpc-calculator"],
  "bandwidth-calculator": ["cidr-calculator", "subnet-calculator", "ip-range-calculator", "download-time-calculator", "data-transfer-calculator", "latency-calculator"],
  "bar-graph-generator": ["word-cloud-generator", "mind-map-builder", "pie-chart-maker"],
  "base32-encoder": ["base64-encoder-decoder", "text-encrypt-decrypt", "hash-generator"],
  "base64-encoder-decoder": ["text-encrypt-decrypt", "hash-generator", "url-encoder-decoder"],
  "base64-image-encoder": ["image-compressor", "image-resizer", "text-to-clipboard"],
  "battery-backup-time-calculator": ["battery-capacity-calculator", "energy-consumption-calculator", "power-calculator-electrical", "voltage-divider-calculator"],
  "battery-capacity-calculator": ["battery-backup-time-calculator", "battery-charging-time-calculator", "energy-consumption-calculator", "solar-battery-calculator"],
  "battery-charging-time-calculator": ["battery-capacity-calculator", "battery-backup-time-calculator", "energy-consumption-calculator", "power-calculator-electrical"],
  "bcrypt-hash-verifier": ["text-encryptor-aes", "password-generator", "hash-generator"],
  "beam-deflection-calculator": ["beam-load-calculator", "torque-calculator", "force-calculator", "spring-force-calculator"],
  "beam-load-calculator": ["foundation-depth-calculator", "concrete-volume-calculator", "steel-quantity-calculator"],
  "bearing-life-calculator": ["torque-calculator", "gear-ratio-calculator", "spring-force-calculator", "angular-velocity-calculator", "natural-frequency-calculator", "centripetal-force-calculator"],
  "bending-moment-calculator": ["beam-deflection-calculator", "stress-calculator", "torque-calculator", "moment-of-inertia-calculator", "force-calculator", "spring-force-calculator"],
  "bernoulli-equation-calculator": ["reynolds-number-calculator", "pressure-drop-calculator", "flow-rate-calculator", "hydraulic-pressure-calculator"],
  "big-data-throughput-calculator": ["cluster-utilization-calculator", "spark-job-time-calculator", "data-compression-ratio-calculator", "encoding-efficiency-calculator", "data-partition-calculator", "time-series-forecast-calculator"],
  "bigha-land-calculator": ["katha-land-calculator", "land-area-calculator-square-feet", "acre-to-square-feet-converter", "hectare-to-acre-converter"],
  "binary-hex-decimal-converter": ["base64-encoder-decoder", "hash-generator", "timestamp-unix-converter"],
  "binary-to-decimal-calculator": ["logic-gate-calculator", "adc-resolution-calculator"],
  "bionic-reading-converter": [],
  "bmi-calculator": ["age-calculator"],
  "bmr-calculator": ["bmi-calculator"],
  "body-fat-calculator": ["bmi-calculator", "bmr-calculator", "ideal-weight-calculator"],
  "bolt-load-calculator": ["torque-calculator", "stress-calculator", "force-calculator", "spring-force-calculator", "friction-force-calculator"],
  "bounce-rate-calculator": ["ctr-calculator", "conversion-rate-calculator", "percentage-calculator", "investment-return-calculator"],
  "boundary-length-calculator": ["plot-division-calculator", "land-area-calculator-square-feet", "fence-material-calculator", "land-price-calculator"],
  "break-even-calculator": ["profit-margin-calculator-marketing", "revenue-growth-calculator", "cost-per-acquisition-cpa-calculator", "customer-lifetime-value-calculator", "investment-return-calculator"],
  "brick-calculator": ["wall-area-calculator", "tile-quantity-calculator", "paint-required-calculator"],
  "building-height-calculator": ["floor-area-calculator", "plot-area-calculator", "room-volume-calculator"],
  "cable-length-calculator": ["wire-size-calculator", "voltage-drop-calculator", "circuit-breaker-calculator"],
  "cache-efficiency-calculator": ["index-size-calculator", "cluster-utilization-calculator", "big-data-throughput-calculator", "etl-throughput-calculator", "data-pipeline-latency-calculator", "storage-requirement-calculator"],
  "capacitive-reactance-calculator": ["inductive-reactance-calculator", "capacitor-calculator", "impedance-calculator"],
  "capacitor-calculator": ["ohms-law-calculator", "voltage-divider-calculator", "energy-consumption-calculator"],
  "capacitor-charge-time-calculator": ["capacitor-calculator", "series-resistor-calculator", "ohms-law-calculator"],
  "carbon-footprint-calculator-construction": ["green-building-score-calculator", "energy-efficiency-calculator-building", "sustainability-index-calculator"],
  "cement-calculator": ["brick-calculator", "tile-quantity-calculator", "wall-area-calculator"],
  "celsius-to-fahrenheit-converter": ["temperature-conversion-scientific", "inch-to-cm-converter", "meter-to-km-converter", "square-meter-to-square-foot-converter"],
  "centimeter-to-meter-converter": ["temperature-conversion-scientific", "unit-ratio-calculator"],
  "centripetal-force-calculator": ["force-calculator", "torque-calculator", "angular-velocity-calculator", "kinetic-energy-calculator", "spring-force-calculator", "velocity-calculator"],
  "checksum-calculator": ["subnet-calculator", "file-hash-generator", "hash-generator", "ip-range-calculator", "text-encrypt-decrypt", "bandwidth-calculator"],
  "chi-square-calculator": ["p-value-calculator", "a-b-test-calculator", "sample-size-calculator", "correlation-coefficient-calculator", "standard-deviation-calculator", "confidence-interval-calculator"],
  "churn-rate-calculator": ["retention-rate-calculator", "customer-lifetime-value-calculator", "marketing-roi-calculator", "break-even-calculator", "ad-spend-calculator"],
  "cidr-calculator": ["subnet-calculator", "ip-range-calculator", "bandwidth-calculator", "checksum-calculator", "ip-address-masker", "download-time-calculator"],
  "circuit-breaker-calculator": ["voltage-drop-calculator", "wire-size-calculator", "power-consumption-calculator"],
  "cladding-material-calculator": ["facade-area-calculator", "wall-area-calculator", "paint-required-calculator"],
  "click-heatmap-density-calculator": ["scroll-depth-calculator", "session-duration-calculator", "page-speed-score-calculator", "bounce-rate-calculator", "conversion-rate-calculator", "engagement-rate-calculator"],
  "clock-frequency-calculator": ["capacitor-charge-time-calculator", "inductor-calculator", "impedance-calculator", "capacitive-reactance-calculator"],
  "cloud-cost-calculator": ["ai-token-cost-calculator", "download-time-calculator", "latency-calculator", "bandwidth-calculator", "data-transfer-calculator", "time-complexity-calculator"],
  "cluster-utilization-calculator": ["big-data-throughput-calculator", "spark-job-time-calculator", "data-compression-ratio-calculator", "encoding-efficiency-calculator", "data-partition-calculator", "time-series-forecast-calculator"],
  "clustering-distance-calculator": ["correlation-coefficient-calculator", "standard-deviation-calculator", "roc-auc-calculator", "confusion-matrix-calculator", "regression-calculator", "outlier-detection-calculator"],
  "color-blindness-simulator": ["contrast-checker", "color-palette-contrast-grid", "color-palette-generator"],
  "color-format-converter": ["hex-to-rgb-converter", "color-palette-generator", "css-gradient-generator"],
  "color-palette-contrast-grid": ["contrast-checker", "color-palette-generator", "hsl-color-slider"],
  "color-palette-extractor": ["color-palette-generator", "hex-to-rgb-converter", "contrast-checker"],
  "color-palette-generator": ["hex-to-rgb-converter", "duotone-filter"],
  "column-buckling-calculator": ["beam-deflection-calculator", "stress-calculator", "moment-of-inertia-calculator", "bending-moment-calculator", "bolt-load-calculator", "torque-calculator"],
  "column-load-calculator": ["beam-load-calculator", "foundation-depth-calculator", "concrete-volume-calculator"],
  "combinatorics-calculator": ["model-accuracy-calculator", "dataset-split-calculator", "f1-score-calculator", "time-complexity-calculator", "standard-deviation-calculator"],
  "compound-interest-calculator": ["simple-interest-calculator", "mortgage-calculator", "loan-calculator"],
  "concrete-mix-ratio-calculator": ["cement-calculator", "sand-calculator", "brick-calculator"],
  "concrete-volume-calculator": ["concrete-mix-ratio-calculator", "cement-calculator", "sand-calculator"],
  "confidence-interval-calculator": ["z-score-calculator", "standard-deviation-calculator", "p-value-calculator", "sample-size-calculator", "correlation-coefficient-calculator", "mean-calculator"],
  "confusion-matrix-calculator": ["precision-recall-calculator", "f1-score-calculator", "model-accuracy-calculator", "ai-token-cost-calculator", "ai-prompt-length-calculator", "time-complexity-calculator"],
  "construction-cost-estimator": ["escalation-cost-calculator", "concrete-volume-calculator", "brick-calculator"],
  "contrast-checker": ["color-format-converter", "css-gradient-generator", "color-palette-generator"],
  "conversion-rate-calculator": ["ctr-calculator", "percentage-calculator", "investment-return-calculator", "gst-vat-calculator"],
  "cooling-load-calculator-architecture": ["hvac-load-calculator", "ventilation-calculator", "air-change-rate-calculator"],
  "correlation-coefficient-calculator": ["mean-calculator", "median-calculator", "standard-deviation-calculator", "regression-calculator", "data-growth-calculator", "session-duration-calculator"],
  "cost-per-acquisition-cpa-calculator": ["cost-per-click-cpc-calculator", "ctr-calculator", "conversion-rate-calculator", "bounce-rate-calculator", "investment-return-calculator"],
  "cost-per-click-cpc-calculator": ["ctr-calculator", "conversion-rate-calculator", "bounce-rate-calculator", "investment-return-calculator", "percentage-calculator"],
  "cpm-calculator": ["cost-per-click-cpc-calculator", "cost-per-acquisition-cpa-calculator", "impressions-calculator", "ad-frequency-calculator", "ctr-calculator"],
  "cron-expression-generator": ["timestamp-unix-converter", "time-zone-converter"],
  "css-animation-previewer": ["css-filter-tester", "css-gradient-generator", "css-box-shadow-generator"],
  "css-border-radius-blob": ["css-gradient-generator", "css-box-shadow-generator", "neumorphism-generator"],
  "css-box-shadow-generator": ["css-gradient-generator", "color-palette-generator", "hex-to-rgb-converter"],
  "css-button-generator": ["css-box-shadow-generator", "css-gradient-generator", "color-palette-generator"],
  "css-clamp-generator": ["css-gradient-generator", "neumorphism-generator", "css-animation-previewer"],
  "css-cursor-style-previewer": ["css-filter-tester", "css-animation-previewer", "neumorphism-generator"],
  "css-filter-tester": ["css-animation-previewer", "css-gradient-generator", "css-box-shadow-generator"],
  "css-flexbox-playground": ["css-gradient-generator", "css-box-shadow-generator", "css-animation-previewer"],
  "css-glassmorphism-generator": ["css-gradient-generator", "css-box-shadow-generator", "color-format-converter"],
  "css-gradient-generator": ["color-palette-generator", "hex-to-rgb-converter", "duotone-filter"],
  "css-keyframe-animator": ["css-animation-previewer", "css-gradient-generator", "css-box-shadow-generator"],
  "css-mesh-gradient-generator": ["css-gradient-generator", "gradient-text-generator", "random-hex-color-generator"],
  "css-triangle-generator": ["css-box-shadow-generator", "css-gradient-generator", "color-format-converter"],
  "csv-to-json-converter": ["json-to-csv", "json-formatter", "json-validator"],
  "ctr-calculator": ["cost-per-click-cpc-calculator", "cost-per-acquisition-cpa-calculator", "conversion-rate-calculator", "keyword-density-checker", "profit-margin-calculator-marketing"],
  "currency-format-previewer": ["percentage-calculator"],
  "current-divider-calculator": ["voltage-divider-calculator", "parallel-resistor-calculator", "ohms-law-calculator", "power-calculator-electrical"],
  "curtain-wall-calculator": ["facade-area-calculator", "glass-panel-size-calculator", "cladding-material-calculator"],
  "custom-scrollbar-styler": ["css-gradient-generator", "css-box-shadow-generator", "neumorphism-generator"],
  "customer-lifetime-value-calculator": ["cost-per-acquisition-cpa-calculator", "cost-per-click-cpc-calculator", "conversion-rate-calculator", "ctr-calculator", "investment-return-calculator"],
  "cutting-speed-calculator": ["torque-calculator", "gear-ratio-calculator", "angular-velocity-calculator", "force-calculator", "reynolds-number-calculator", "flow-rate-calculator"],
  "dac-output-calculator": ["adc-resolution-calculator", "pwm-duty-cycle-calculator"],
  "daily-calorie-calculator": ["bmr-calculator", "bmi-calculator", "body-fat-calculator"],
  "data-compression-ratio-calculator": ["storage-requirement-calculator", "data-transfer-cost-calculator", "encoding-efficiency-calculator", "data-growth-calculator", "hadoop-storage-calculator", "data-pipeline-latency-calculator"],
  "data-growth-calculator": ["user-growth-rate-calculator", "traffic-growth-calculator", "session-duration-calculator", "page-speed-score-calculator", "scroll-depth-calculator", "revenue-growth-calculator"],
  "data-normalization-calculator": ["min-max-scaling-calculator", "log-transformation-calculator", "standard-deviation-calculator", "z-score-calculator", "mean-calculator", "variance-calculator"],
  "data-partition-calculator": ["hadoop-storage-calculator", "storage-requirement-calculator", "cluster-utilization-calculator", "big-data-throughput-calculator", "data-pipeline-latency-calculator", "etl-throughput-calculator"],
  "data-pipeline-latency-calculator": ["latency-calculator", "cloud-cost-calculator", "download-time-calculator", "session-duration-calculator", "storage-requirement-calculator", "data-transfer-cost-calculator"],
  "data-rate-calculator": ["clock-frequency-calculator", "energy-consumption-calculator", "power-calculator-electrical", "impedance-calculator"],
  "data-sampling-calculator": ["confidence-interval-calculator", "p-value-calculator", "correlation-coefficient-calculator", "data-normalization-calculator", "confusion-matrix-calculator", "time-series-forecast-calculator"],
  "data-transfer-calculator": ["bandwidth-calculator", "cidr-calculator", "subnet-calculator", "download-time-calculator", "latency-calculator", "ip-range-calculator"],
  "data-transfer-cost-calculator": ["storage-requirement-calculator", "cloud-cost-calculator", "download-time-calculator", "session-duration-calculator", "page-speed-score-calculator", "click-heatmap-density-calculator"],
  "dataset-split-calculator": ["model-accuracy-calculator", "confusion-matrix-calculator", "f1-score-calculator", "precision-recall-calculator", "ai-token-cost-calculator", "time-complexity-calculator"],
  "date-difference-calculator": ["age-calculator", "timestamp-unix-converter"],
  "decibel-db-calculator": ["amplifier-gain-calculator", "frequency-calculator", "impedance-calculator"],
  "decimal-land-calculator": ["katha-land-calculator", "bigha-land-calculator", "acre-to-square-feet-converter", "hectare-to-acre-converter"],
  "decimal-to-binary-calculator": ["logic-gate-calculator", "dac-output-calculator"],
  "decision-wheel": ["random-name-picker", "random-number-generator", "habit-tracker"],
  "dice-roller": ["decision-wheel", "random-number-generator", "random-name-picker"],
  "diode-calculator": ["led-resistor-calculator", "ohms-law-calculator", "voltage-divider-calculator", "power-calculator-electrical"],
  "discount-calculator": ["percentage-calculator", "percentage-increase-decrease", "profit-margin-calculator-marketing"],
  "dithering-filter": ["image-to-grayscale", "image-compressor"],
  "domain-authority-estimator": ["backlink-ratio-calculator", "seo-score-calculator", "keyword-density-checker", "ctr-calculator", "bounce-rate-calculator", "conversion-rate-calculator"],
  "door-area-calculator": ["window-area-calculator", "floor-area-calculator", "wall-area-calculator"],
  "down-payment-calculator": ["mortgage-calculator", "land-price-calculator"],
  "download-time-calculator": ["data-transfer-calculator", "bandwidth-calculator", "cidr-calculator", "subnet-calculator", "ip-range-calculator", "time-complexity-calculator"],
  "drag-force-calculator": ["friction-force-calculator", "force-calculator", "reynolds-number-calculator", "bernoulli-equation-calculator", "flow-rate-calculator", "pressure-drop-calculator"],
  "drainage-flow-calculator": ["excavation-volume-calculator", "concrete-volume-calculator", "slope-stability-calculator"],
  "drainage-system-calculator": ["rainwater-runoff-calculator", "irrigation-water-calculator", "soil-volume-calculator"],
  "duotone-filter": ["image-to-grayscale", "dithering-filter", "image-compressor"],
  "earth-filling-calculator": ["soil-volume-calculator", "excavation-cost-calculator", "land-area-calculator-square-feet"],
  "earthing-resistance-calculator": ["voltage-drop-calculator", "fuse-rating-calculator", "impedance-calculator"],
  "electric-bill-calculator": ["percentage-calculator"],
  "electric-motor-power-calculator": ["transformer-efficiency-calculator", "power-factor-calculator", "energy-consumption-calculator"],
  "electrical-efficiency-calculator": ["power-loss-calculator", "power-calculator-electrical", "energy-consumption-calculator", "motor-efficiency-calculator"],
  "electrical-load-calculator-building": ["lighting-load-calculator", "power-consumption-calculator", "ohms-law-calculator"],
  "elevation-design-calculator": ["facade-area-calculator", "building-height-calculator", "floor-area-calculator"],
  "email-click-rate-calculator": ["email-open-rate-calculator", "engagement-rate-calculator", "lead-conversion-funnel-calculator", "marketing-roi-calculator", "retention-rate-calculator", "cpm-calculator"],
  "email-obfuscator": ["text-encryptor-aes", "password-generator", "hash-generator"],
  "email-open-rate-calculator": ["email-click-rate-calculator", "engagement-rate-calculator", "lead-conversion-funnel-calculator", "marketing-roi-calculator", "retention-rate-calculator", "cpm-calculator"],
  "emergency-exit-width-calculator": ["fire-safety-load-calculator", "staircase-calculator", "room-area-calculator"],
  "encoding-efficiency-calculator": ["data-compression-ratio-calculator", "storage-requirement-calculator", "data-transfer-cost-calculator", "data-growth-calculator", "hadoop-storage-calculator", "data-pipeline-latency-calculator"],
  "energy-consumption-calculator": ["ohms-law-calculator", "power-calculator-electrical", "electric-bill-calculator"],
  "energy-efficiency-calculator-building": ["hvac-load-calculator", "cooling-load-calculator-architecture", "insulation-thickness-calculator"],
  "engagement-rate-calculator": ["social-media-reach-calculator", "impressions-calculator", "ctr-calculator", "conversion-rate-calculator", "cost-per-click-cpc-calculator"],
  "escalation-cost-calculator": ["concrete-volume-calculator", "cement-calculator", "brick-calculator"],
  "etl-throughput-calculator": ["data-growth-calculator", "session-duration-calculator", "page-speed-score-calculator", "user-growth-rate-calculator", "scroll-depth-calculator", "mean-calculator"],
  "excavation-cost-calculator": ["soil-volume-calculator", "earth-filling-calculator", "land-price-calculator"],
  "excavation-volume-calculator": ["concrete-volume-calculator", "construction-cost-estimator", "material-cost-calculator"],
  "exif-remover": ["image-compressor", "image-to-grayscale", "image-resizer"],
  "exponent-calculator": ["square-root-calculator", "scientific-calculator", "fraction-calculator"],
  "exponential-smoothing-calculator": ["moving-average-calculator", "mean-calculator", "standard-deviation-calculator", "regression-calculator", "correlation-coefficient-calculator", "data-growth-calculator"],
  "f1-score-calculator": ["precision-recall-calculator", "model-accuracy-calculator", "ai-token-cost-calculator", "ai-prompt-length-calculator", "time-complexity-calculator", "latency-calculator"],
  "facade-area-calculator": ["wall-area-calculator", "paint-required-calculator", "room-area-calculator"],
  "fan-power-consumption-calculator": ["energy-consumption-calculator", "electric-bill-calculator", "power-calculator-electrical"],
  "fatigue-life-calculator": ["stress-calculator", "beam-deflection-calculator", "spring-force-calculator", "moment-of-inertia-calculator", "natural-frequency-calculator"],
  "favicon-generator": ["image-resizer", "image-compressor", "base64-image-encoder"],
  "feed-rate-calculator": ["cutting-speed-calculator", "lathe-speed-calculator", "torque-calculator", "angular-velocity-calculator", "thread-pitch-calculator", "gear-ratio-calculator"],
  "fence-material-calculator": ["boundary-length-calculator", "plot-division-calculator", "land-price-calculator", "wall-boundary-cost-calculator"],
  "fertilizer-requirement-calculator": ["land-area-calculator-square-feet", "acre-to-hectare-converter", "soil-volume-calculator", "irrigation-water-calculator"],
  "file-hash-generator": ["text-encryptor-aes", "hash-generator", "password-generator"],
  "file-size-converter": ["data-transfer-calculator", "bandwidth-calculator", "download-time-calculator", "checksum-calculator", "subnet-calculator", "latency-calculator"],
  "find-and-replace": [],
  "fire-safety-load-calculator": ["concrete-volume-calculator", "construction-cost-estimator", "room-area-calculator"],
  "floor-area-calculator": ["aspect-ratio-calculator", "square-meter-to-square-foot-converter", "room-area-calculator"],
  "floor-finish-calculator": ["tile-quantity-calculator", "room-area-calculator", "paint-required-calculator"],
  "flow-rate-calculator": ["reynolds-number-calculator", "pressure-drop-calculator", "bernoulli-equation-calculator", "water-flow-rate-calculator", "drainage-flow-calculator"],
  "flowchart-logic-mapper": ["mind-map-builder", "timeline-creator", "venn-diagram-maker"],
  "font-pairer": ["color-palette-generator", "css-gradient-generator", "placeholder-image-generator"],
  "footing-size-calculator": ["foundation-depth-calculator", "concrete-volume-calculator", "slab-concrete-calculator"],
  "force-calculator": ["torque-calculator", "kinetic-energy-calculator", "centripetal-force-calculator", "momentum-calculator", "spring-force-calculator", "acceleration-calculator"],
  "foundation-depth-calculator": ["footing-size-calculator", "soil-bearing-capacity-calculator", "concrete-volume-calculator"],
  "fraction-calculator": ["percentage-calculator", "scientific-calculator", "average-calculator"],
  "frequency-calculator": ["impedance-calculator", "capacitive-reactance-calculator", "inductive-reactance-calculator"],
  "frequency-response-calculator": ["ohms-law-calculator", "capacitor-calculator", "inductor-calculator", "impedance-calculator"],
  "friction-force-calculator": ["force-calculator", "torque-calculator", "stress-calculator", "spring-force-calculator", "centripetal-force-calculator", "momentum-calculator"],
  "fuel-cost-calculator": [],
  "furniture-layout-calculator": ["interior-space-optimization-calculator", "room-area-calculator", "floor-area-calculator"],
  "fuse-rating-calculator": ["energy-consumption-calculator", "voltage-divider-calculator", "power-factor-calculator"],
  "gear-ratio-calculator": ["torque-calculator", "angular-velocity-calculator", "force-calculator", "velocity-calculator", "kinetic-energy-calculator", "spring-force-calculator"],
  "generator-size-calculator": ["solar-inverter-calculator", "energy-consumption-calculator", "wire-size-calculator"],
  "glass-panel-size-calculator": ["window-area-calculator", "door-area-calculator", "facade-area-calculator"],
  "glassmorphism-layer-tester": ["css-glassmorphism-generator", "pattern-noise-generator", "neumorphism-generator"],
  "golden-ratio-calculator": ["aspect-ratio-calculator", "css-gradient-generator", "color-palette-generator"],
  "gradient-text-generator": ["css-gradient-generator", "hsl-color-slider", "color-palette-generator"],
  "green-building-score-calculator": ["energy-efficiency-calculator-building", "carbon-footprint-calculator-construction", "sustainability-index-calculator"],
  "ground-fault-current-calculator": ["short-circuit-current-calculator", "power-loss-calculator", "ohms-law-calculator", "electrical-efficiency-calculator"],
  "gst-vat-calculator": ["discount-calculator", "percentage-calculator", "profit-margin-calculator-marketing", "investment-return-calculator"],
  "habit-tracker": ["pomodoro-timer", "timer-stopwatch"],
  "hadoop-storage-calculator": ["storage-requirement-calculator", "data-transfer-cost-calculator", "cluster-utilization-calculator", "big-data-throughput-calculator", "data-partition-calculator", "data-pipeline-latency-calculator"],
  "hash-generator": ["password-generator", "text-encrypt-decrypt", "username-generator"],
  "heat-dissipation-calculator": ["power-loss-calculator", "power-calculator-electrical", "ohms-law-calculator", "electrical-efficiency-calculator"],
  "heat-loss-calculator-building": ["hvac-load-calculator", "cooling-load-calculator-architecture", "ventilation-calculator"],
  "heat-transfer-calculator": ["thermal-expansion-calculator", "specific-heat-calculator", "thermal-efficiency-calculator", "reynolds-number-calculator", "ideal-gas-law-calculator"],
  "heatmap-grid": ["venn-diagram-maker", "flowchart-logic-mapper", "timeline-creator"],
  "heatsink-calculator": ["heat-dissipation-calculator", "power-loss-calculator", "electrical-efficiency-calculator", "power-density-calculator"],
  "hectare-to-acre-converter": ["acre-to-hectare-converter", "acre-to-square-feet-converter", "square-feet-to-acre-converter", "land-area-calculator-square-meter"],
  "hex-to-rgb-converter": ["duotone-filter"],
  "hex-to-rgba-converter": ["color-format-converter", "hex-to-rgb-converter", "css-gradient-generator"],
  "histogram-bin-calculator": ["standard-deviation-calculator", "percentile-calculator", "mean-calculator", "median-calculator", "outlier-detection-calculator", "data-normalization-calculator"],
  "house-wiring-load-calculator": ["fuse-rating-calculator", "voltage-drop-calculator", "energy-consumption-calculator"],
  "hsl-color-slider": ["color-palette-generator", "color-format-converter", "hex-to-rgb-converter"],
  "html-entity-encoder": ["url-encoder-decoder", "base64-encoder-decoder", "json-formatter"],
  "http-status-code-lookup": ["user-agent-parser", "json-formatter", "regex-tester"],
  "hvac-load-calculator": ["ventilation-calculator", "air-change-rate-calculator", "cooling-load-calculator-architecture"],
  "hydraulic-pressure-calculator": ["pressure-drop-calculator", "flow-rate-calculator", "pump-efficiency-calculator", "force-calculator", "stress-calculator", "bernoulli-equation-calculator"],
  "ideal-gas-law-calculator": ["reynolds-number-calculator", "bernoulli-equation-calculator", "pressure-drop-calculator", "flow-rate-calculator", "temperature-conversion-scientific", "heat-transfer-calculator"],
  "ideal-weight-calculator": ["bmi-calculator", "bmr-calculator", "daily-calorie-calculator"],
  "image-compressor": ["image-resizer", "image-to-grayscale", "exif-remover"],
  "image-resizer": [],
  "image-to-grayscale": ["image-compressor", "image-resizer", "favicon-generator"],
  "impedance-calculator": ["inductive-reactance-calculator", "capacitive-reactance-calculator", "phase-angle-calculator"],
  "impressions-calculator": ["ctr-calculator", "conversion-rate-calculator", "cost-per-click-cpc-calculator", "bounce-rate-calculator", "cost-per-acquisition-cpa-calculator"],
  "inch-to-cm-converter": ["centimeter-to-meter-converter", "meter-to-km-converter", "temperature-conversion-scientific"],
  "index-size-calculator": ["storage-requirement-calculator", "hadoop-storage-calculator", "data-partition-calculator", "cache-efficiency-calculator", "data-compression-ratio-calculator", "cluster-utilization-calculator"],
  "inductive-reactance-calculator": ["capacitive-reactance-calculator", "impedance-calculator", "inductor-calculator"],
  "inductor-calculator": ["capacitor-calculator", "capacitive-reactance-calculator", "ohms-law-calculator"],
  "insulation-thickness-calculator": ["heat-loss-calculator-building", "hvac-load-calculator", "cooling-load-calculator-architecture"],
  "interior-space-optimization-calculator": ["room-area-calculator", "floor-area-calculator", "parking-space-calculator"],
  "investment-return-calculator": ["simple-interest-calculator", "compound-interest-calculator", "percentage-calculator", "loan-calculator"],
  "ip-address-masker": ["hash-generator", "base64-encoder-decoder", "url-encoder-decoder"],
  "ip-range-calculator": ["subnet-calculator", "cidr-calculator", "bandwidth-calculator", "checksum-calculator", "ip-address-masker", "download-time-calculator"],
  "irrigation-water-calculator": ["fertilizer-requirement-calculator", "land-area-calculator-square-feet", "rainwater-harvesting-calculator", "water-tank-capacity-calculator"],
  "json-formatter": ["json-validator", "json-to-csv", "xml-to-json"],
  "json-to-csv": ["json-validator", "xml-to-json", "find-and-replace"],
  "json-validator": ["find-and-replace", "text-diff-checker"],
  "jwt-debugger": ["json-validator", "base64-encoder-decoder", "hash-generator"],
  "katha-land-calculator": ["land-area-calculator-square-feet", "land-area-calculator-square-meter", "acre-to-square-feet-converter", "hectare-to-acre-converter"],
  "keyword-density-calculator-seo": ["ctr-calculator", "conversion-rate-calculator", "cost-per-click-cpc-calculator", "cost-per-acquisition-cpa-calculator", "bounce-rate-calculator"],
  "keyword-density-checker": ["word-counter", "paragraph-formatter"],
  "keyword-difficulty-estimator": ["seo-score-calculator", "domain-authority-estimator", "backlink-ratio-calculator", "keyword-density-calculator-seo", "serp-ctr-estimator", "organic-vs-paid-ratio-calculator"],
  "kinetic-energy-calculator": ["force-calculator", "momentum-calculator", "velocity-calculator", "torque-calculator", "projectile-motion-calculator"],
  "labor-cost-calculator": ["construction-cost-estimator", "material-cost-calculator", "escalation-cost-calculator"],
  "land-area-calculator-square-feet": ["plot-area-calculator", "room-area-calculator", "floor-area-calculator", "square-meter-to-square-foot-converter"],
  "land-area-calculator-square-meter": ["land-area-calculator-square-feet", "acre-to-square-feet-converter", "square-meter-to-square-foot-converter", "plot-area-calculator"],
  "land-development-cost-calculator": ["land-price-calculator", "subdivision-cost-calculator", "excavation-cost-calculator", "land-valuation-calculator", "construction-cost-estimator", "property-appreciation-calculator"],
  "land-leveling-calculator": ["earth-filling-calculator", "soil-volume-calculator", "excavation-cost-calculator", "land-area-calculator-square-feet"],
  "land-price-calculator": ["decimal-land-calculator", "katha-land-calculator", "bigha-land-calculator", "acre-to-square-feet-converter"],
  "land-valuation-calculator": ["land-price-calculator", "price-per-square-feet-calculator", "decimal-land-calculator", "katha-land-calculator"],
  "latency-calculator": ["download-time-calculator", "data-transfer-calculator", "bandwidth-calculator", "subnet-calculator", "cidr-calculator", "ip-range-calculator"],
  "lathe-speed-calculator": ["cutting-speed-calculator", "torque-calculator", "gear-ratio-calculator", "angular-velocity-calculator", "thread-pitch-calculator", "feed-rate-calculator"],
  "lead-conversion-funnel-calculator": ["conversion-rate-calculator", "cost-per-acquisition-cpa-calculator", "customer-lifetime-value-calculator", "bounce-rate-calculator", "marketing-roi-calculator"],
  "led-resistor-calculator": ["ohms-law-calculator", "voltage-divider-calculator", "series-resistor-calculator", "parallel-resistor-calculator"],
  "leetspeak-converter": ["zalgo-text-generator", "text-reverser", "nato-phonetic-converter"],
  "lighting-load-calculator": ["electrical-load-calculator-building", "power-consumption-calculator", "energy-efficiency-calculator-building"],
  "lightning-protection-calculator": ["power-calculator-electrical", "energy-consumption-calculator", "electric-bill-calculator", "ohms-law-calculator"],
  "list-prefix-suffix": ["remove-duplicate-lines", "find-and-replace", "paragraph-formatter"],
  "live-load-calculator": ["structural-load-calculator", "slab-load-calculator"],
  "loan-calculator": ["simple-interest-calculator", "compound-interest-calculator", "salary-calculator", "percentage-calculator"],
  "loan-interest-calculator-property": ["mortgage-calculator", "down-payment-calculator", "land-price-calculator"],
  "log-transformation-calculator": ["data-normalization-calculator", "min-max-scaling-calculator", "standard-deviation-calculator", "mean-calculator", "exponential-smoothing-calculator", "variance-calculator"],
  "logic-gate-calculator": ["adc-resolution-calculator"],
  "lorem-ipsum-generator": ["word-counter", "paragraph-formatter"],
  "mach-number-calculator": ["drag-force-calculator", "reynolds-number-calculator", "velocity-calculator", "bernoulli-equation-calculator", "flow-rate-calculator", "pressure-drop-calculator"],
  "map-scale-calculator": ["survey-area-calculator", "boundary-length-calculator", "land-area-calculator-square-feet"],
  "markdown-previewer": ["word-counter", "paragraph-formatter"],
  "marketing-roi-calculator": ["cost-per-acquisition-cpa-calculator", "cost-per-click-cpc-calculator", "profit-margin-calculator-marketing", "break-even-calculator", "customer-lifetime-value-calculator"],
  "material-cost-calculator": ["construction-cost-estimator", "concrete-volume-calculator", "brick-calculator"],
  "matrix-calculator": [],
  "mean-calculator": ["median-calculator", "mode-calculator", "standard-deviation-calculator", "variance-calculator", "percentile-calculator"],
  "median-calculator": ["mean-calculator", "standard-deviation-calculator", "data-growth-calculator", "etl-throughput-calculator", "storage-requirement-calculator", "session-duration-calculator"],
  "meter-to-km-converter": ["centimeter-to-meter-converter", "unit-ratio-calculator"],
  "min-max-scaling-calculator": ["data-normalization-calculator", "log-transformation-calculator", "standard-deviation-calculator", "z-score-calculator", "mean-calculator", "outlier-detection-calculator"],
  "mind-map-builder": ["flowchart-logic-mapper", "venn-diagram-maker", "word-cloud-generator"],
  "mock-data-generator": ["json-formatter", "password-generator", "username-generator"],
  "mode-calculator": ["mean-calculator", "median-calculator", "standard-deviation-calculator", "variance-calculator", "percentile-calculator"],
  "model-accuracy-calculator": ["ai-token-cost-calculator", "ai-prompt-length-calculator", "time-complexity-calculator", "latency-calculator", "data-transfer-calculator", "subnet-calculator"],
  "moment-of-inertia-calculator": ["beam-deflection-calculator", "stress-calculator", "torque-calculator"],
  "momentum-calculator": ["kinetic-energy-calculator", "force-calculator", "velocity-calculator", "acceleration-calculator", "torque-calculator", "centripetal-force-calculator"],
  "morse-code-translator": ["nato-phonetic-converter", "text-reverser", "upside-down-text-generator"],
  "mortgage-calculator": ["loan-calculator", "simple-interest-calculator"],
  "motor-efficiency-calculator": ["electric-motor-power-calculator", "power-factor-calculator", "energy-consumption-calculator"],
  "motor-speed-calculator": ["electric-motor-power-calculator", "frequency-calculator", "power-factor-calculator"],
  "moving-average-calculator": ["mean-calculator", "median-calculator", "standard-deviation-calculator", "regression-calculator", "correlation-coefficient-calculator", "data-growth-calculator"],
  "nato-phonetic-converter": ["text-reverser", "sentence-case-converter", "word-counter"],
  "natural-frequency-calculator": ["spring-force-calculator", "torque-calculator", "kinetic-energy-calculator", "moment-of-inertia-calculator", "beam-deflection-calculator", "stress-calculator"],
  "neumorphism-generator": ["css-box-shadow-generator", "css-gradient-generator", "css-glassmorphism-generator"],
  "ohms-law-calculator": ["unit-ratio-calculator"],
  "op-amp-calculator": ["amplifier-gain-calculator", "voltage-divider-calculator", "impedance-calculator"],
  "organic-vs-paid-ratio-calculator": ["traffic-growth-calculator", "seo-score-calculator", "domain-authority-estimator", "cost-per-click-cpc-calculator", "conversion-rate-calculator"],
  "outlier-detection-calculator": ["standard-deviation-calculator", "percentile-calculator", "histogram-bin-calculator", "mean-calculator", "median-calculator", "z-score-calculator"],
  "p-value-calculator": ["confidence-interval-calculator", "z-score-calculator", "correlation-coefficient-calculator", "standard-deviation-calculator", "chi-square-calculator", "sample-size-calculator"],
  "page-rank-estimator": ["seo-score-calculator", "serp-ctr-estimator", "domain-authority-estimator", "keyword-density-calculator-seo", "backlink-ratio-calculator", "traffic-growth-calculator"],
  "page-speed-score-calculator": ["session-duration-calculator", "bounce-rate-calculator", "conversion-rate-calculator", "seo-score-calculator", "domain-authority-estimator", "download-time-calculator"],
  "paint-required-calculator": ["wall-area-calculator", "room-area-calculator", "floor-area-calculator"],
  "palindrome-checker": ["word-counter", "text-reverser", "paragraph-formatter"],
  "paragraph-formatter": ["word-counter", "text-reverser"],
  "parallel-resistor-calculator": ["series-resistor-calculator", "ohms-law-calculator", "voltage-divider-calculator"],
  "parking-space-calculator": ["room-area-calculator", "floor-area-calculator", "plot-area-calculator"],
  "password-generator": ["username-generator", "hash-generator", "text-encrypt-decrypt"],
  "password-strength-meter": ["password-generator", "hash-generator", "text-encrypt-decrypt"],
  "pattern-noise-generator": ["css-glassmorphism-generator", "css-gradient-generator", "dithering-filter"],
  "percentage-calculator": ["percentage-increase-decrease", "discount-calculator"],
  "percentage-increase-decrease": ["percentage-calculator", "discount-calculator"],
  "percentile-calculator": ["median-calculator", "mean-calculator", "standard-deviation-calculator", "variance-calculator", "z-score-calculator", "outlier-detection-calculator"],
  "phase-angle-calculator": ["power-factor-calculator", "impedance-calculator", "inductive-reactance-calculator"],
  "pie-chart-maker": ["bar-graph-generator", "heatmap-grid", "word-cloud-generator"],
  "pixel-art-grid": ["ascii-art-generator", "placeholder-image-generator", "color-palette-generator"],
  "placeholder-image-generator": ["favicon-generator", "color-palette-generator", "css-gradient-generator"],
  "plot-area-calculator": ["floor-area-calculator", "aspect-ratio-calculator", "square-meter-to-square-foot-converter"],
  "plot-division-calculator": ["land-price-calculator", "land-area-calculator-square-feet", "boundary-length-calculator", "fence-material-calculator"],
  "plumbing-pipe-size-calculator": ["drainage-flow-calculator", "water-tank-capacity-calculator", "concrete-volume-calculator"],
  "polygon-area-calculator": ["survey-area-calculator", "land-price-calculator", "boundary-length-calculator", "triangle-land-area-calculator"],
  "pomodoro-timer": ["timer-stopwatch"],
  "power-calculator-electrical": ["ohms-law-calculator", "voltage-drop-calculator", "electrical-load-calculator-building"],
  "power-consumption-calculator": [],
  "power-density-calculator": ["power-calculator-electrical", "electrical-efficiency-calculator", "power-loss-calculator", "energy-consumption-calculator"],
  "power-factor-calculator": ["impedance-calculator", "phase-angle-calculator", "energy-consumption-calculator"],
  "power-loss-calculator": ["power-calculator-electrical", "energy-consumption-calculator", "ohms-law-calculator", "voltage-drop-calculator"],
  "power-supply-calculator": ["power-consumption-calculator", "energy-consumption-calculator", "electric-motor-power-calculator", "power-loss-calculator"],
  "precision-recall-calculator": ["model-accuracy-calculator", "ai-token-cost-calculator", "ai-prompt-length-calculator", "time-complexity-calculator", "latency-calculator", "data-transfer-calculator"],
  "pressure-drop-calculator": ["reynolds-number-calculator", "flow-rate-calculator", "bernoulli-equation-calculator", "hydraulic-pressure-calculator"],
  "price-per-square-feet-calculator": ["land-price-calculator", "decimal-land-calculator", "katha-land-calculator", "acre-to-square-feet-converter"],
  "prime-number-checker": ["scientific-calculator", "random-number-generator"],
  "profit-margin-calculator-marketing": ["revenue-growth-calculator", "cost-per-acquisition-cpa-calculator", "customer-lifetime-value-calculator", "investment-return-calculator", "break-even-calculator"],
  "project-timeline-calculator": ["construction-cost-estimator", "labor-cost-calculator", "material-cost-calculator"],
  "projectile-motion-calculator": ["kinetic-energy-calculator", "force-calculator", "velocity-calculator", "centripetal-force-calculator", "angular-velocity-calculator", "momentum-calculator"],
  "property-appreciation-calculator": ["roi-real-estate-calculator", "rental-yield-calculator", "land-price-calculator", "mortgage-calculator", "down-payment-calculator", "land-valuation-calculator"],
  "pump-efficiency-calculator": ["flow-rate-calculator", "reynolds-number-calculator", "pressure-drop-calculator", "motor-efficiency-calculator"],
  "pwm-duty-cycle-calculator": ["frequency-calculator", "signal-attenuation-calculator", "rc-time-constant-calculator"],
  "px-to-rem-converter": ["css-gradient-generator", "css-box-shadow-generator", "css-flexbox-playground"],
  "qr-code-generator": ["base64-image-encoder", "url-encoder-decoder"],
  "query-optimization-calculator": ["big-data-throughput-calculator", "cluster-utilization-calculator", "spark-job-time-calculator", "data-compression-ratio-calculator", "index-size-calculator", "data-partition-calculator"],
  "rafter-length-calculator": ["roof-pitch-calculator", "roof-area-calculator", "floor-area-calculator"],
  "rainwater-harvesting-calculator": ["excavation-volume-calculator", "drainage-flow-calculator", "concrete-volume-calculator"],
  "rainwater-runoff-calculator": ["drainage-system-calculator", "rainwater-harvesting-calculator", "irrigation-water-calculator", "water-tank-capacity-calculator", "drainage-flow-calculator", "land-area-calculator-square-feet"],
  "random-hex-color-generator": ["color-palette-generator", "hsl-color-slider", "gradient-text-generator"],
  "random-id-generator": ["hash-generator", "password-generator"],
  "random-name-picker": [],
  "random-number-generator": ["password-generator", "hash-generator", "username-generator"],
  "rc-time-constant-calculator": ["capacitor-charge-time-calculator", "capacitor-calculator", "impedance-calculator"],
  "reactive-power-calculator": ["real-power-calculator", "power-factor-calculator", "phase-angle-calculator"],
  "reading-time-calculator": ["word-counter", "word-frequency-counter", "paragraph-formatter"],
  "real-power-calculator": ["voltage-divider-calculator", "impedance-calculator", "phase-angle-calculator"],
  "rebar-spacing-calculator": ["rebar-weight-calculator", "concrete-volume-calculator", "steel-quantity-calculator"],
  "rebar-weight-calculator": ["steel-quantity-calculator", "concrete-volume-calculator", "cement-calculator"],
  "refrigeration-cop-calculator": ["thermal-efficiency-calculator", "air-conditioner-power-calculator", "ideal-gas-law-calculator", "heat-dissipation-calculator", "pump-efficiency-calculator"],
  "regex-tester": ["json-validator", "text-diff-checker", "find-and-replace"],
  "regression-calculator": ["correlation-coefficient-calculator", "mean-calculator", "median-calculator", "standard-deviation-calculator", "data-growth-calculator", "session-duration-calculator"],
  "relay-calculator": ["led-resistor-calculator", "op-amp-calculator"],
  "remove-duplicate-lines": [],
  "rental-yield-calculator": ["land-price-calculator", "mortgage-calculator", "down-payment-calculator"],
  "resistor-color-code-calculator": ["ohms-law-calculator", "parallel-resistor-calculator", "voltage-divider-calculator"],
  "retaining-wall-calculator": ["concrete-volume-calculator", "soil-bearing-capacity-calculator", "foundation-depth-calculator"],
  "retention-rate-calculator": ["churn-rate-calculator", "customer-lifetime-value-calculator", "conversion-rate-calculator", "bounce-rate-calculator", "lead-conversion-funnel-calculator", "revenue-growth-calculator"],
  "revenue-growth-calculator": ["cost-per-acquisition-cpa-calculator", "customer-lifetime-value-calculator", "investment-return-calculator", "profit-margin-calculator-marketing", "conversion-rate-calculator"],
  "reynolds-number-calculator": ["flow-rate-calculator", "pressure-drop-calculator", "bernoulli-equation-calculator", "drag-force-calculator", "torque-calculator", "force-calculator"],
  "rf-power-calculator": ["antenna-length-calculator", "impedance-calculator", "decibel-db-calculator", "amplifier-gain-calculator"],
  "rl-time-constant-calculator": ["rc-time-constant-calculator", "inductor-calculator", "impedance-calculator"],
  "rlc-resonance-calculator": ["rc-time-constant-calculator", "rl-time-constant-calculator", "impedance-calculator"],
  "roc-auc-calculator": ["precision-recall-calculator", "f1-score-calculator", "confusion-matrix-calculator", "chi-square-calculator", "a-b-test-calculator"],
  "roi-calculator-marketing": ["ctr-calculator", "conversion-rate-calculator", "bounce-rate-calculator", "investment-return-calculator", "simple-interest-calculator", "compound-interest-calculator"],
  "roi-real-estate-calculator": ["rental-yield-calculator", "mortgage-calculator", "down-payment-calculator", "land-price-calculator"],
  "roman-numeral-converter": ["binary-hex-decimal-converter", "timestamp-unix-converter"],
  "roof-area-calculator": ["floor-area-calculator", "wall-area-calculator", "paint-required-calculator"],
  "roof-pitch-calculator": ["roof-area-calculator", "floor-area-calculator", "wall-area-calculator"],
  "room-acoustics-calculator": ["acoustic-soundproofing-calculator", "ventilation-calculator", "room-volume-calculator"],
  "room-area-calculator": ["floor-area-calculator", "plot-area-calculator", "square-meter-to-square-foot-converter"],
  "room-lighting-calculator": ["house-wiring-load-calculator", "energy-consumption-calculator", "voltage-drop-calculator"],
  "room-volume-calculator": ["room-area-calculator", "floor-area-calculator", "plot-area-calculator"],
  "salary-calculator": ["percentage-calculator", "loan-calculator"],
  "sample-size-calculator": ["confidence-interval-calculator", "a-b-test-calculator", "p-value-calculator", "standard-deviation-calculator", "mean-calculator", "z-score-calculator"],
  "sand-calculator": ["cement-calculator", "brick-calculator"],
  "scientific-calculator": ["percentage-calculator", "matrix-calculator", "average-calculator"],
  "screen-resolution-checker": ["user-agent-parser", "css-flexbox-playground"],
  "scroll-depth-calculator": ["session-duration-calculator", "page-speed-score-calculator", "click-heatmap-density-calculator", "bounce-rate-calculator", "engagement-rate-calculator", "conversion-rate-calculator"],
  "seasonality-index-calculator": ["time-series-forecast-calculator", "user-growth-rate-calculator", "data-growth-calculator", "correlation-coefficient-calculator", "session-duration-calculator", "sample-size-calculator"],
  "sentence-case-converter": ["word-counter", "text-reverser", "paragraph-formatter"],
  "seo-score-calculator": ["keyword-density-checker", "ctr-calculator", "conversion-rate-calculator", "cost-per-click-cpc-calculator", "bounce-rate-calculator"],
  "septic-tank-size-calculator": ["drainage-flow-calculator", "excavation-volume-calculator", "concrete-volume-calculator"],
  "series-resistor-calculator": ["parallel-resistor-calculator", "ohms-law-calculator", "voltage-divider-calculator"],
  "serp-ctr-estimator": ["ctr-calculator", "keyword-density-calculator-seo", "seo-score-calculator", "domain-authority-estimator", "traffic-growth-calculator", "backlink-ratio-calculator"],
  "session-duration-calculator": ["page-speed-score-calculator", "bounce-rate-calculator", "conversion-rate-calculator", "retention-rate-calculator", "engagement-rate-calculator", "impressions-calculator"],
  "shadow-length-calculator": ["sunlight-exposure-calculator", "building-height-calculator", "room-area-calculator"],
  "short-circuit-current-calculator": ["impedance-calculator", "power-loss-calculator", "fuse-rating-calculator", "circuit-breaker-calculator"],
  "signal-attenuation-calculator": ["amplifier-gain-calculator", "power-factor-calculator", "impedance-calculator"],
  "simple-interest-calculator": ["compound-interest-calculator", "mortgage-calculator", "loan-calculator"],
  "skirting-material-calculator": ["room-area-calculator", "floor-finish-calculator", "paint-required-calculator"],
  "slab-concrete-calculator": ["concrete-volume-calculator", "concrete-mix-ratio-calculator", "cement-calculator"],
  "slab-load-calculator": ["concrete-volume-calculator", "beam-load-calculator", "column-load-calculator"],
  "slip-calculator": ["motor-speed-calculator", "electric-motor-power-calculator", "frequency-calculator"],
  "slope-stability-calculator": ["soil-bearing-capacity-calculator", "retaining-wall-calculator", "foundation-depth-calculator"],
  "smps-calculator": ["power-supply-calculator", "transformer-efficiency-calculator", "power-factor-calculator", "voltage-regulation-calculator"],
  "social-media-post-preview": ["text-to-slug-converter", "word-counter", "paragraph-formatter"],
  "social-media-reach-calculator": ["impressions-calculator", "ctr-calculator", "conversion-rate-calculator", "cost-per-click-cpc-calculator", "bounce-rate-calculator"],
  "soil-bearing-capacity-calculator": ["foundation-depth-calculator", "footing-size-calculator", "structural-load-calculator"],
  "soil-compaction-calculator": ["soil-bearing-capacity-calculator", "foundation-depth-calculator", "excavation-volume-calculator"],
  "soil-compaction-ratio-calculator": ["land-leveling-calculator", "earth-filling-calculator", "soil-volume-calculator", "excavation-cost-calculator"],
  "soil-volume-calculator": ["earth-filling-calculator", "excavation-cost-calculator", "land-area-calculator-square-feet"],
  "solar-battery-calculator": ["solar-panel-calculator", "battery-capacity-calculator", "solar-inverter-calculator"],
  "solar-inverter-calculator": ["solar-panel-calculator", "solar-battery-calculator", "battery-capacity-calculator"],
  "solar-panel-calculator": ["solar-battery-calculator", "solar-inverter-calculator", "energy-consumption-calculator"],
  "spark-job-time-calculator": ["big-data-throughput-calculator", "cluster-utilization-calculator", "data-compression-ratio-calculator", "encoding-efficiency-calculator", "data-partition-calculator", "time-series-forecast-calculator"],
  "specific-heat-calculator": [],
  "spring-force-calculator": ["force-calculator", "torque-calculator", "kinetic-energy-calculator", "stress-calculator", "natural-frequency-calculator"],
  "sql-formatter": ["json-validator", "regex-tester", "find-and-replace"],
  "square-feet-to-acre-converter": ["acre-to-square-feet-converter", "land-area-calculator-square-feet", "land-area-calculator-square-meter", "square-meter-to-square-foot-converter"],
  "square-meter-to-square-foot-converter": ["inch-to-cm-converter", "meter-to-km-converter", "centimeter-to-meter-converter"],
  "square-root-calculator": ["scientific-calculator", "average-calculator"],
  "sri-generator": ["file-hash-generator", "text-encryptor-aes", "password-generator"],
  "staircase-calculator": ["floor-area-calculator", "room-volume-calculator", "wall-area-calculator"],
  "standard-deviation-calculator": ["mean-calculator", "median-calculator", "data-growth-calculator", "etl-throughput-calculator", "storage-requirement-calculator", "session-duration-calculator"],
  "steel-quantity-calculator": ["rebar-weight-calculator", "rebar-spacing-calculator", "concrete-volume-calculator"],
  "steganography-tool": ["text-encryptor-aes", "file-hash-generator", "password-generator"],
  "step-rise-run-calculator": ["staircase-calculator", "floor-area-calculator", "room-volume-calculator"],
  "storage-requirement-calculator": ["data-transfer-cost-calculator", "cloud-cost-calculator", "download-time-calculator", "session-duration-calculator", "page-speed-score-calculator", "click-heatmap-density-calculator"],
  "stress-calculator": ["torque-calculator", "force-calculator", "beam-deflection-calculator", "spring-force-calculator", "kinetic-energy-calculator", "reynolds-number-calculator"],
  "structural-load-calculator": ["beam-load-calculator", "slab-load-calculator", "column-load-calculator"],
  "subdivision-cost-calculator": ["land-price-calculator", "plot-division-calculator", "land-valuation-calculator", "excavation-cost-calculator", "fence-material-calculator", "boundary-length-calculator"],
  "subnet-calculator": ["ip-range-calculator", "cidr-calculator", "bandwidth-calculator", "checksum-calculator", "ip-address-masker", "download-time-calculator"],
  "sunlight-exposure-calculator": ["building-height-calculator", "room-area-calculator", "plot-area-calculator"],
  "survey-area-calculator": ["land-area-calculator-square-feet", "polygon-area-calculator", "land-price-calculator", "boundary-length-calculator"],
  "sustainability-index-calculator": ["green-building-score-calculator", "energy-efficiency-calculator-building", "carbon-footprint-calculator-construction"],
  "svg-path-visualizer": ["css-gradient-generator", "color-format-converter", "css-glassmorphism-generator"],
  "svg-pattern-generator": ["css-gradient-generator", "placeholder-image-generator", "color-palette-generator"],
  "table-to-markdown": [],
  "temperature-conversion-scientific": ["celsius-to-fahrenheit-converter"],
  "text-diff-checker": [],
  "text-encrypt-decrypt": ["password-generator", "hash-generator"],
  "text-encryptor-aes": ["password-generator", "hash-generator"],
  "text-reverser": ["word-counter", "paragraph-formatter"],
  "text-to-clipboard": ["word-counter", "text-reverser", "paragraph-formatter"],
  "text-to-slug-converter": ["word-counter", "text-reverser", "paragraph-formatter"],
  "text-to-speech-preview": ["voice-to-text-notepad", "reading-time-calculator", "word-counter"],
  "thermal-efficiency-calculator": ["heat-transfer-calculator", "ideal-gas-law-calculator", "thermal-expansion-calculator", "pump-efficiency-calculator"],
  "thermal-expansion-calculator": ["heat-transfer-calculator", "stress-calculator", "reynolds-number-calculator", "flow-rate-calculator", "torque-calculator", "kinetic-energy-calculator"],
  "thread-pitch-calculator": ["torque-calculator", "bolt-load-calculator", "stress-calculator", "force-calculator", "gear-ratio-calculator", "spring-force-calculator"],
  "three-phase-power-calculator": ["power-factor-calculator", "apparent-power-calculator", "real-power-calculator", "reactive-power-calculator"],
  "tile-quantity-calculator": ["wall-area-calculator", "floor-area-calculator", "paint-required-calculator"],
  "time-complexity-calculator": ["data-transfer-calculator", "bandwidth-calculator", "cidr-calculator", "subnet-calculator", "checksum-calculator", "ip-range-calculator"],
  "time-duration-calculator": ["date-difference-calculator", "timestamp-unix-converter", "timer-stopwatch"],
  "time-series-forecast-calculator": ["moving-average-calculator", "exponential-smoothing-calculator", "regression-calculator", "seasonality-index-calculator", "correlation-coefficient-calculator", "data-growth-calculator"],
  "time-zone-converter": ["pomodoro-timer", "timer-stopwatch", "date-difference-calculator"],
  "timeline-creator": ["bar-graph-generator", "pie-chart-maker", "mind-map-builder"],
  "timer-stopwatch": ["timestamp-unix-converter"],
  "timestamp-unix-converter": ["age-calculator"],
  "tip-calculator": ["discount-calculator", "percentage-calculator"],
  "torque-calculator": ["gear-ratio-calculator", "force-calculator", "angular-velocity-calculator", "spring-force-calculator", "centripetal-force-calculator", "kinetic-energy-calculator"],
  "traffic-growth-calculator": ["revenue-growth-calculator", "seo-score-calculator", "domain-authority-estimator", "impressions-calculator", "social-media-reach-calculator"],
  "transformer-current-calculator": ["transformer-turns-ratio-calculator", "transformer-efficiency-calculator", "three-phase-power-calculator", "power-factor-calculator"],
  "transformer-efficiency-calculator": ["transformer-turns-ratio-calculator", "power-factor-calculator", "energy-consumption-calculator", "three-phase-power-calculator"],
  "transformer-turns-ratio-calculator": ["voltage-divider-calculator", "power-factor-calculator", "impedance-calculator", "ohms-law-calculator"],
  "transistor-bias-calculator": ["ohms-law-calculator", "voltage-divider-calculator", "led-resistor-calculator", "power-calculator-electrical"],
  "trapezoid-land-calculator": ["triangle-land-area-calculator", "survey-area-calculator", "polygon-area-calculator", "land-price-calculator"],
  "triangle-land-area-calculator": ["survey-area-calculator", "polygon-area-calculator", "land-price-calculator", "boundary-length-calculator"],
  "unit-ratio-calculator": ["aspect-ratio-calculator", "golden-ratio-calculator"],
  "ups-backup-calculator": ["ups-load-calculator", "battery-backup-time-calculator", "battery-capacity-calculator", "energy-consumption-calculator"],
  "ups-load-calculator": ["battery-backup-time-calculator", "power-consumption-calculator", "generator-size-calculator", "energy-consumption-calculator"],
  "upside-down-text-generator": ["text-reverser", "zalgo-text-generator", "leetspeak-converter"],
  "url-encoder-decoder": ["base64-encoder-decoder", "json-validator", "regex-tester"],
  "url-sanitizer": ["url-encoder-decoder", "password-generator", "hash-generator"],
  "user-agent-parser": ["json-formatter", "base64-encoder-decoder", "regex-tester"],
  "user-growth-rate-calculator": ["traffic-growth-calculator", "retention-rate-calculator", "churn-rate-calculator", "viral-coefficient-calculator", "revenue-growth-calculator", "customer-lifetime-value-calculator"],
  "username-generator": ["password-generator", "random-name-picker", "text-to-slug-converter"],
  "variance-calculator": ["standard-deviation-calculator", "mean-calculator", "median-calculator", "mode-calculator", "z-score-calculator", "correlation-coefficient-calculator"],
  "velocity-calculator": ["torque-calculator", "force-calculator", "kinetic-energy-calculator", "angular-velocity-calculator", "centripetal-force-calculator", "projectile-motion-calculator"],
  "venn-diagram-maker": ["flowchart-logic-mapper", "mind-map-builder", "timeline-creator"],
  "ventilation-calculator": ["hvac-load-calculator", "room-volume-calculator"],
  "video-frame-extractor": ["audio-visualizer", "image-resizer", "image-compressor"],
  "viral-coefficient-calculator": ["retention-rate-calculator", "churn-rate-calculator", "customer-lifetime-value-calculator", "marketing-roi-calculator", "lead-conversion-funnel-calculator"],
  "voice-to-text-notepad": ["word-counter", "text-to-clipboard", "reading-time-calculator"],
  "voltage-divider-calculator": ["ohms-law-calculator", "power-consumption-calculator", "resistor-color-code-calculator"],
  "voltage-drop-calculator": ["voltage-divider-calculator", "energy-consumption-calculator", "fuse-rating-calculator"],
  "voltage-regulation-calculator": ["voltage-divider-calculator", "transformer-efficiency-calculator", "power-loss-calculator", "voltage-drop-calculator"],
  "wall-area-calculator": ["floor-area-calculator", "room-area-calculator", "plot-area-calculator"],
  "wall-boundary-cost-calculator": ["boundary-length-calculator", "fence-material-calculator", "land-price-calculator", "plot-division-calculator"],
  "water-flow-rate-calculator": ["plumbing-pipe-size-calculator", "drainage-flow-calculator", "water-tank-capacity-calculator"],
  "water-tank-capacity-calculator": ["rainwater-harvesting-calculator", "concrete-volume-calculator", "excavation-volume-calculator"],
  "wavelength-calculator": ["frequency-calculator", "rlc-resonance-calculator", "impedance-calculator"],
  "whitespace-remover": [],
  "wifi-password-generator": ["password-generator", "username-generator", "hash-generator"],
  "window-area-calculator": ["floor-area-calculator", "wall-area-calculator", "room-area-calculator"],
  "wire-size-calculator": ["voltage-drop-calculator", "circuit-breaker-calculator", "power-consumption-calculator"],
  "word-cloud-generator": ["word-frequency-counter", "keyword-density-checker"],
  "word-counter": ["word-frequency-counter", "paragraph-formatter", "text-reverser"],
  "word-frequency-counter": ["word-counter", "paragraph-formatter"],
  "workforce-requirement-calculator": ["labor-cost-calculator", "project-timeline-calculator", "construction-cost-estimator"],
  "working-days-calculator": ["date-difference-calculator", "time-duration-calculator"],
  "xml-to-json": ["json-validator", "find-and-replace"],
  "yaml-to-json-converter": ["json-formatter", "csv-to-json-converter", "xml-to-json"],
  "z-score-calculator": ["standard-deviation-calculator", "variance-calculator", "mean-calculator", "confidence-interval-calculator", "sample-size-calculator", "correlation-coefficient-calculator"],
  "zalgo-text-generator": ["word-counter", "text-reverser", "paragraph-formatter"],
  "zener-diode-calculator": ["diode-calculator", "led-resistor-calculator", "voltage-divider-calculator", "ohms-law-calculator"],
};
