export const palindromeCheckerConfig = {
  id: 'palindrome-checker',
  slug: 'palindrome-checker',
  name: 'Palindrome Checker',
  description: 'Check if words, phrases, or sentences read the same forward and backward with detailed analysis',
  category: 'text',
  icon: '🔄',
  keywords: [
    'palindrome checker',
    'palindrome tool',
    'check palindrome',
    'word palindrome',
    'sentence palindrome',
    'phrase palindrome checker',
    'bulk palindrome checker',
    'reverse text checker',
    'palindrome test online',
    'palindrome finder',
    'ignore punctuation palindrome',
    'ignore spaces palindrome',
    'palindrome analyzer',
    'text symmetry checker',
    'string palindrome validator',
    'palindrome frequency analysis',
    'real time palindrome checker',
    'free palindrome checker'
  ],
  seo: {
    title: 'Palindrome Checker Online - Single and Bulk Sentence Validation Tool',
    description: 'Free Palindrome Checker with single and bulk checks, similarity score, cleaned/reversed text analysis, frequency breakdown, and configurable ignore rules.',
    keywords: [
      'palindrome checker',
      'palindrome tool',
      'check palindrome',
      'word palindrome',
      'sentence palindrome',
      'phrase palindrome checker',
      'bulk palindrome checker',
      'reverse text checker',
      'palindrome test online',
      'palindrome finder',
      'ignore punctuation palindrome',
      'ignore spaces palindrome',
      'palindrome analyzer',
      'text symmetry checker',
      'string palindrome validator',
      'palindrome frequency analysis',
      'real time palindrome checker',
      'free palindrome checker',
      'palindrome checker for phrases',
      'bulk sentence palindrome check',
      'palindrome similarity calculator',
      'palindrome rules checker',
      'word puzzle palindrome tool',
      'online palindrome validator'
    ],
    openGraph: {
      title: 'Palindrome Checker - Rule-Based Text and Sentence Validation',
      description: 'Check words and phrases with configurable filters, bulk mode, and detailed palindrome diagnostics.',
      type: 'website',
      url: '/tools/writing/palindrome-checker',
    },
  },
};
