export const palindromeCheckerConfig = {
  id: 'palindrome-checker',
  slug: 'palindrome-checker',
  name: 'Palindrome Checker',
  description: 'Check if words, phrases, or sentences read the same forward and backward with detailed analysis',
  category: 'text',
  icon: '🔄',
  keywords: [
    'palindrome checker',
    'palindrome tool',
    'check palindrome',
    'word palindrome',
    'sentence palindrome',
    'phrase palindrome checker',
    'bulk palindrome checker',
    'reverse text checker',
    'palindrome test online',
    'palindrome finder',
    'ignore punctuation palindrome',
    'ignore spaces palindrome',
    'palindrome analyzer',
    'text symmetry checker',
    'string palindrome validator',
    'palindrome frequency analysis',
    'real time palindrome checker',
    'free palindrome checker'
  ],
  seo: {
    title: "Palindrome Checker – Words, Sentences & Bulk Lists",
    description: "Check whether words or sentences are palindromes, one at a time or in bulk, with the cleaned and reversed text, a similarity score and ignore rules.",
    keywords: [
      'palindrome checker',
      'palindrome tool',
      'check palindrome',
      'word palindrome',
      'sentence palindrome',
      'phrase palindrome checker',
      'bulk palindrome checker',
      'reverse text checker',
      'palindrome test online',
      'palindrome finder',
      'ignore punctuation palindrome',
      'ignore spaces palindrome',
      'palindrome analyzer',
      'text symmetry checker',
      'string palindrome validator',
      'palindrome frequency analysis',
      'real time palindrome checker',
      'free palindrome checker',
      'palindrome checker for phrases',
      'bulk sentence palindrome check',
      'palindrome similarity calculator',
      'palindrome rules checker',
      'word puzzle palindrome tool',
      'online palindrome validator'
    ],
    openGraph: {
      title: "Palindrome Checker – Words, Sentences & Bulk Lists",
      description: "Check whether words or sentences are palindromes, one at a time or in bulk, with the cleaned and reversed text, a similarity score and ignore rules.",
      type: 'website',
      url: '/tools/writing/palindrome-checker',
    },
    howToSteps: [
      { name: "Choose Single Check for one input or Bulk Check for multiple lines", text: "Choose Single Check for one input or Bulk Check for multiple lines." },
      { name: "Enter your word", text: "Enter your word, phrase, sentence, or line list." },
      { name: "Set options such as ignore case", text: "Set options such as ignore case, spaces, punctuation, or numbers." },
      { name: "Run the checker or enable real-time mode for live updates", text: "Run the checker or enable real-time mode for live updates." },
      { name: "Review the analysis and copy or download the result when needed", text: "Review the analysis and copy or download the result when needed." },
    ],
    faq: [
      { q: "What is a palindrome checker?", a: "A palindrome checker tests whether a word, phrase, or sentence reads the same forward and backward after applying selected cleanup rules." },
      { q: "Can this tool check full sentences and phrases?", a: "Yes. It supports phrase-level checks and can ignore spaces, punctuation, and case to evaluate natural-language palindromes accurately." },
      { q: "What is the difference between single and bulk mode?", a: "Single mode provides detailed analysis for one input. Bulk mode checks multiple lines at once and marks each line as palindrome or not." },
      { q: "How does real-time checking work?", a: "When real-time mode is enabled, the checker automatically updates results while you type so you do not need to click check repeatedly." },
      { q: "What does the similarity score mean?", a: "Similarity shows how closely the cleaned text matches its reversed form, even when the input is not a perfect palindrome." },
      { q: "Does this tool show cleaned and reversed text?", a: "Yes. The result panel shows original, cleaned, and reversed text so you can validate why a match passed or failed." },
      { q: "Can I check numbers as part of palindrome logic?", a: "Yes. You can keep numbers or enable ignore-numbers depending on whether numeric characters should affect the result." },
      { q: "Can I copy or download results?", a: "Yes. In single mode, you can copy a detailed report or download it as a TXT file for documentation and sharing." },
      { q: "Is my text private when using this tool?", a: "Yes. We do not collect or store what you enter." },
    ],
  },
};
