export const cssKeyframeAnimatorConfig = {
  slug: "css-keyframe-animator",
  name: "CSS Keyframe Animator",
  description: "Create CSS animations visually with timeline editor",
  category: "design",
  icon: "🎬",
  free: true,
  backend: false,
  seo: {
    title: "CSS Keyframe Animator – Visual Timeline Animation Generator | Productive Toolbox",
    description: "Create CSS @keyframes animations visually using a timeline editor. Generate production-ready CSS with live preview, presets, and export options. Free online tool.",
    keywords: [
      "css keyframe animator",
      "css animation generator",
      "keyframe generator",
      "css animation maker",
      "animation timeline editor",
      "css keyframes tool",
      "visual animation editor",
      "css animation builder",
      "keyframe animation tool",
      "css animation creator",
      "animation generator online",
      "css keyframes generator",
      "visual keyframe editor",
      "css animation designer",
      "keyframe timeline tool"
    ],
    openGraph: {
      title: "CSS Keyframe Animator – Visual Timeline Animation Generator",
      description: "Create CSS animations visually with timeline editor. Generate @keyframes instantly with live preview and presets.",
      type: "website",
      url: "/css-keyframe-animator"
    }
  },
  features: [
    "Visual timeline editor (0% to 100%)",
    "Add, drag, and delete keyframes",
    "Live animation preview",
    "Play/pause controls",
    "8 animation presets (Fade In, Slide Up, Bounce, Rotate, Pulse, Shake, Swing)",
    "Multi-property keyframes",
    "Transform controls (translateX, translateY, scale, rotate)",
    "Opacity control",
    "Background color animation",
    "Border radius animation",
    "Duration control (0.1s to 10s)",
    "Delay control (0s to 5s)",
    "Iteration count (1 to infinite)",
    "Animation direction (normal, reverse, alternate, alternate-reverse)",
    "Fill mode (none, forwards, backwards, both)",
    "Easing functions (linear, ease, ease-in, ease-out, ease-in-out)",
    "Preview element types (box, circle, text)",
    "Responsive viewport preview (mobile, tablet, desktop)",
    "Complete CSS export",
    "Keyframes-only export",
    "Animation shorthand export",
    "SCSS mixin export",
    "JSON export",
    "One-click copy to clipboard",
    "Download CSS file",
    "Real-time preview updates",
    "Snap to grid (5% increments)",
    "100% client-side processing"
  ]
};
