import { siteConfig } from "@/config/site";

export const hectareToAcreConverterConfig = {
  name: "Hectare to Acre Converter",
  slug: "hectare-to-acre-converter",
  description: "Convert hectares to acres and acres to hectares instantly. Free online land area converter with comprehensive reference table, precision control, and conversion history.",
  category: "land",
  icon: "🔄",
  free: true,
  backend: false,
  seo: {
    title: "Hectare to Acre Converter — Free ha to Acres Calculator | Productive Toolbox",
    description: "Convert hectares to acres instantly. Free ha to acres calculator with full reference table, reverse conversion, and common values. Browser-based, no signup.",
    keywords: [
      "hectare to acre converter",
      "hectares to acres",
      "ha to acres",
      "convert hectares to acres",
      "1 hectare to acre",
      "hectare to acre",
      "0.5 hectares to acres",
      "2.5 hectares to acres",
      "10 hectares to acres",
      "100 hectares to acres",
      "hectares in acres",
      "ha to ac",
      "acres to hectares",
      "acre to hectare",
      "convert acres to hectares",
      "1 hectare in acres",
      "hectare to acre calculator",
      "land area converter",
      "how many acres in a hectare",
      "how many hectares in an acre",
      "hectare acres conversion",
      "ha to acre calculator",
      "free hectare to acre converter",
      "metric to imperial land conversion",
      "hectare to acre formula",
    ],
    openGraph: {
      title: "Hectare to Acre Converter — Free ha to Acres Calculator",
      description: "Convert hectares to acres and acres to hectares instantly. Full reference table, precision control, reverse conversion. Browser-based, free.",
      type: "website",
      url: `${siteConfig.url}/tools/land/hectare-to-acre-converter`,
    },
    og: {
      title: "Hectare to Acre Converter — Free ha to Acres Calculator",
      description: "Convert hectares to acres and acres to hectares instantly. Full reference table, precision control, reverse conversion. Browser-based, free.",
      url: `${siteConfig.url}/tools/land/hectare-to-acre-converter`,
    },
    howToSteps: [
      { name: "Enter Your Hectare Value", text: "Type any number of hectares into the input field. Decimals are fully supported — for example, 0.5, 2.47, or 1000. The conversion result appears instantly as you type." },
      { name: "Read the Acre Result", text: "The acre equivalent appears immediately below the input. For a 1 hectare input, the result is 2.47105 acres. The result updates with every keystroke." },
      { name: "Adjust Decimal Precision", text: "Use the precision selector to choose 2, 4, 6, or 8 decimal places depending on how precise your conversion needs to be. 4 decimal places is suitable for most practical applications." },
      { name: "Use Presets for Common Values", text: "Click any preset button (0.5, 1, 5, 10, 50, 100 ha) to instantly load that value. Presets are ideal for quickly checking standard land parcel sizes without manual input." },
      { name: "Swap to Acres to Hectares", text: "Click the swap button to reverse the conversion direction — so you can enter acres and receive hectares. The same tool covers both ha to acres and acres to ha." },
      { name: "Copy or Export", text: "Click the copy button to copy the result to clipboard, or download a text report of your conversion history for documentation or client handoff." },
    ],
    faq: [
      { q: "How many acres is 1 hectare?", a: "1 hectare equals 2.47105 acres. This is derived from the exact definitions: 1 hectare = 10,000 square meters and 1 acre = 4,046.856 square meters. Dividing: 10,000 ÷ 4,046.856 = 2.47105." },
      { q: "How many hectares is 1 acre?", a: "1 acre equals 0.404686 hectares. This is the reciprocal of the hectare-to-acre factor: 1 ÷ 2.47105 = 0.404686. So 10 acres equals 4.04686 hectares." },
      { q: "Which is bigger — a hectare or an acre?", a: "A hectare is larger. 1 hectare = 2.47105 acres, meaning a hectare is about 2.47 times the size of an acre. A hectare is 10,000 square meters; an acre is 4,046.86 square meters." },
      { q: "How many acres is 0.5 hectares?", a: "0.5 hectares equals 1.23553 acres. Calculation: 0.5 × 2.47105 = 1.23553. Half a hectare is approximately 1.24 acres." },
      { q: "How many acres is 2.5 hectares?", a: "2.5 hectares equals 6.17763 acres. Calculation: 2.5 × 2.47105 = 6.17763." },
      { q: "How many acres is 10 hectares?", a: "10 hectares equals 24.7105 acres. Calculation: 10 × 2.47105 = 24.7105." },
      { q: "How many acres is 100 hectares?", a: "100 hectares equals 247.105 acres. 100 hectares is also 1 square kilometer. Calculation: 100 × 2.47105 = 247.105." },
      { q: "Where are hectares used vs acres?", a: "Hectares are the standard metric land unit used across most of Europe, Asia, Africa, and South America — and by international agricultural and environmental organizations. Acres are primarily used in the United States, United Kingdom, Canada, and a few other countries. Most international farming data, UN statistics, and European land records use hectares." },
      { q: "What is the hectare to acre formula?", a: "Acres = Hectares × 2.47105. For reverse conversion: Hectares = Acres × 0.404686. Both conversion factors are internationally standardized and used in all official land measurement systems." },
      { q: "Is my data private when using this converter?", a: "Yes. All conversions run entirely in your browser using JavaScript. Your inputs are never sent to any server, stored in any database, or accessible to anyone other than you." },
    ],
  },
  features: [
    "Instant ha to acres conversion",
    "Reverse conversion: acres to hectares",
    "2, 4, 6, and 8 decimal precision options",
    "Quick presets for common land sizes",
    "Comprehensive reference table",
    "Land size context descriptions",
    "Conversion history (last 10 entries)",
    "Copy result to clipboard",
    "Export conversion report",
    "100% browser-based — no data sent to server",
    "No registration required",
  ],
  relatedTools: [
    "acre-to-hectare-converter",
    "acre-to-square-feet-converter",
    "square-feet-to-acre-converter",
    "decimal-land-calculator",
    "land-area-calculator-square-meter",
    "land-price-calculator",
  ],
};
