import { siteConfig } from "@/config/site";

export const toolConfig = {
  slug: "bmi-calculator",
  name: "BMI Calculator",
  description: "Calculate your Body Mass Index (BMI) instantly with metric or imperial units. Get your BMI category, healthy weight range, and ideal weight estimates — free, no sign-up required.",
  category: "calculator",
  icon: "⚖️",
  free: true,
  backend: false,
  seo: {
    title: "BMI Calculator — Free Body Mass Index Calculator Online | Productive Toolbox",
    description: "Free BMI calculator with metric and imperial support. Instantly calculate your Body Mass Index, BMI category, healthy weight range, and ideal weight. No sign-up, 100% browser-based.",
    keywords: [
      "bmi calculator",
      "bmi calculator online",
      "body mass index calculator",
      "calculate bmi",
      "free bmi calculator",
      "bmi chart",
      "healthy bmi range",
      "bmi for women",
      "bmi for men",
      "bmi calculator metric",
      "bmi calculator imperial",
      "healthy weight calculator",
      "ideal weight calculator",
      "bmi categories",
      "normal bmi range",
      "overweight bmi",
      "obese bmi range",
      "bmi calculator kg cm",
      "bmi calculator lbs inches",
      "bmi calculator adults",
      "bmi and healthy weight range",
      "body weight index",
      "weight category calculator",
      "bmi scale",
      "calculate body mass index online",
    ],
    openGraph: {
      title: "BMI Calculator — Free Body Mass Index Calculator Online",
      description: "Instantly calculate BMI, check your category, healthy weight range, and ideal weight estimates. Free, metric and imperial, no sign-up.",
      type: "website",
      url: `${siteConfig.url}/tools/calculator/bmi-calculator`,
    },
  },
  features: [
    "Instant BMI calculation in metric (kg/cm) or imperial (lb/ft/in)",
    "BMI category with color-coded visual scale",
    "Healthy weight range based on your exact height",
    "Ideal weight estimates using Devine and Robinson formulas",
    "Interactive weight simulator to preview BMI changes",
    "Local history for repeat check-ins — no account needed",
    "100% browser-based — your data never leaves your device",
  ],
  relatedTools: [
    "body-fat-calculator",
    "bmr-calculator",
    "calorie-calculator",
    "ideal-weight-calculator",
    "waist-to-hip-ratio-calculator",
    "age-calculator",
  ],
};
