import { siteConfig } from "@/config/site";

export const landPriceCalculatorConfig = {
  name: "Land Price Calculator",
  slug: "land-price-calculator",
  description: "Calculate the total price of land from its area and the price per acre, square foot, square meter or hectare, with automatic unit conversion.",
  category: "land",
  icon: "💰",
  free: true,
  backend: false,
  seo: {
    title: "Land Price Calculator – Total Price per Acre or Sq Ft",
    description: "Work out the total price of land from its area and the price per acre, square foot, m² or hectare. Converts units automatically and compares two plots.",
    keywords: [
      "land price calculator",
      "land value calculator",
      "land cost calculator",
      "price per acre calculator",
      "land price per square foot",
      "land price per square meter",
      "land price per hectare",
      "lot price calculator",
      "acreage price calculator",
      "land rate calculator",
      "compare land prices",
    ],
    openGraph: {
      title: "Land Price Calculator – Total Price per Acre or Sq Ft",
      description: "Total land price from area and price per acre, sq ft, m² or hectare, with automatic unit conversion and a two-plot comparison.",
      type: "website",
      url: `${siteConfig.url}/tools/land/land-price-calculator`,
    },
    howToSteps: [
      { name: "Enter the land area", text: "Type the size of the plot in acres, square feet, square meters or hectares (Decimal, Katha and Bigha are also available)." },
      { name: "Choose the rate unit", text: "Pick the unit the price is quoted in. It can differ from the area unit: an area in acres with a price per square foot is converted automatically." },
      { name: "Enter the price per unit", text: "Type the price for one unit, such as 50,000 per acre or 120 per square foot, and choose USD, EUR, GBP, CAD or AUD." },
      { name: "Read the total", text: "See the total price, the converted area and the price at 25%, 50%, 75% and 100% of the area." },
      { name: "Compare two plots", text: "Switch to comparison mode to price two listings side by side and see which is cheaper and by how much." },
    ],
    faq: [
      { q: "How is the total price of land calculated?", a: "Total price = area × price per unit, after converting the area into the unit the price is quoted in. A 2.5 acre parcel at $48,000 per acre costs $120,000; a 0.25 acre lot priced at $11 per square foot is 10,890 sq ft × $11 = $119,790." },
      { q: "How do I convert a price per acre to a price per square foot?", a: "Divide by 43,560, the number of square feet in an acre. $50,000 per acre is $1.15 per sq ft; $10 per sq ft is $435,600 per acre. Per hectare, multiply the per-acre price by 2.471." },
      { q: "What affects the price of land?", a: "Location and access, zoning and what can be built, road frontage, utilities (water, sewer, power), topography, flood risk, lot size and recent comparable sales. Small building lots usually cost far more per square foot than large rural parcels." },
      { q: "How much is an acre of land worth?", a: "It varies enormously. The USDA put the average US farmland value at about $4,170 per acre in 2024, while residential lots in metro areas can exceed $500,000 per acre. In the UK, farmland averaged roughly £10,000 per acre. Use local listings and recent sales for real figures." },
      { q: "Which currencies can I use?", a: "US dollars, euros, pounds, Canadian dollars and Australian dollars. The calculator does not convert between currencies; the total is in the same currency as the rate you enter." },
      { q: "What are Decimal, Katha and Bigha?", a: "Traditional land units used in Bangladesh and eastern India: 1 Decimal = 435.6 sq ft (1/100 acre), 1 Katha = 720 sq ft and 1 Bigha = 14,400 sq ft. They are included for plots measured in those units; local values of Katha and Bigha vary." },
      { q: "Is my data private?", a: "Yes. Everything runs in your browser; nothing you enter is sent to a server. History is saved only in your browser's local storage." },
    ],
  },
  features: [
    "Total land price from area and rate per unit",
    "Automatic unit conversion when area and rate units differ",
    "Supports acres, square feet, square meters, hectares, Decimal, Katha and Bigha",
    "Currencies: USD, EUR, GBP, CAD, AUD",
    "Price breakdown at 25%, 50%, 75%, 100% area",
    "Comparison mode for two deals side by side",
    "Real-time results as you type",
    "Save and export calculation history",
    "100% browser-based — no data sent to any server",
    "No registration required",
  ],
  relatedTools: [
    "decimal-land-calculator",
    "land-valuation-calculator",
    "land-area-calculator-square-meter",
    "katha-land-calculator",
    "price-per-square-feet-calculator",
    "land-development-cost-calculator",
  ],
};
