export const cuttingSpeedCalculatorConfig = {
  name: "Cutting Speed Calculator",
  slug: "cutting-speed-calculator",
  description: "Calculate machining cutting speed, spindle RPM, feed rate, and machining time for milling, turning, drilling, and CNC operations. Supports metric and imperial units.",
  category: "mechanical",
  icon: "⚙️",
  free: true,
  seo: {
    title: "Free Cutting Speed Calculator – Machining Speed & RPM Calculator Online",
    description: "Calculate machining cutting speed, spindle RPM, feed rate, and machining values instantly. Free online cutting speed calculator for CNC, milling, turning, and drilling operations.",
    keywords: [
      "cutting speed calculator",
      "machining speed calculator",
      "RPM calculator CNC",
      "spindle speed calculator",
      "milling cutting speed calculator",
      "machining RPM calculator",
      "CNC feed speed calculator",
      "surface speed calculator",
      "cutting speed formula",
      "machining calculator online",
      "CNC machining calculator",
      "turning speed calculator",
      "drilling speed calculator",
      "feed rate calculator",
      "machining time calculator",
    ],
    og: {
      title: "Free Cutting Speed Calculator – Machining Speed & RPM Calculator Online",
      description: "Calculate machining cutting speed, spindle RPM, feed rate, and machining time instantly. Free online calculator for CNC, milling, turning, and drilling operations.",
      url: "https://www.engineeringcalcs.com/tools/mechanical/cutting-speed-calculator",
    },
  },
  relatedTools: [
    "torque-calculator",
    "gear-ratio-calculator",
    "angular-velocity-calculator",
    "force-calculator",
    "reynolds-number-calculator",
    "flow-rate-calculator",
  ],
};
