export const averageCalculatorConfig = {
  slug: "average-calculator",
  name: "Average Calculator",
  description: "Free online Average Calculator to find the arithmetic mean of a list of numbers instantly. Paste values from Excel or CSV and get average, sum, count, min, and max in real time.",
  category: "calculator",
  icon: "🔢",
  free: true,
  backend: false,
  seo: {
    howToSteps: [
      { name: "Paste or type your numbers", text: "Enter the values in the box, separated by commas, spaces or new lines. You can paste a row or column straight from Excel or Google Sheets." },
      { name: "Read the average", text: "The mean appears as you type, with the sum, count, minimum and maximum of your list." },
      { name: "Check what was counted", text: "Anything that is not a number, such as a header or a currency sign on its own, is skipped, so compare the count with the number of values you meant to enter." },
      { name: "Copy or export", text: "Copy the result, or download your values and their average as a CSV file." },
    ],
    faq: [
      { q: "How do you calculate an average?", a: "Add all the numbers and divide by how many there are. For 4, 8, 15, 16, 23 and 42 the sum is 108 and there are 6 numbers, so the average (arithmetic mean) is 108 ÷ 6 = 18." },
      { q: "Is the average the same as the mean?", a: "In everyday use, yes: \"average\" usually means the arithmetic mean. Statisticians also call the median and the mode averages, because each describes a typical value in a different way." },
      { q: "What is the difference between mean and median?", a: "The mean adds everything and divides by the count; the median is the middle value once the list is sorted. One very large or small value pulls the mean but barely moves the median, which is why incomes and house prices are usually reported as medians." },
      { q: "How do I calculate a weighted average?", a: "Multiply each value by its weight, add the results, and divide by the sum of the weights. A grade of 90 worth 60% and 80 worth 40% gives (90 × 0.6 + 80 × 0.4) ÷ 1.0 = 86." },
      { q: "Can I paste data from Excel or Google Sheets?", a: "Yes. Copy a row or a column and paste it into the box. Commas, tabs, spaces and line breaks all work as separators, and decimals and negative numbers are supported. Write thousands without a comma separator (1000, not 1,000)." },
      { q: "Can I export the result?", a: "Yes. The CSV export downloads your numbered values and their average, ready to open in a spreadsheet." },
      { q: "Is my data private?", a: "Yes. The calculation runs in your browser and your numbers are not sent anywhere." },
    ],
    title: "Average Calculator – Mean of a List of Numbers",
    description: "Find the average (mean) of any list of numbers, pasted with commas, spaces or new lines, along with the sum, count, minimum and maximum.",
    keywords: [
      "average calculator",
      "mean calculator",
      "arithmetic mean",
      "calculate average",
      "average of numbers",
      "mean of numbers",
      "how to find average",
      "average formula",
      "marks average calculator",
      "grade average calculator",
      "number average calculator",
      "dataset average calculator",
      "statistics average calculator",
      "average calculator with steps",
      "excel average alternative",
      "online mean finder",
      "sum and average calculator",
      "average calculator with csv",
      "best average calculator",
      "online calculator",
      "free calculator",
      "math calculator",
      "statistics calculator",
      "data analysis"
    ],
    openGraph: {
      title: "Average Calculator Online - Find Mean of Numbers Instantly",
      description: "Calculate average instantly from any list of numbers. Paste from Excel, copy results, and export CSV with no signup.",
      type: "website",
      url: "/tools/average-calculator"
    }
  },
  features: [
    "Calculate average (mean) instantly",
    "Real-time calculation as you type",
    "Smart number parsing (comma, space, newline)",
    "Copy result to clipboard",
    "Export results as CSV",
    "Paste from Excel or CSV",
    "Clear input with one click",
    "Mobile-responsive design",
    "100% client-side processing",
    "No backend or API required"
  ]
};
