export const averageCalculatorConfig = {
  slug: "average-calculator",
  name: "Average Calculator",
  description: "Free online Average Calculator to find the arithmetic mean of a list of numbers instantly. Paste values from Excel or CSV and get average, sum, count, min, and max in real time.",
  category: "calculator",
  icon: "🔢",
  free: true,
  backend: false,
  seo: {
    howToSteps: [
      { name: "Paste or type your numbers", text: "Enter the values separated by commas, spaces or new lines, or paste a row or column from Excel or Google Sheets. Figures like 1,000 or $25 are read as numbers." },
      { name: "Read the average and statistics", text: "The mean appears as you type, with the count, sum, minimum, maximum, median, mode, range and standard deviation." },
      { name: "Add weights if some values count more", text: "Tick Weighted average and enter one weight per value in the same order, such as 0.6 and 0.4 for an exam and coursework; the weighted mean appears under the average." },
      { name: "Copy or export", text: "Copy all the results, or download your values with the count, sum, average, median and standard deviation as a CSV file." },
    ],
    faq: [
      { q: "How do you calculate an average?", a: "Add all the numbers and divide by how many there are. For 4, 8, 15, 16, 23 and 42 the sum is 108 and there are 6 numbers, so the average (arithmetic mean) is 108 ÷ 6 = 18." },
      { q: "Is the average the same as the mean?", a: "In everyday use, yes: \"average\" usually means the arithmetic mean. Statisticians also call the median and the mode averages, because each describes a typical value in a different way." },
      { q: "What is the difference between mean and median?", a: "The mean adds everything and divides by the count; the median is the middle value once the list is sorted. One very large or small value pulls the mean but barely moves the median, which is why incomes and house prices are usually reported as medians." },
      { q: "How do I calculate a weighted average?", a: "Multiply each value by its weight, add the results, and divide by the sum of the weights. A grade of 90 worth 60% and 80 worth 40% gives (90 × 0.6 + 80 × 0.4) ÷ 1.0 = 86. Tick Weighted average in the calculator and enter the weights in the same order as the values." },
      { q: "Can I paste data from Excel or Google Sheets?", a: "Yes. Copy a row or a column and paste it into the box. Tabs, spaces, line breaks, semicolons and commas all separate values, numbers written with thousands separators such as 1,000 or 12,345.67 are read as one number, and a leading $, €, £ or a trailing % is ignored." },
      { q: "Can I export the result?", a: "Yes. The CSV export downloads your numbered values followed by the count, sum, average, median and sample standard deviation, ready to open in a spreadsheet." },
      { q: "Is my data private?", a: "Yes. The calculation runs in your browser and your numbers are not sent anywhere." },
      { q: "What is the difference between sample and population standard deviation?", a: "Both measure how spread out the values are. Use the population figure, which divides by n, when your list is the whole group, such as every student in one class. Use the sample figure, which divides by n − 1, when your list is a sample from a larger group; it is slightly larger to allow for that." },
    ],
    title: "Average Calculator – Mean, Median, Mode & Std Deviation",
    description: "Find the average of a list of numbers, plus median, mode, range, standard deviation and weighted average. Paste from Excel; 1,000-style numbers work.",
    keywords: [
      "average calculator",
      "mean calculator",
      "arithmetic mean",
      "calculate average",
      "average of numbers",
      "mean of numbers",
      "how to find average",
      "average formula",
      "marks average calculator",
      "grade average calculator",
      "number average calculator",
      "dataset average calculator",
      "statistics average calculator",
      "average calculator with steps",
      "excel average alternative",
      "online mean finder",
      "sum and average calculator",
      "average calculator with csv",
      "best average calculator",
      "online calculator",
      "free calculator",
      "math calculator",
      "statistics calculator",
      "data analysis"
    ],
    openGraph: {
      title: "Average Calculator Online - Find Mean of Numbers Instantly",
      description: "Calculate average instantly from any list of numbers. Paste from Excel, copy results, and export CSV with no signup.",
      type: "website",
      url: "/tools/average-calculator"
    }
  },
  features: [
    "Calculate average (mean) instantly",
    "Real-time calculation as you type",
    "Smart number parsing (comma, space, newline)",
    "Copy result to clipboard",
    "Export results as CSV",
    "Paste from Excel or CSV",
    "Clear input with one click",
    "Mobile-responsive design",
    "100% client-side processing",
    "No backend or API required"
  ]
};
