export const fractionCalculatorConfig = {
  slug: "fraction-calculator",
  name: "Fraction Calculator",
  description: "Add, subtract, multiply, and divide fractions with automatic simplification and mixed number conversion",
  category: "calculator",
  icon: "➗",
  free: true,
  backend: false,
  seo: {
    title: "Fraction Calculator with Steps – Add, Subtract, Multiply",
    description: "Add, subtract, multiply and divide fractions and mixed numbers with step-by-step working, automatic simplification and a decimal answer.",
    keywords: [
      "fraction calculator",
      "fraction calculator with steps",
      "online fraction calculator",
      "free fraction calculator",
      "add fractions",
      "subtract fractions",
      "multiply fractions",
      "divide fractions",
      "simplify fractions",
      "simplify fraction calculator",
      "fractions in simplest form",
      "mixed number calculator",
      "improper fraction to mixed number",
      "fraction to decimal",
      "decimal to fraction calculator",
      "adding fractions with unlike denominators",
      "fraction math solver",
      "fraction problem calculator",
      "fraction arithmetic calculator",
      "fraction operations calculator",
      "fraction math calculator"
    ],
    openGraph: {
      title: "Fraction Calculator with Steps – Add, Subtract, Multiply & Divide Fractions",
      description: "Perform fraction operations with simplification, mixed numbers, decimals, and optional step-by-step output.",
      type: "website",
      url: "/tools/fraction-calculator"
    },
    howToSteps: [
      { name: "Enter numerator and denominator for Fraction A", text: "Enter numerator and denominator for Fraction A." },
      { name: "Enter numerator and denominator for Fraction B", text: "Enter numerator and denominator for Fraction B." },
      { name: "Choose add", text: "Choose add, subtract, multiply, or divide." },
      { name: "Review simplified fraction", text: "Review simplified fraction, mixed number, and decimal output." },
      { name: "Turn on steps", text: "Turn on steps, copy result text, or reuse values from history." },
    ],
    faq: [
      { q: "How do I add fractions with different denominators?", a: "The calculator finds a common denominator, adjusts each numerator, adds the values, and then simplifies the final fraction automatically." },
      { q: "Can this tool simplify fractions to lowest terms?", a: "Yes. Every result is reduced using a greatest common divisor method, so you get a clean simplified answer by default." },
      { q: "Does it convert improper fractions to mixed numbers?", a: "Yes. When the result is improper, the tool also shows a mixed number view so the output is easier to read and use in classwork or real-world tasks." },
      { q: "Can I see decimal values from fraction results?", a: "Yes. The result panel can display a decimal form alongside the fraction and mixed number, useful for conversion and quick comparison." },
      { q: "Does this fraction calculator show step-by-step math?", a: "Yes. Enable the steps option to see each operation line, including intermediate expressions and simplification." },
      { q: "Is the calculator free and private?", a: "Yes. It is free to use, and we do not collect or store what you enter." },
    ],
  },
  features: [
    "Add, subtract, multiply, and divide fractions",
    "Automatic fraction simplification using GCD",
    "Convert to mixed numbers",
    "Convert to decimal values",
    "Step-by-step calculation display",
    "Visual fraction representation",
    "Calculation history",
    "Copy results to clipboard",
    "Random fraction generator",
    "Keyboard navigation support",
    "Mobile-responsive design",
    "Input validation",
    "Private: your inputs are not collected or stored"
  ]
};
