/**
 * Regenerates config/content-dates.ts: the date each page's content last
 * changed, used for the sitemap's <lastmod> (#17).
 *
 * A tool's date is the last commit touching its seo-content.tsx or config.ts —
 * the copy and metadata Google reads. UI and logic refactors do not count.
 * Mechanical commits that should not bump a date are skipped: either listed in
 * IGNORE_COMMITS, or — preferred, since rebase-merging rewrites hashes — with
 * "[no-content-date]" anywhere in the commit message.
 *
 * Git history is read here, at development time, rather than during the build:
 * Vercel builds from a shallow clone, where it is not reliable.
 *
 * Usage: node scripts/content-dates.mjs   (then commit config/content-dates.ts)
 */
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = 'config/content-dates.ts';

/* Mechanical commits that touched content files without changing the content. */
const IGNORE_COMMITS = new Set([
  '04b0ed3', // www → non-www URL in power-consumption-calculator's JSON-LD
]);

/* Squash merges whose message carries "[no-content-date]" from some of the
   squashed commits while others did change content: they still count. */
const CONTENT_COMMITS = new Set([
  '4ca317d', // #75: rewrote the electric bill calculator's content
]);

/* Standalone pages whose content lives in one file. */
const PAGES = {
  '/': 'app/page.tsx',
  '/tools': 'app/tools/page.tsx',
  '/about': 'app/about/page.tsx',
  '/contact': 'app/contact/page.tsx',
  '/privacy': 'app/privacy/page.tsx',
  '/terms': 'app/terms/page.tsx',
};

const git = (...args) => execFileSync('git', args, { cwd: ROOT, encoding: 'utf8' }).trim();

if (git('rev-parse', '--is-shallow-repository') === 'true') {
  console.error('content-dates: shallow clone — run `git fetch --unshallow` first.');
  process.exit(1);
}

/* Files edited but not yet committed count as changed today, so the usual
   order — edit, regenerate, commit both together — records the new date. */
const today = new Date().toISOString().slice(0, 10);
const uncommitted = new Set(
  git('status', '--porcelain', '--', 'tools', 'app')
    .split('\n')
    .filter(Boolean)
    .map((l) => l.slice(3).trim())
);

/** Commit date (YYYY-MM-DD) of the newest non-ignored commit touching `files`. */
function lastChanged(files) {
  const existing = files.filter((f) => fs.existsSync(path.join(ROOT, f)));
  if (!existing.length) return null;
  if (existing.some((f) => uncommitted.has(f))) return today;
  const tagged = new Set(
    git('log', '--format=%h', '--fixed-strings', '--grep=[no-content-date]', '--', ...existing)
      .split('\n')
      .filter(Boolean)
      .map((h) => h.slice(0, 7))
  );
  const log = git('log', '--format=%h %cs', '--', ...existing);
  for (const line of log.split('\n')) {
    const [hash, date] = line.split(' ');
    if (!hash) continue;
    const short = hash.slice(0, 7);
    if (IGNORE_COMMITS.has(short)) continue;
    if (tagged.has(short) && !CONTENT_COMMITS.has(short)) continue;
    return date;
  }
  return null;
}

const tools = {};
for (const dir of fs.readdirSync(path.join(ROOT, 'tools')).sort()) {
  const cfg = path.join('tools', dir, 'config.ts');
  if (!fs.existsSync(path.join(ROOT, cfg))) continue;
  const slug = fs.readFileSync(path.join(ROOT, cfg), 'utf8').match(/slug:\s*["']([^"']+)["']/)?.[1];
  if (!slug) continue;
  const date = lastChanged([path.join('tools', dir, 'seo-content.tsx'), cfg]);
  if (date) tools[slug] = date;
}

const pages = {};
for (const [route, file] of Object.entries(PAGES)) {
  const date = lastChanged([file]);
  if (date) pages[route] = date;
}

const body = (obj) => Object.entries(obj).map(([k, v]) => `  ${JSON.stringify(k)}: "${v}",`).join('\n');
fs.writeFileSync(path.join(ROOT, OUT), `/* Generated by scripts/content-dates.mjs — do not edit by hand.
   Regenerate and commit after changing a tool's seo-content.tsx or config.ts.

   Server-only: imported by the sitemap. Keep it out of client components —
   config/tools.ts ships to the browser, this file must not. */

/** Tool slug → date its content (seo-content.tsx / config.ts) last changed. */
export const TOOL_CONTENT_DATES: Record<string, string> = {
${body(tools)}
};

/** Standalone page route → date its content last changed. */
export const PAGE_CONTENT_DATES: Record<string, string> = {
${body(pages)}
};
`);
console.log(`content-dates: ${Object.keys(tools).length} tools, ${Object.keys(pages).length} pages → ${OUT}`);
