export const toolConfig = {
  slug: "css-button-generator",
  name: "CSS Button Style Generator",
  description: "Design a button visually with color, border-radius, shadow, and hover effects. Get copy-ready CSS.",
  category: "design",
  icon: "🔘",
  free: true,
  backend: false,
  seo: {
    title: "CSS Button Generator – Design Buttons, Copy CSS & Tailwind",
    description: "Design a button with colors, padding, radius, border, shadow and hover color in a live preview, then copy the CSS or matching Tailwind classes.",
    keywords: [
      "css button generator",
      "button css generator",
      "tailwind button generator",
      "button style generator",
      "create css button online",
      "button designer",
      "css button maker",
      "button hover effects",
      "custom button css",
      "button shadow generator",
      "responsive button css",
      "modern button styles",
      "ui button generator",
      "web button creator",
      "button css code",
      "interactive button designer",
      "button styling tool",
      "css button builder",
      "button animation css",
      "gradient button generator"
    ],
    openGraph: {
      title: "CSS Button Generator – Design Buttons, Copy CSS & Tailwind",
      description: "Design a button with colors, padding, radius, border, shadow and hover color in a live preview, then copy the CSS or matching Tailwind classes.",
      type: "website",
      url: "https://productivetoolbox.com/tools/design/css-button-generator"
    },
    howToSteps: [
      { name: "Start from a preset", text: "Pick Primary, Success, Danger, Ghost or Pill, or start from the default button." },
      { name: "Style the button", text: "Set the text, background and text colors, font size (12–28 px), padding, border radius (0–50 px), border width, style and color, and the shadow." },
      { name: "Set the hover effect", text: "Choose the hover background, which is suggested as a darker shade of the button color, and the transition time, then hover over the preview or toggle the hover state to check it." },
      { name: "Copy the code", text: "Copy the CSS, which includes the hover and keyboard focus styles, or the equivalent Tailwind classes." },
    ],
    faq: [
      { q: "Can I use the generated CSS in production?", a: "Yes. It uses standard properties supported by every current browser: background, color, padding, border-radius, border, box-shadow and transition, plus :hover and :focus-visible states. Rename the button selector to a class such as .btn-primary so it does not style every button on the site." },
      { q: "Do the Tailwind classes need any configuration?", a: "No. Custom colors and sizes are written as arbitrary values such as bg-[#3b82f6], px-[20px] and rounded-[8px], which Tailwind CSS v3 and v4 generate on demand, so the classes reproduce the preview exactly." },
      { q: "How do I make a button accessible?", a: "Use a real <button> element (or <a> for links), give the text a contrast ratio of at least 4.5:1 against the background, keep a visible focus outline for keyboard users, and make the button at least 24 × 24 CSS pixels, or 44 × 44 for touch." },
      { q: "How much padding and radius should a button have?", a: "Common values are 8–12 px vertical and 16–24 px horizontal padding, with a radius of 4–8 px for a modern look or 9999 px for a pill. Use the same values for every button in a design system." },
      { q: "What transition duration looks best?", a: "Between 150 and 300 ms. Shorter feels abrupt and longer feels sluggish. Transition color and background changes; avoid animating width, height or padding, which forces the page to re-layout." },
      { q: "Are my button designs saved?", a: "No. We do not collect or store what you enter." },
    ],
  },
  features: [
    "Live button preview",
    "Background & text colors",
    "Border radius control",
    "Padding adjustment",
    "Font size control",
    "Border styling",
    "Box shadow effects",
    "Hover state preview",
    "Transition animations",
    "Copy CSS code",
    "Copy Tailwind classes",
    "Button presets",
    "Responsive preview",
    "Private: your inputs are not collected or stored"
  ]
};