"use client";

import { useState, useEffect, useCallback, useRef } from "react";
import {
  calculateCTR,
  validateInputs,
  formatNumber,
  parseNumber,
  saveHistory,
  getHistory,
  clearHistory,
  debounce,
  buildShareUrl,
  parseShareParams,
  type CTRResult,
  type HistoryEntry,
} from "./logic";
import CTRCalculatorSEO from "./seo-content";
import RelatedTools from "@/components/RelatedTools";

const PRESETS = [
  { label: "150 / 5,000", clicks: 150, impressions: 5000 },
  { label: "2,350 / 72,800", clicks: 2350, impressions: 72800 },
  { label: "500 / 10,000", clicks: 500, impressions: 10000 },
  { label: "1,000 / 25,000", clicks: 1000, impressions: 25000 },
  { label: "80 / 20,000", clicks: 80, impressions: 20000 },
];

const PERFORMANCE_STYLES: Record<
  CTRResult["performanceLevel"],
  { bg: string; text: string; border: string; dot: string }
> = {
  excellent: {
    bg: "bg-green-50",
    text: "text-green-700",
    border: "border-green-200",
    dot: "bg-green-500",
  },
  good: {
    bg: "bg-blue-50",
    text: "text-blue-700",
    border: "border-blue-200",
    dot: "bg-blue-500",
  },
  average: {
    bg: "bg-yellow-50",
    text: "text-yellow-700",
    border: "border-yellow-200",
    dot: "bg-yellow-500",
  },
  low: {
    bg: "bg-orange-50",
    text: "text-orange-700",
    border: "border-orange-200",
    dot: "bg-orange-500",
  },
  "very-low": {
    bg: "bg-red-50",
    text: "text-red-700",
    border: "border-red-200",
    dot: "bg-red-400",
  },
};

export default function CTRCalculatorUI() {
  const [clicks, setClicks] = useState("150");
  const [impressions, setImpressions] = useState("5000");
  const [decimalPlaces, setDecimalPlaces] = useState(2);
  const [result, setResult] = useState<CTRResult | null>(null);
  const [clicksError, setClicksError] = useState<string | null>(null);
  const [impressionsError, setImpressionsError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [showHistory, setShowHistory] = useState(false);
  const [history, setHistory] = useState<HistoryEntry[]>([]);
  const [shareCopied, setShareCopied] = useState(false);
  const clicksRef = useRef<HTMLInputElement>(null);

  // Load history and parse share URL on mount
  useEffect(() => {
    setHistory(getHistory());
    const shared = parseShareParams();
    if (shared) {
      setClicks(shared.clicks);
      setImpressions(shared.impressions);
    } else {
      clicksRef.current?.focus();
    }
  }, []);

  const run = useCallback(
    debounce((c: string, imp: string, dp: number) => {
      const { clicksError: ce, impressionsError: ie } = validateInputs(c, imp);
      setClicksError(ce);
      setImpressionsError(ie);
      if (ce || ie) {
        setResult(null);
        return;
      }
      const cv = parseNumber(c);
      const iv = parseNumber(imp);
      if (cv === null || iv === null) {
        setResult(null);
        return;
      }
      setResult(calculateCTR(cv, iv, dp));
    }, 120),
    []
  );

  useEffect(() => {
    run(clicks, impressions, decimalPlaces);
  }, [clicks, impressions, decimalPlaces, run]);

  const handlePreset = (p: (typeof PRESETS)[0]) => {
    setClicks(String(p.clicks));
    setImpressions(String(p.impressions));
    clicksRef.current?.focus();
  };

  const handleReset = () => {
    setClicks("150");
    setImpressions("5000");
    setResult(null);
    setClicksError(null);
    setImpressionsError(null);
    clicksRef.current?.focus();
  };

  const handleCopyResult = () => {
    if (!result) return;
    navigator.clipboard.writeText(result.ctrFormatted);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleCopyFull = () => {
    if (!result) return;
    const text = [
      `CTR Calculator Result`,
      `=====================`,
      `Clicks:      ${formatNumber(result.clicks)}`,
      `Impressions: ${formatNumber(result.impressions)}`,
      `Formula:     ${result.formula}`,
      `CTR:         ${result.ctrFormatted}`,
      `Performance: ${result.performanceLabel}`,
    ].join("\n");
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadTxt = () => {
    if (!result) return;
    const text = [
      `CTR Calculator Report`,
      `=====================`,
      ``,
      `Clicks:      ${formatNumber(result.clicks)}`,
      `Impressions: ${formatNumber(result.impressions)}`,
      `Formula:     ${result.formula}`,
      `CTR:         ${result.ctrFormatted}`,
      `Performance: ${result.performanceLabel}`,
      ``,
      `Generated by Productive Toolbox`,
    ].join("\n");
    const blob = new Blob([text], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `ctr_${result.clicks}_${result.impressions}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadCsv = () => {
    if (!result) return;
    const csv = [
      "Clicks,Impressions,CTR,Performance",
      `${result.clicks},${result.impressions},${result.ctrFormatted},${result.performanceLabel}`,
    ].join("\n");
    const blob = new Blob([csv], { type: "text/csv" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `ctr_${result.clicks}_${result.impressions}.csv`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleShare = () => {
    if (!result) return;
    const url = buildShareUrl(result.clicks, result.impressions);
    navigator.clipboard.writeText(url);
    setShareCopied(true);
    setTimeout(() => setShareCopied(false), 2000);
  };

  const handleSave = () => {
    if (!result) return;
    saveHistory({ clicks: result.clicks, impressions: result.impressions, result });
    setHistory(getHistory());
  };

  const handleClearHistory = () => {
    if (confirm("Clear all calculation history?")) {
      clearHistory();
      setHistory([]);
    }
  };

  const loadFromHistory = (entry: HistoryEntry) => {
    setClicks(String(entry.clicks));
    setImpressions(String(entry.impressions));
    setShowHistory(false);
  };

  const perfStyle = result ? PERFORMANCE_STYLES[result.performanceLevel] : null;

  return (
    <>
      <div className="max-w-5xl mx-auto space-y-6">

        {/* Info Banner */}
        <div className="bg-blue-50 border border-blue-100 rounded-xl p-4 flex items-start gap-3">
          <span className="text-xl mt-0.5">📊</span>
          <div>
            <h3 className="text-sm font-semibold text-blue-900" style={{ fontFamily: "var(--font-heading)" }}>
              Click-Through Rate (CTR) Calculator
            </h3>
            <p className="text-sm text-blue-700 mt-0.5" style={{ fontFamily: "var(--font-body)" }}>
              Enter your clicks and impressions to instantly calculate CTR. All calculations run locally in your browser — no data is sent anywhere.
            </p>
          </div>
        </div>

        <div className="grid lg:grid-cols-12 gap-6">

          {/* Left: Controls */}
          <div className="lg:col-span-4 space-y-5">

            {/* Input Panel */}
            <div className="bg-white rounded-xl border border-gray-100 shadow-sm p-5 space-y-4">
              <h3 className="text-sm font-semibold text-gray-800" style={{ fontFamily: "var(--font-heading)" }}>
                Campaign Data
              </h3>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1.5" htmlFor="ctr-clicks">
                  Clicks
                </label>
                <input
                  ref={clicksRef}
                  id="ctr-clicks"
                  type="number"
                  min="0"
                  value={clicks}
                  onChange={(e) => setClicks(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && run(clicks, impressions, decimalPlaces)}
                  className={`w-full px-3 py-2.5 border-2 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent text-sm ${
                    clicksError ? "border-red-300" : "border-gray-200"
                  }`}
                  placeholder="150"
                  aria-label="Number of clicks"
                  aria-describedby={clicksError ? "clicks-error" : undefined}
                  inputMode="numeric"
                />
                {clicksError && (
                  <p id="clicks-error" className="text-xs text-red-600 mt-1" role="alert">
                    {clicksError}
                  </p>
                )}
                <p className="text-xs text-gray-400 mt-1">
                  Number of times users clicked
                </p>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1.5" htmlFor="ctr-impressions">
                  Impressions
                </label>
                <input
                  id="ctr-impressions"
                  type="number"
                  min="1"
                  value={impressions}
                  onChange={(e) => setImpressions(e.target.value)}
                  onKeyDown={(e) => e.key === "Enter" && run(clicks, impressions, decimalPlaces)}
                  className={`w-full px-3 py-2.5 border-2 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent text-sm ${
                    impressionsError ? "border-red-300" : "border-gray-200"
                  }`}
                  placeholder="5000"
                  aria-label="Number of impressions"
                  aria-describedby={impressionsError ? "impressions-error" : undefined}
                  inputMode="numeric"
                />
                {impressionsError && (
                  <p id="impressions-error" className="text-xs text-red-600 mt-1" role="alert">
                    {impressionsError}
                  </p>
                )}
                <p className="text-xs text-gray-400 mt-1">
                  Number of times content was shown
                </p>
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1.5" htmlFor="ctr-decimal">
                  Decimal Places
                </label>
                <select
                  id="ctr-decimal"
                  value={decimalPlaces}
                  onChange={(e) => setDecimalPlaces(Number(e.target.value))}
                  className="w-full px-3 py-2.5 border-2 border-gray-200 rounded-lg focus:ring-2 focus:ring-primary focus:border-transparent text-sm bg-white"
                  aria-label="Decimal precision"
                >
                  {[0, 1, 2, 3, 4].map((d) => (
                    <option key={d} value={d}>{d} decimal{d !== 1 ? "s" : ""}</option>
                  ))}
                </select>
              </div>

              <p className="text-xs text-gray-400">
                Press <kbd className="px-1 py-0.5 bg-gray-100 rounded text-xs font-mono">Enter</kbd> to recalculate
              </p>

              <div className="space-y-2 pt-1">
                <button
                  onClick={handleReset}
                  className="w-full px-4 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg text-sm font-medium transition-colors"
                >
                  Reset
                </button>
                <div className="grid grid-cols-2 gap-2">
                  <button
                    onClick={handleDownloadTxt}
                    disabled={!result}
                    className="px-3 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg text-xs font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    Export TXT
                  </button>
                  <button
                    onClick={handleDownloadCsv}
                    disabled={!result}
                    className="px-3 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg text-xs font-medium transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    Export CSV
                  </button>
                </div>
                <button
                  onClick={() => setShowHistory(!showHistory)}
                  className="w-full px-4 py-2 bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg text-sm font-medium transition-colors"
                >
                  {showHistory ? "Hide" : "Show"} History
                </button>
              </div>
            </div>

            {/* Result Summary Card */}
            <div className="bg-primary rounded-xl border border-primary shadow-lg shadow-primary/20 p-5 text-white">
              <p className="text-primary-100 text-xs font-semibold uppercase tracking-wider mb-2" style={{ fontFamily: "var(--font-heading)" }}>
                Result
              </p>
              {result ? (
                <>
                  <div className="text-4xl font-bold font-mono mb-1 tabular-nums">
                    {result.ctrFormatted}
                  </div>
                  <div className="text-sm text-primary-100 mb-1 font-mono">
                    {result.formula}
                  </div>
                  {perfStyle && (
                    <div className="flex items-center gap-2 mb-4 mt-2">
                      <span className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full text-xs font-semibold ${perfStyle.bg} ${perfStyle.text} ${perfStyle.border} border`}>
                        <span className={`w-1.5 h-1.5 rounded-full ${perfStyle.dot}`} />
                        {result.performanceLabel}
                      </span>
                    </div>
                  )}
                  <div className="border-t border-white/20 pt-3 space-y-1 text-sm mb-4">
                    <div className="flex justify-between">
                      <span className="text-primary-100">Clicks</span>
                      <span className="font-semibold font-mono">{formatNumber(result.clicks)}</span>
                    </div>
                    <div className="flex justify-between">
                      <span className="text-primary-100">Impressions</span>
                      <span className="font-semibold font-mono">{formatNumber(result.impressions)}</span>
                    </div>
                  </div>
                  <div className="space-y-2">
                    <button
                      onClick={handleCopyResult}
                      className="w-full bg-white text-primary font-semibold py-2 rounded-lg hover:bg-gray-50 transition-colors text-sm"
                    >
                      {copied ? "✓ Copied!" : "Copy CTR"}
                    </button>
                    <div className="grid grid-cols-2 gap-2">
                      <button
                        onClick={handleCopyFull}
                        className="border border-white/30 text-white font-medium py-2 rounded-lg hover:bg-white/10 transition-colors text-xs"
                      >
                        Copy All
                      </button>
                      <button
                        onClick={handleShare}
                        className="border border-white/30 text-white font-medium py-2 rounded-lg hover:bg-white/10 transition-colors text-xs"
                      >
                        {shareCopied ? "✓ Copied!" : "Share URL"}
                      </button>
                    </div>
                    <button
                      onClick={handleSave}
                      className="w-full border border-white/30 text-white font-medium py-2 rounded-lg hover:bg-white/10 transition-colors text-sm"
                    >
                      Save to History
                    </button>
                  </div>
                </>
              ) : (
                <div className="text-primary-100 text-sm">
                  {clicksError || impressionsError
                    ? "Fix the errors above to calculate"
                    : "Enter clicks and impressions to calculate"}
                </div>
              )}
            </div>

          </div>

          {/* Right: Results */}
          <div className="lg:col-span-8 space-y-5">

            {/* Quick Presets */}
            <div className="bg-white rounded-xl border border-gray-100 shadow-sm p-5">
              <h3 className="text-sm font-semibold text-gray-800 mb-3" style={{ fontFamily: "var(--font-heading)" }}>
                Quick Examples
              </h3>
              <div className="flex flex-wrap gap-2">
                {PRESETS.map((p) => {
                  const active =
                    clicks === String(p.clicks) && impressions === String(p.impressions);
                  return (
                    <button
                      key={p.label}
                      onClick={() => handlePreset(p)}
                      className={`px-3 py-1.5 rounded-lg text-sm font-mono font-medium transition-colors border ${
                        active
                          ? "bg-primary text-white border-primary"
                          : "bg-gray-50 text-gray-700 border-gray-200 hover:bg-gray-100"
                      }`}
                    >
                      {p.label}
                    </button>
                  );
                })}
              </div>
            </div>

            {/* Calculation Breakdown */}
            <div className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
              <div className="p-5 border-b border-gray-100 bg-gray-50/50">
                <h3 className="font-semibold text-gray-800 text-sm" style={{ fontFamily: "var(--font-heading)" }}>
                  Calculation Breakdown
                </h3>
              </div>
              {result ? (
                <div className="divide-y divide-gray-50">
                  {[
                    { label: "Clicks", value: formatNumber(result.clicks), mono: true },
                    { label: "Impressions", value: formatNumber(result.impressions), mono: true },
                    { label: "Formula", value: result.formula, mono: true },
                    { label: "CTR", value: result.ctrFormatted, mono: true, highlight: true },
                    { label: "Performance", value: result.performanceLabel, mono: false },
                  ].map(({ label, value, mono, highlight }) => (
                    <div
                      key={label}
                      className="flex items-center justify-between px-5 py-3 hover:bg-gray-50 transition-colors"
                    >
                      <span className="text-sm text-gray-600">{label}</span>
                      <span
                        className={`text-sm font-semibold ${
                          mono ? "font-mono" : ""
                        } ${highlight ? "text-primary text-base" : "text-gray-900"}`}
                      >
                        {value}
                      </span>
                    </div>
                  ))}
                </div>
              ) : (
                <div className="p-8 text-center text-gray-400 text-sm">
                  {clicksError || impressionsError
                    ? clicksError || impressionsError
                    : "Enter values above to see the breakdown"}
                </div>
              )}
            </div>

            {/* Performance Guide */}
            <div className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
              <div className="p-5 border-b border-gray-100 bg-gray-50/50">
                <h3 className="font-semibold text-gray-800 text-sm" style={{ fontFamily: "var(--font-heading)" }}>
                  Performance Reference
                </h3>
              </div>
              <div className="divide-y divide-gray-50">
                {[
                  { level: "excellent" as const, label: "Excellent", range: "≥ 5.00%", desc: "Outstanding engagement" },
                  { level: "good" as const, label: "Good", range: "3.00% – 4.99%", desc: "Above average performance" },
                  { level: "average" as const, label: "Average", range: "1.50% – 2.99%", desc: "Typical industry range" },
                  { level: "low" as const, label: "Low", range: "0.50% – 1.49%", desc: "Room for improvement" },
                  { level: "very-low" as const, label: "Very Low", range: "< 0.50%", desc: "Consider reviewing your targeting or copy" },
                ].map(({ level, label, range, desc }) => {
                  const s = PERFORMANCE_STYLES[level];
                  const isActive = result?.performanceLevel === level;
                  return (
                    <div
                      key={level}
                      className={`flex items-center justify-between px-5 py-3 transition-colors ${
                        isActive ? "bg-primary/5" : "hover:bg-gray-50"
                      }`}
                    >
                      <div className="flex items-center gap-3">
                        <span className={`inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full text-xs font-semibold ${s.bg} ${s.text} ${s.border} border`}>
                          <span className={`w-1.5 h-1.5 rounded-full ${s.dot}`} />
                          {label}
                        </span>
                        <span className="text-xs text-gray-500">{desc}</span>
                      </div>
                      <span className="text-xs font-mono font-semibold text-gray-700">{range}</span>
                    </div>
                  );
                })}
              </div>
              <p className="text-xs text-gray-400 px-5 py-3 border-t border-gray-50">
                * Benchmarks are general guidelines. Good CTR varies by industry, channel, and campaign type.
              </p>
            </div>

            {/* History */}
            {showHistory && (
              <div className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
                <div className="p-4 border-b border-gray-100 bg-gray-50/50 flex items-center justify-between">
                  <h3 className="font-semibold text-gray-800 text-sm" style={{ fontFamily: "var(--font-heading)" }}>
                    Calculation History
                  </h3>
                  {history.length > 0 && (
                    <button
                      onClick={handleClearHistory}
                      className="text-xs text-red-600 hover:text-red-700 font-medium"
                    >
                      Clear All
                    </button>
                  )}
                </div>
                <div className="divide-y divide-gray-50 max-h-72 overflow-y-auto">
                  {history.length === 0 ? (
                    <div className="p-6 text-center text-gray-400 text-sm">
                      No saved calculations yet
                    </div>
                  ) : (
                    history.map((entry) => (
                      <div
                        key={entry.id}
                        onClick={() => loadFromHistory(entry)}
                        className="p-4 hover:bg-gray-50 cursor-pointer transition-colors"
                      >
                        <div className="flex items-center justify-between mb-1">
                          <span className="font-mono text-sm font-semibold text-gray-900">
                            {formatNumber(entry.clicks)} clicks / {formatNumber(entry.impressions)} impr.
                          </span>
                          <span className="text-xs text-gray-400">
                            {new Date(entry.timestamp).toLocaleString("en-US")}
                          </span>
                        </div>
                        <div className="text-xs text-primary font-mono font-semibold">
                          CTR: {entry.result.ctrFormatted} · {entry.result.performanceLabel}
                        </div>
                      </div>
                    ))
                  )}
                </div>
              </div>
            )}

          </div>
        </div>
      </div>

      <CTRCalculatorSEO />

      <RelatedTools
        currentTool="ctr-calculator"
        tools={[
          "percentage-calculator",
          "discount-calculator",
          "investment-return-calculator",
          "gst-vat-calculator",
          "salary-calculator",
          "simple-interest-calculator",
        ]}
      />
    </>
  );
}
