export interface Appliance {
  id: string;
  name: string;
  wattage: number;
  hoursPerDay: number;
}

export interface CalculationResult {
  dailyKwh: number;
  monthlyKwh: number;
  yearlyKwh: number;
  monthlyCost: number;
  yearlyCost: number;
}

export interface ApplianceResult extends Appliance, CalculationResult {}

const DAYS_PER_MONTH = 30;
const MONTHS_PER_YEAR = 12;

export const calculateApplianceConsumption = (
  wattage: number,
  hoursPerDay: number,
  ratePerKwh: number
): CalculationResult => {
  const dailyKwh = (wattage * hoursPerDay) / 1000;
  const monthlyKwh = dailyKwh * DAYS_PER_MONTH;
  const yearlyKwh = monthlyKwh * MONTHS_PER_YEAR;
  const monthlyCost = monthlyKwh * ratePerKwh;
  const yearlyCost = yearlyKwh * ratePerKwh;

  return {
    dailyKwh: Math.round(dailyKwh * 10000) / 10000,
    monthlyKwh: Math.round(monthlyKwh * 100) / 100,
    yearlyKwh: Math.round(yearlyKwh * 100) / 100,
    monthlyCost: Math.round(monthlyCost * 100) / 100,
    yearlyCost: Math.round(yearlyCost * 100) / 100,
  };
};

export const calculateTotalConsumption = (
  appliances: Appliance[],
  ratePerKwh: number
) => {
  const results = appliances.map((app) => ({
    ...app,
    ...calculateApplianceConsumption(app.wattage, app.hoursPerDay, ratePerKwh),
  }));

  const totals = {
    dailyKwh: Math.round(results.reduce((sum, r) => sum + r.dailyKwh, 0) * 10000) / 10000,
    monthlyKwh: Math.round(results.reduce((sum, r) => sum + r.monthlyKwh, 0) * 100) / 100,
    yearlyKwh: Math.round(results.reduce((sum, r) => sum + r.yearlyKwh, 0) * 100) / 100,
    monthlyCost: Math.round(results.reduce((sum, r) => sum + r.monthlyCost, 0) * 100) / 100,
    yearlyCost: Math.round(results.reduce((sum, r) => sum + r.yearlyCost, 0) * 100) / 100,
  };

  return { results, totals };
};

export const generateCSV = (appliances: Appliance[], ratePerKwh: number): string => {
  const { results, totals } = calculateTotalConsumption(appliances, ratePerKwh);

  let csv = "Appliance,Wattage (W),Hours/Day,Daily (kWh),Monthly (kWh),Yearly (kWh),Monthly Cost ($),Yearly Cost ($)\n";

  results.forEach((app) => {
    csv += `"${app.name}",${app.wattage},${app.hoursPerDay},${app.dailyKwh},${app.monthlyKwh},${app.yearlyKwh},${app.monthlyCost},${app.yearlyCost}\n`;
  });

  csv += `\nTOTAL,,,${totals.dailyKwh},${totals.monthlyKwh},${totals.yearlyKwh},${totals.monthlyCost},${totals.yearlyCost}\n`;
  csv += `\nElectricity Rate ($/kWh),${ratePerKwh}\n`;
  csv += `Generated by Productive Toolbox - Power Consumption Calculator\n`;

  return csv;
};

export const downloadCSV = (appliances: Appliance[], ratePerKwh: number) => {
  const csv = generateCSV(appliances, ratePerKwh);
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);

  link.setAttribute("href", url);
  link.setAttribute("download", `power-consumption-${new Date().toISOString().split("T")[0]}.csv`);
  link.style.visibility = "hidden";

  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};

export const saveToLocalStorage = (appliances: Appliance[], ratePerKwh: number) => {
  const data = { appliances, ratePerKwh, timestamp: new Date().toISOString() };
  localStorage.setItem("powerConsumptionData", JSON.stringify(data));
};

export const loadFromLocalStorage = (): { appliances: Appliance[]; ratePerKwh: number } | null => {
  const data = localStorage.getItem("powerConsumptionData");
  if (!data) return null;

  try {
    const parsed = JSON.parse(data);
    return { appliances: parsed.appliances || [], ratePerKwh: parsed.ratePerKwh || 0.12 };
  } catch {
    return null;
  }
};

export const clearLocalStorage = () => {
  localStorage.removeItem("powerConsumptionData");
};

export const generateSummaryText = (appliances: Appliance[], ratePerKwh: number): string => {
  const { results, totals } = calculateTotalConsumption(appliances, ratePerKwh);

  let text = "Power Consumption Summary\n";
  text += "=".repeat(50) + "\n\n";

  results.forEach((app) => {
    text += `${app.name}\n`;
    text += `  Wattage: ${app.wattage}W | Hours/Day: ${app.hoursPerDay}h\n`;
    text += `  Daily: ${app.dailyKwh} kWh | Monthly: ${app.monthlyKwh} kWh | Yearly: ${app.yearlyKwh} kWh\n`;
    text += `  Monthly Cost: $${app.monthlyCost} | Yearly Cost: $${app.yearlyCost}\n\n`;
  });

  text += "=".repeat(50) + "\n";
  text += `TOTAL CONSUMPTION\n`;
  text += `  Daily: ${totals.dailyKwh} kWh\n`;
  text += `  Monthly: ${totals.monthlyKwh} kWh\n`;
  text += `  Yearly: ${totals.yearlyKwh} kWh\n\n`;
  text += `TOTAL COST\n`;
  text += `  Monthly: $${totals.monthlyCost}\n`;
  text += `  Yearly: $${totals.yearlyCost}\n\n`;
  text += `Electricity Rate: $${ratePerKwh}/kWh\n`;
  text += `Generated by Productive Toolbox - Power Consumption Calculator\n`;

  return text;
};
