export const feedRateCalculatorConfig = {
  name: "Feed Rate Calculator",
  slug: "feed-rate-calculator",
  description: "Calculate CNC machining feed rate instantly using spindle RPM, number of flutes, and feed per tooth (chip load). Supports metric and imperial units for milling, drilling, and CNC operations.",
  category: "mechanical",
  icon: "⚙️",
  free: true,
  seo: {
    title: "Free Feed Rate Calculator – CNC & Machining Feed Speed Calculator",
    description: "Calculate CNC machining feed rate instantly using RPM, flutes, and chip load. Free online feed rate calculator for milling, drilling, and machining operations. Supports metric and imperial units.",
    keywords: [
      "feed rate calculator",
      "cnc feed calculator",
      "machining feed rate",
      "milling feed calculator",
      "chip load calculator",
      "cnc machining calculator",
      "feed speed calculator",
      "feed per tooth calculator",
      "spindle feed rate",
      "milling feed rate formula",
      "cnc feed rate formula",
      "machining calculator online",
      "feed rate mm per min",
      "cutting feed rate calculator",
      "flute feed rate calculator",
    ],
    og: {
      title: "Free Feed Rate Calculator – CNC & Machining Feed Speed Calculator",
      description: "Calculate CNC machining feed rate instantly using RPM, flutes, and chip load. Free online feed rate calculator for milling, drilling, and machining operations.",
      url: "https://www.productivetoolbox.com/tools/mechanical/feed-rate-calculator",
    },
  },
  relatedTools: [
    "cutting-speed-calculator",
    "lathe-speed-calculator",
    "torque-calculator",
    "angular-velocity-calculator",
    "thread-pitch-calculator",
    "gear-ratio-calculator",
  ],
};
