import { siteConfig } from "@/config/site";

export const engagementRateCalculatorConfig = {
  slug: "engagement-rate-calculator",
  name: "Engagement Rate Calculator",
  description: "Calculate social media engagement rate using industry-standard formulas — by followers, reach, impressions, or video views. Supports Instagram, TikTok, Facebook, YouTube, LinkedIn, and X (Twitter). Free browser-based calculator with instant results and downloadable reports.",
  category: "marketing",
  icon: "💬",
  free: true,
  seo: {
    title: "Free Engagement Rate Calculator – Instagram, TikTok, Facebook & Social Media Engagement Calculator",
    description: "Calculate engagement rate instantly using industry-standard formulas for Instagram, TikTok, Facebook, YouTube, LinkedIn, X (Twitter), and more. Free online engagement calculator with live results and downloadable reports.",
    keywords: [
      "engagement rate calculator",
      "instagram engagement calculator",
      "tiktok engagement calculator",
      "social media engagement calculator",
      "engagement percentage calculator",
      "engagement rate formula",
      "influencer engagement calculator",
      "marketing calculator",
      "engagement rate by followers",
      "engagement rate by reach",
      "engagement rate by impressions",
      "cost per engagement calculator",
      "facebook engagement calculator",
      "youtube engagement calculator",
      "linkedin engagement calculator",
      "free engagement calculator",
      "social media analytics",
      "creator engagement",
      "brand engagement",
      "engagement metrics",
      "digital marketing tools",
      "social media roi",
    ],
    openGraph: {
      title: "Engagement Rate Calculator – Free Social Media Engagement Calculator",
      description: "Calculate engagement rate by followers, reach, impressions, or views. Instant results, performance ratings, and CSV/TXT export — all in your browser.",
      type: "website",
      url: `${siteConfig.url}/tools/marketing/engagement-rate-calculator`,
    },
  },
};
