export const toolConfig = {
  slug: "pie-chart-maker",
  name: "Pie Chart Maker",
  description: "Create dynamic pie charts from your data instantly. Customize colors, labels, and export as PNG or SVG.",
  category: "visualization",
  icon: "📊",
  free: true,
  backend: false,
  seo: {
    title: "Pie Chart Maker Online – Create Pie Charts Instantly",
    description: "Free online Pie Chart Maker. Create dynamic pie charts from your data instantly using SVG or Canvas. Customize colors, labels, and export charts as PNG or SVG.",
    keywords: [
      "pie chart maker",
      "pie chart generator",
      "create pie chart",
      "online pie chart",
      "pie chart tool",
      "data visualization",
      "chart maker",
      "free pie chart",
      "pie chart creator",
      "svg pie chart",
      "canvas pie chart",
      "interactive pie chart",
      "pie chart download",
      "pie chart export",
      "business chart"
    ],
    openGraph: {
      title: "Pie Chart Maker - Create Dynamic Pie Charts Online",
      description: "Fast, free pie chart maker. Create and customize pie charts instantly in your browser. Export as PNG or SVG.",
      type: "website",
      url: "/tools/pie-chart-maker"
    },
    faq: [
      { q: "How are pie chart percentages calculated?", a: "Each slice's share is its value divided by the total, times 100. For values 40, 35 and 25 the total is 100, so the slices are 40%, 35% and 25%, covering 144°, 126° and 90° of the circle." },
      { q: "Can I import data from a spreadsheet?", a: "Yes. Paste or import CSV with a label and a value on each row, and the chart updates with one slice per row." },
      { q: "Which export formats are supported?", a: "PNG for documents and slides, SVG for crisp scaling on the web and in design tools, and CSV for the underlying data." },
      { q: "When should I not use a pie chart?", a: "When there are more than about 5–7 categories, when the values are close to each other, or when you want to compare changes over time. A bar chart is easier to read in those cases." },
      { q: "Is my data saved?", a: "Yes, the chart data is saved so it is still there when you return." },
    ],
  },
  features: [
    "Dynamic pie chart rendering with SVG",
    "Real-time chart updates",
    "Customizable colors for each slice",
    "Interactive data table editor",
    "Animated chart rendering",
    "Hover tooltips with details",
    "Legend generator",
    "Random data generator",
    "Export as PNG or SVG",
    "CSV data import/export",
    "Chart title customization",
    "Show/hide percentages and labels",
    "Dark/Light theme toggle",
    "Responsive design for all devices",
    "Chart history",
    "Private: your inputs are not collected or stored"
  ]
};
