import { siteConfig } from "@/config/site";

export const parkingSpaceCalculatorConfig = {
  name: "Parking Space Calculator",
  slug: "parking-space-calculator",
  description: "Calculate how many parking stalls fit in a given lot area, or how much space a target number of vehicles requires. Supports 90°/60°/45° layouts, ADA compliance, and demand estimation.",
  category: "architecture",
  icon: "🅿️",
  free: true,
  backend: false,
  seo: {
    title: "Parking Space Calculator — Free Parking Lot Layout Tool | Productive Toolbox",
    description: "Calculate parking stall count from lot area or required area from stall count. Free parking lot calculator with ADA, 90°/60°/45° layouts, and demand mode. No signup.",
    keywords: [
      "parking space calculator",
      "parking lot layout calculator",
      "parking area calculator",
      "parking lot calculator",
      "parking stall calculator",
      "parking demand calculator",
      "car parking calculator",
      "parking lot spacing calculator",
      "how many parking spaces per square foot",
      "parking space dimensions",
      "ADA parking calculator",
      "parking lot design calculator",
      "number of parking spaces calculator",
      "parking stall count calculator",
      "free parking lot layout calculator",
      "parking space calculator online",
      "parking lot measurements calculator",
      "parking spaces per acre",
      "parking requirement calculator",
      "surface parking lot calculator",
      "parking lot capacity calculator",
      "accessible parking space calculator",
      "parking ratio calculator",
      "car park space calculator",
      "parking calculator free",
    ],
    openGraph: {
      title: "Parking Space Calculator — Free Parking Lot Layout Tool Online",
      description: "Calculate parking stall count from lot area or required area from stall count. ADA compliance, 90°/60°/45° layouts, demand mode. Browser-based, free.",
      type: "website",
      url: `${siteConfig.url}/tools/architecture/parking-space-calculator`,
    },
    howToSteps: [
      { name: "Enter Your Lot Dimensions", text: "Input the available parking area in square feet, square meters, or as length × width. Subtract the building footprint and required setbacks from the total parcel area before entering." },
      { name: "Select Parking Angle and Stall Type", text: "Choose 90° (perpendicular), 60°, or 45° layout. Select stall type: standard, compact, or ADA. Stall dimensions and aisle width update automatically." },
      { name: "Configure Aisle Traffic Direction", text: "Select one-way or two-way traffic. Two-way aisles (24 ft) work with 90° layouts. One-way aisles (18–20 ft) suit 60° and 45° angled layouts." },
      { name: "Read Stall Count and ADA Requirements", text: "The calculator returns total stalls, required ADA and van-accessible spaces, aisle count, paved area, and lot efficiency ratio." },
      { name: "Use Demand Mode", text: "Switch to demand mode, enter building type and floor area, and confirm the required stall count from your local zoning baseline." },
      { name: "Export Layout Summary", text: "Download the stall count report as PDF or text for planning applications, design briefs, or client presentations." },
    ],
    faq: [
      { q: "What is a parking space calculator?", a: "A parking space calculator is a free online tool that determines how many parking stalls fit in a given lot area, factoring in stall dimensions, aisle width, parking angle, and ADA requirements. It is used by architects, civil engineers, urban planners, and developers during site feasibility and design review." },
      { q: "How many square feet does a parking space require?", a: "A standard 90° stall requires 162–180 sq ft of stall area. Including the proportional aisle share (24 ft wide for two-way), total area per stall is approximately 300–350 sq ft. Compact stalls require around 270–300 sq ft per space including aisle." },
      { q: "What are standard parking space dimensions?", a: "Standard stall: 8.5–9 ft wide × 18–20 ft deep. Compact: 7.5–8 ft × 15–16 ft. ADA accessible: 8 ft wide with a 5 ft access aisle. Van-accessible: 8 ft wide with an 8 ft access aisle. Drive aisle: 24 ft (two-way 90°), 18–20 ft (one-way angled)." },
      { q: "How many parking spaces fit in an acre?", a: "A 1-acre (43,560 sq ft) surface lot at 90° layout fits approximately 78–100 stalls in practice, after accounting for entrance drives, landscaping buffers, and unusable corners. The theoretical maximum at 330 sq ft per stall is about 132 stalls." },
      { q: "How many parking spaces are required by code?", a: "Parking requirements vary by jurisdiction and use type. Common baselines: retail 3–5 spaces per 1,000 sq ft GFA; office 3–4 per 1,000 sq ft; restaurant 1 per 3–4 seats; residential 1–2 per unit. ADA requires 1 accessible space per 25 total (4%), with 1 in 6 accessible spaces being van-accessible." },
      { q: "What is a parking demand calculator?", a: "A parking demand calculator estimates how many parking spaces a facility needs based on building type, occupancy, and peak usage. This tool covers both physical capacity (how many stalls fit) and demand estimation (how many stalls are required by code or projected usage)." },
      { q: "How does parking angle affect stall count?", a: "At 90°, stalls are perpendicular to the aisle and two-way traffic is possible — this yields the highest stall count per area. At 60° and 45°, stalls are angled with one-way aisles — easier maneuvering but lower stall density per area." },
      { q: "What is lot efficiency ratio?", a: "Lot efficiency ratio is stall area divided by total lot area, expressed as a percentage. A well-designed surface lot achieves 60–70%. Below 55% usually indicates poor geometry or too many aisles. Above 75% may mean insufficient pedestrian and landscape space." },
      { q: "How do I calculate ADA parking requirements?", a: "ADA requires 1 accessible space per 25 total stalls (4% minimum). Of the accessible spaces, 1 in 6 must be van-accessible (8 ft access aisle instead of 5 ft). Enter your total stall count and this calculator returns both the accessible and van-accessible requirements automatically." },
      { q: "Is my data private when using this calculator?", a: "Yes. All calculations run entirely in your browser using JavaScript. Your lot dimensions, stall counts, and inputs are never transmitted to any server or stored anywhere outside your device." },
    ],
  },
  features: [
    "Total stall count from lot area",
    "Required lot area from target stall count",
    "ADA and van-accessible stall count",
    "90°, 60°, and 45° layout options",
    "Standard, compact, and ADA stall types",
    "One-way and two-way aisle configuration",
    "Lot efficiency ratio",
    "Parking demand mode by building type",
    "US standard and metric dimensions",
    "Visual layout diagram",
    "Export layout summary",
    "No signup required",
  ],
  relatedTools: [
    "shadow-length-calculator",
    "structural-load-calculator",
    "floor-area-calculator",
    "land-area-calculator-square-meter",
    "room-volume-calculator",
    "building-height-calculator",
  ],
};
