import { Unit, ShadowInputs, ShadowCalculation, HistoryEntry } from "./types";

const HISTORY_KEY = "shadow-length-calculator-history";
const MAX_HISTORY = 5;

// Conversion factors
const METERS_TO_FEET = 3.28084;
const FEET_TO_METERS = 0.3048;

/**
 * Calculate shadow length using trigonometry
 * Formula: Shadow Length = Height / tan(angle)
 */
export function calculateShadowLength(inputs: ShadowInputs): ShadowCalculation {
  const { objectHeight, sunAngle, unit } = inputs;
  
  // Convert angle to radians
  const angleRadians = (sunAngle * Math.PI) / 180;
  
  // Calculate shadow length
  const shadowLength = objectHeight / Math.tan(angleRadians);
  
  // Convert to opposite unit for reference
  let shadowLengthConverted: number | undefined;
  if (unit === "meters") {
    shadowLengthConverted = shadowLength * METERS_TO_FEET;
  } else {
    shadowLengthConverted = shadowLength * FEET_TO_METERS;
  }
  
  return {
    objectHeight,
    sunAngle,
    unit,
    shadowLength,
    shadowLengthConverted,
    timestamp: Date.now()
  };
}

/**
 * Convert between units
 */
export function convertUnit(value: number, fromUnit: Unit, toUnit: Unit): number {
  if (fromUnit === toUnit) return value;
  
  if (fromUnit === "meters" && toUnit === "feet") {
    return value * METERS_TO_FEET;
  } else if (fromUnit === "feet" && toUnit === "meters") {
    return value * FEET_TO_METERS;
  }
  
  return value;
}

/**
 * Validate inputs
 */
export function validateInputs(height: number, angle: number): string | null {
  if (!height || height <= 0) {
    return "Object height must be greater than 0";
  }
  
  if (!angle || angle <= 0 || angle >= 90) {
    return "Sun angle must be between 1° and 89°";
  }
  
  return null;
}

/**
 * Format number with specified decimal places
 */
export function formatNumber(value: number, decimals: number = 2): string {
  return value.toFixed(decimals);
}

/**
 * Get unit label
 */
export function getUnitLabel(unit: Unit): string {
  return unit === "meters" ? "m" : "ft";
}

/**
 * Get opposite unit
 */
export function getOppositeUnit(unit: Unit): Unit {
  return unit === "meters" ? "feet" : "meters";
}

/**
 * Get opposite unit label
 */
export function getOppositeUnitLabel(unit: Unit): string {
  return unit === "meters" ? "ft" : "m";
}

// History management
export function saveToHistory(calculation: ShadowCalculation): void {
  if (typeof window === 'undefined') return;
  
  const history = getHistory();
  const entry: HistoryEntry = {
    id: `${Date.now()}-${Math.random()}`,
    timestamp: Date.now(),
    calculation
  };
  
  history.unshift(entry);
  const trimmed = history.slice(0, MAX_HISTORY);
  
  try {
    localStorage.setItem(HISTORY_KEY, JSON.stringify(trimmed));
  } catch (e) {
    console.error('Failed to save history:', e);
  }
}

export function getHistory(): HistoryEntry[] {
  if (typeof window === 'undefined') return [];
  
  try {
    const stored = localStorage.getItem(HISTORY_KEY);
    return stored ? JSON.parse(stored) : [];
  } catch (e) {
    console.error('Failed to load history:', e);
    return [];
  }
}

export function clearHistory(): void {
  if (typeof window === 'undefined') return;
  
  try {
    localStorage.removeItem(HISTORY_KEY);
  } catch (e) {
    console.error('Failed to clear history:', e);
  }
}

/**
 * Export calculation as text
 */
export function exportToText(calculation: ShadowCalculation): string {
  const unitLabel = getUnitLabel(calculation.unit);
  const oppositeUnitLabel = getOppositeUnitLabel(calculation.unit);
  
  return `SHADOW LENGTH CALCULATION
${'='.repeat(40)}

Object Height: ${formatNumber(calculation.objectHeight, 2)} ${unitLabel}
Sun Elevation Angle: ${formatNumber(calculation.sunAngle, 1)}°

Shadow Length: ${formatNumber(calculation.shadowLength, 2)} ${unitLabel}
(${formatNumber(calculation.shadowLengthConverted || 0, 2)} ${oppositeUnitLabel})

Formula: Shadow Length = Height / tan(angle)

Date: ${new Date(calculation.timestamp).toLocaleString()}

${'='.repeat(40)}
Generated by Shadow Length Calculator`;
}

/**
 * Debounce function
 */
export function debounce<T extends (...args: any[]) => any>(
  func: T,
  wait: number
): (...args: Parameters<T>) => void {
  let timeout: NodeJS.Timeout | null = null;
  
  return function executedFunction(...args: Parameters<T>) {
    const later = () => {
      timeout = null;
      func(...args);
    };
    
    if (timeout) {
      clearTimeout(timeout);
    }
    timeout = setTimeout(later, wait);
  };
}
